import type { Concept } from "@/lib/learning/types";

/** Legacy seeded concepts. Kept so old progress and lessons do not crash. */
export const RETIRED_CONCEPTS: Concept[] = [
  {
    id: "ast-hr",
    name: "The Hertzsprung–Russell diagram",
    category: "astronomy",
    prerequisites: [],
    level: "intro",
    summary: "Luminosity versus temperature as a map of stellar lives.",
  },
  {
    id: "ast-exo",
    name: "Exoplanet detection",
    category: "astronomy",
    parentId: "ast-hr",
    prerequisites: ["ast-hr"],
    level: "core",
    summary: "Transits, radial velocity, and what each method cannot see.",
  },
  {
    id: "bio-selection",
    name: "Natural selection",
    category: "evo-bio",
    prerequisites: [],
    level: "intro",
    summary: "Differential reproductive success, not progress.",
  },
  {
    id: "bio-evodevo",
    name: "Evo-devo",
    category: "evo-bio",
    parentId: "bio-selection",
    prerequisites: ["bio-selection"],
    level: "core",
    summary: "How developmental toolkits make large morphological jumps cheap.",
  },
  {
    id: "econ-ca",
    name: "Comparative advantage",
    category: "economics",
    prerequisites: [],
    level: "intro",
    summary: "Opportunity cost, not absolute productivity.",
  },
  {
    id: "econ-money",
    name: "Monetary policy",
    category: "economics",
    parentId: "econ-ca",
    prerequisites: ["econ-ca"],
    level: "core",
    summary: "Rates, reserves, and the transmission the press compresses.",
  },
  {
    id: "stat-bias",
    name: "Sampling bias",
    category: "statistics",
    prerequisites: [],
    level: "intro",
    summary: "Who is in the data is the result.",
  },
  {
    id: "stat-pvalue",
    name: "P-values",
    category: "statistics",
    parentId: "stat-bias",
    prerequisites: ["stat-bias"],
    level: "core",
    summary: "A tail probability under a model, not the chance you are right.",
  },
  {
    id: "stat-bayes",
    name: "Bayes in practice",
    category: "statistics",
    parentId: "stat-pvalue",
    prerequisites: ["stat-pvalue"],
    level: "journalist",
    summary: "Priors, likelihoods, and why base rates refuse to die.",
  },
  {
    id: "aud-freq",
    name: "Frequency response",
    category: "audio",
    prerequisites: [],
    level: "intro",
    summary: "What a system does to amplitude versus frequency.",
  },
  {
    id: "aud-comp",
    name: "Compression",
    category: "audio",
    parentId: "aud-freq",
    prerequisites: ["aud-freq"],
    level: "core",
    summary: "Threshold, ratio, attack, release — gain reduction as time.",
  },
  {
    id: "hist-method",
    name: "How historians argue",
    category: "history",
    prerequisites: [],
    level: "intro",
    summary: "Sources, causation, and the difference between chronicle and claim.",
  },
  {
    id: "hist-nixon",
    name: "The Nixon shock",
    category: "history",
    parentId: "hist-method",
    prerequisites: ["hist-method"],
    level: "journalist",
    summary: "Ending gold convertibility and the monetary order that followed.",
  },
];
