/* Generated by scripts/generate-curriculum.mjs — do not edit by hand. */
import type { CourseManifest } from "../schema";
import cpu_foundations from "./cpu-foundations.json" with { type: "json" };
import cpu_microarch from "./cpu-microarch.json" with { type: "json" };
import arch_gpu from "./arch-gpu.json" with { type: "json" };
import semi_process from "./semi-process.json" with { type: "json" };
import semi_litho from "./semi-litho.json" with { type: "json" };
import semi_leading from "./semi-leading.json" with { type: "json" };
import os_foundations from "./os-foundations.json" with { type: "json" };
import os_concurrency from "./os-concurrency.json" with { type: "json" };
import os_storage from "./os-storage.json" with { type: "json" };
import net_foundations from "./net-foundations.json" with { type: "json" };
import net_transport from "./net-transport.json" with { type: "json" };
import net_internet from "./net-internet.json" with { type: "json" };
import cmp_frontend from "./cmp-frontend.json" with { type: "json" };
import cmp_ir from "./cmp-ir.json" with { type: "json" };
import cmp_backend from "./cmp-backend.json" with { type: "json" };
import ml_foundations from "./ml-foundations.json" with { type: "json" };
import ml_neural from "./ml-neural.json" with { type: "json" };
import ml_transformers from "./ml-transformers.json" with { type: "json" };
import horo_foundations from "./horo-foundations.json" with { type: "json" };
import horo_regulation from "./horo-regulation.json" with { type: "json" };
import horo_complications from "./horo-complications.json" with { type: "json" };
import mus_foundations from "./mus-foundations.json" with { type: "json" };
import mus_harmony from "./mus-harmony.json" with { type: "json" };
import mus_heavy from "./mus-heavy.json" with { type: "json" };
import dm_history from "./dm-history.json" with { type: "json" };
import dm_construction from "./dm-construction.json" with { type: "json" };
import dm_advanced from "./dm-advanced.json" with { type: "json" };

export const MANIFESTS = [
  cpu_foundations,
  cpu_microarch,
  arch_gpu,
  semi_process,
  semi_litho,
  semi_leading,
  os_foundations,
  os_concurrency,
  os_storage,
  net_foundations,
  net_transport,
  net_internet,
  cmp_frontend,
  cmp_ir,
  cmp_backend,
  ml_foundations,
  ml_neural,
  ml_transformers,
  horo_foundations,
  horo_regulation,
  horo_complications,
  mus_foundations,
  mus_harmony,
  mus_heavy,
  dm_history,
  dm_construction,
  dm_advanced,
] as unknown as CourseManifest[];

export const MANIFEST_IDS = [
  "cpu-foundations",
  "cpu-microarch",
  "arch-gpu",
  "semi-process",
  "semi-litho",
  "semi-leading",
  "os-foundations",
  "os-concurrency",
  "os-storage",
  "net-foundations",
  "net-transport",
  "net-internet",
  "cmp-frontend",
  "cmp-ir",
  "cmp-backend",
  "ml-foundations",
  "ml-neural",
  "ml-transformers",
  "horo-foundations",
  "horo-regulation",
  "horo-complications",
  "mus-foundations",
  "mus-harmony",
  "mus-heavy",
  "dm-history",
  "dm-construction",
  "dm-advanced"
] as const;
