import type { Concept } from "@/lib/learning/types";

export const CONCEPTS: Concept[] = [
  {
    id: "cpu-pipeline",
    name: "Instruction pipelines",
    category: "cpu",
    prerequisites: [],
    level: "intro",
    summary: "Breaking instruction execution into overlapping stages.",
  },
  {
    id: "cpu-hazards",
    name: "Pipeline hazards",
    category: "cpu",
    parentId: "cpu-pipeline",
    prerequisites: ["cpu-pipeline"],
    level: "core",
    summary: "Data, control, and structural stalls that break ideal overlap.",
  },
  {
    id: "cpu-branch-prediction",
    name: "Branch prediction",
    category: "cpu",
    parentId: "cpu-pipeline",
    prerequisites: ["cpu-pipeline"],
    level: "core",
    summary: "Guessing control flow so the pipeline stays full.",
  },
  {
    id: "cpu-btb",
    name: "Branch target buffers",
    category: "cpu",
    parentId: "cpu-branch-prediction",
    prerequisites: ["cpu-branch-prediction"],
    level: "journalist",
    summary: "Caching where a branch went last time, not just taken/not-taken.",
  },
  {
    id: "cpu-predictors",
    name: "Predictor types",
    category: "cpu",
    parentId: "cpu-branch-prediction",
    prerequisites: ["cpu-branch-prediction"],
    level: "journalist",
    summary: "Local, global, and TAGE-style predictors and why they exist.",
  },
  {
    id: "cpu-ras",
    name: "Return address stacks",
    category: "cpu",
    parentId: "cpu-branch-prediction",
    prerequisites: ["cpu-branch-prediction"],
    level: "journalist",
    summary: "Special-casing CALL/RET so returns do not pollute the BTB.",
  },
  {
    id: "cpu-renaming",
    name: "Register renaming",
    category: "cpu",
    parentId: "cpu-pipeline",
    prerequisites: ["cpu-pipeline"],
    level: "core",
    summary: "Mapping architectural names onto a larger physical file.",
  },
  {
    id: "cpu-rob",
    name: "Reorder buffers",
    category: "cpu",
    parentId: "cpu-renaming",
    prerequisites: ["cpu-renaming"],
    level: "journalist",
    summary: "Retiring out-of-order work in program order.",
  },
  {
    id: "cpu-coherency",
    name: "Cache coherency",
    category: "cpu",
    parentId: "cpu-pipeline",
    prerequisites: ["cpu-pipeline"],
    level: "core",
    summary: "Keeping private caches honest across cores.",
  },

  {
    id: "semi-litho",
    name: "Photolithography",
    category: "semiconductors",
    prerequisites: [],
    level: "intro",
    summary: "Projecting patterns into resist to define features.",
  },
  {
    id: "semi-euv",
    name: "EUV lithography",
    category: "semiconductors",
    parentId: "semi-litho",
    prerequisites: ["semi-litho"],
    level: "core",
    summary: "13.5 nm light, mirrors, and why refractive optics die.",
  },
  {
    id: "semi-na",
    name: "Numerical aperture",
    category: "semiconductors",
    parentId: "semi-euv",
    prerequisites: ["semi-euv"],
    level: "journalist",
    summary: "How High-NA EUV buys resolution and spends depth of focus.",
  },
  {
    id: "semi-overlay",
    name: "Overlay",
    category: "semiconductors",
    parentId: "semi-euv",
    prerequisites: ["semi-euv"],
    level: "journalist",
    summary: "Layer-to-layer alignment as a yield budget, not a slogan.",
  },
  {
    id: "semi-stochastics",
    name: "Stochastic defects",
    category: "semiconductors",
    parentId: "semi-euv",
    prerequisites: ["semi-euv"],
    level: "journalist",
    summary: "Photon and photoacid shot noise at EUV doses.",
  },

  {
    id: "os-process",
    name: "Processes and threads",
    category: "os",
    prerequisites: [],
    level: "intro",
    summary: "Address spaces, threads, and what isolation actually costs.",
  },
  {
    id: "os-vm",
    name: "Virtual memory",
    category: "os",
    parentId: "os-process",
    prerequisites: ["os-process"],
    level: "core",
    summary: "Pages, page tables, and the TLB as a cache of translations.",
  },
  {
    id: "os-sched",
    name: "CPU scheduling",
    category: "os",
    parentId: "os-process",
    prerequisites: ["os-process"],
    level: "core",
    summary: "Fairness, latency, and why CFS is not a real-time scheduler.",
  },

  {
    id: "net-stack",
    name: "The network stack",
    category: "networking",
    prerequisites: [],
    level: "intro",
    summary: "Layers as contracts, not a morality play.",
  },
  {
    id: "net-congestion",
    name: "Congestion control",
    category: "networking",
    parentId: "net-stack",
    prerequisites: ["net-stack"],
    level: "core",
    summary: "How senders share a pipe they cannot see.",
  },
  {
    id: "net-bgp",
    name: "BGP",
    category: "networking",
    parentId: "net-stack",
    prerequisites: ["net-stack"],
    level: "journalist",
    summary: "Policy routing between autonomous systems.",
  },

  {
    id: "cmp-front",
    name: "Lexing and parsing",
    category: "compilers",
    prerequisites: [],
    level: "intro",
    summary: "Turning characters into a tree the rest of the compiler can hate.",
  },
  {
    id: "cmp-ssa",
    name: "SSA form",
    category: "compilers",
    parentId: "cmp-front",
    prerequisites: ["cmp-front"],
    level: "core",
    summary: "Single assignment so dataflow becomes a graph problem.",
  },
  {
    id: "cmp-alloc",
    name: "Register allocation",
    category: "compilers",
    parentId: "cmp-ssa",
    prerequisites: ["cmp-ssa"],
    level: "journalist",
    summary: "Graph coloring, spilling, and the real cost of an extra live range.",
  },

  {
    id: "ml-gd",
    name: "Gradient descent",
    category: "ml",
    prerequisites: [],
    level: "intro",
    summary: "Following the slope of a loss you can actually compute.",
  },
  {
    id: "ml-backprop",
    name: "Backpropagation",
    category: "ml",
    parentId: "ml-gd",
    prerequisites: ["ml-gd"],
    level: "core",
    summary: "Reverse-mode autodiff, not a separate algorithm from calculus.",
  },
  {
    id: "ml-attention",
    name: "Attention",
    category: "ml",
    parentId: "ml-backprop",
    prerequisites: ["ml-backprop"],
    level: "journalist",
    summary: "QKV as a content-addressable lookup, and why it scales.",
  },

  {
    id: "ast-hr",
    name: "The Hertzsprung–Russell diagram",
    category: "astronomy",
    prerequisites: [],
    level: "intro",
    summary: "Luminosity versus temperature as a map of stellar lives.",
  },
  {
    id: "ast-exo",
    name: "Exoplanet detection",
    category: "astronomy",
    parentId: "ast-hr",
    prerequisites: ["ast-hr"],
    level: "core",
    summary: "Transits, radial velocity, and what each method cannot see.",
  },

  {
    id: "bio-selection",
    name: "Natural selection",
    category: "evo-bio",
    prerequisites: [],
    level: "intro",
    summary: "Differential reproductive success, not progress.",
  },
  {
    id: "bio-evodevo",
    name: "Evo-devo",
    category: "evo-bio",
    parentId: "bio-selection",
    prerequisites: ["bio-selection"],
    level: "core",
    summary: "How developmental toolkits make large morphological jumps cheap.",
  },

  {
    id: "econ-ca",
    name: "Comparative advantage",
    category: "economics",
    prerequisites: [],
    level: "intro",
    summary: "Opportunity cost, not absolute productivity.",
  },
  {
    id: "econ-money",
    name: "Monetary policy",
    category: "economics",
    parentId: "econ-ca",
    prerequisites: ["econ-ca"],
    level: "core",
    summary: "Rates, reserves, and the transmission the press compresses.",
  },

  {
    id: "stat-bias",
    name: "Sampling bias",
    category: "statistics",
    prerequisites: [],
    level: "intro",
    summary: "Who is in the data is the result.",
  },
  {
    id: "stat-pvalue",
    name: "P-values",
    category: "statistics",
    parentId: "stat-bias",
    prerequisites: ["stat-bias"],
    level: "core",
    summary: "A tail probability under a model, not the chance you are right.",
  },
  {
    id: "stat-bayes",
    name: "Bayes in practice",
    category: "statistics",
    parentId: "stat-pvalue",
    prerequisites: ["stat-pvalue"],
    level: "journalist",
    summary: "Priors, likelihoods, and why base rates refuse to die.",
  },

  {
    id: "horo-escape",
    name: "The escapement",
    category: "horology",
    prerequisites: [],
    level: "intro",
    summary: "Turning a spring’s unwind into counted ticks.",
  },
  {
    id: "horo-tourbillon",
    name: "The tourbillon",
    category: "horology",
    parentId: "horo-escape",
    prerequisites: ["horo-escape"],
    level: "core",
    summary: "Averaging positional error, and when it is theater.",
  },

  {
    id: "aud-freq",
    name: "Frequency response",
    category: "audio",
    prerequisites: [],
    level: "intro",
    summary: "What a system does to amplitude versus frequency.",
  },
  {
    id: "aud-comp",
    name: "Compression",
    category: "audio",
    parentId: "aud-freq",
    prerequisites: ["aud-freq"],
    level: "core",
    summary: "Threshold, ratio, attack, release — gain reduction as time.",
  },

  {
    id: "mus-interval",
    name: "Intervals and consonance",
    category: "music-theory",
    prerequisites: [],
    level: "intro",
    summary: "Ratios, beating, and why a fifth sits still.",
  },
  {
    id: "mus-modes",
    name: "Modes",
    category: "music-theory",
    parentId: "mus-interval",
    prerequisites: ["mus-interval"],
    level: "core",
    summary: "Same pitch set, different tonic gravity.",
  },

  {
    id: "dm-blast",
    name: "Blast beats",
    category: "death-metal",
    prerequisites: [],
    level: "intro",
    summary: "The drum grammar that made death metal possible.",
  },
  {
    id: "dm-harmony",
    name: "Death-metal harmony",
    category: "death-metal",
    parentId: "dm-blast",
    prerequisites: ["dm-blast"],
    level: "core",
    summary: "Diminished cells, chromatic planing, and riff as form.",
  },
  {
    id: "dm-history",
    name: "Florida and Stockholm",
    category: "death-metal",
    prerequisites: [],
    level: "intro",
    summary: "Two scenes, two production doctrines, one genre name.",
  },

  {
    id: "hist-method",
    name: "How historians argue",
    category: "history",
    prerequisites: [],
    level: "intro",
    summary: "Sources, causation, and the difference between chronicle and claim.",
  },
  {
    id: "hist-nixon",
    name: "The Nixon shock",
    category: "history",
    parentId: "hist-method",
    prerequisites: ["hist-method"],
    level: "journalist",
    summary: "Ending gold convertibility and the monetary order that followed.",
  },
];

export const CONCEPT_MAP: Record<string, Concept> = Object.fromEntries(
  CONCEPTS.map((c) => [c.id, c]),
);
