import type { Concept } from "@/lib/learning/types";

export const CONCEPTS: Concept[] = [
  {
    id: "arch-latency-throughput",
    name: "Latency versus throughput",
    category: "cpu",
    prerequisites: [],
    level: "intro",
    summary: "How long one thing takes versus how much work finishes per unit time.",
    courseId: "arch-gpu",
    moduleId: "arch-gpu-foundations",
    curriculumOrder: 0,
    tier: 0,
    objectives: [
      "Distinguish latency from throughput with a concrete pipeline or factory example",
      "Explain why raising clock or width can move one without the other",
    ],
  },
  {
    id: "arch-data-parallel",
    name: "Data-parallel work",
    category: "cpu",
    parentId: "arch-latency-throughput",
    prerequisites: ["arch-latency-throughput"],
    level: "intro",
    summary: "The same operation over many independent elements, versus one long dependent chain.",
    courseId: "arch-gpu",
    moduleId: "arch-gpu-foundations",
    curriculumOrder: 1,
    tier: 0,
    objectives: [
      "Recognize when a computation is data-parallel",
      "Contrast that with a sequential dependence that a GPU cannot wish away",
    ],
  },
  {
    id: "cpu-pipeline",
    name: "Instruction pipelines",
    category: "cpu",
    parentId: "arch-latency-throughput",
    prerequisites: ["arch-latency-throughput"],
    level: "intro",
    summary: "Breaking instruction execution into overlapping stages.",
    courseId: "arch-gpu",
    moduleId: "arch-gpu-pipeline",
    curriculumOrder: 0,
    tier: 1,
    objectives: [
      "Explain how overlap raises throughput without shrinking per-instruction latency",
      "Name why a bubble exists",
    ],
  },
  {
    id: "cpu-hazards",
    name: "Pipeline hazards",
    category: "cpu",
    parentId: "cpu-pipeline",
    prerequisites: ["cpu-pipeline"],
    level: "core",
    summary: "Data, control, and structural stalls that break ideal overlap.",
    courseId: "arch-gpu",
    moduleId: "arch-gpu-pipeline",
    curriculumOrder: 1,
    tier: 1,
    objectives: ["Name the three hazard classes", "Say what forwarding can and cannot fix"],
  },
  {
    id: "cpu-branch-prediction",
    name: "Branch prediction",
    category: "cpu",
    parentId: "cpu-pipeline",
    prerequisites: ["cpu-pipeline"],
    level: "core",
    summary: "Guessing control flow so the pipeline stays full.",
    courseId: "arch-gpu",
    moduleId: "arch-gpu-ilp",
    curriculumOrder: 0,
    tier: 2,
    objectives: ["Separate direction prediction from target prediction"],
  },
  {
    id: "cpu-btb",
    name: "Branch target buffers",
    category: "cpu",
    parentId: "cpu-branch-prediction",
    prerequisites: ["cpu-branch-prediction"],
    level: "journalist",
    summary: "Caching where a branch went last time, not just taken/not-taken.",
    courseId: "arch-gpu",
    moduleId: "arch-gpu-ilp",
    curriculumOrder: 2,
    tier: 3,
  },
  {
    id: "cpu-predictors",
    name: "Predictor types",
    category: "cpu",
    parentId: "cpu-branch-prediction",
    prerequisites: ["cpu-branch-prediction"],
    level: "journalist",
    summary: "Local, global, and TAGE-style predictors and why they exist.",
    courseId: "arch-gpu",
    moduleId: "arch-gpu-ilp",
    curriculumOrder: 3,
    tier: 3,
  },
  {
    id: "cpu-ras",
    name: "Return address stacks",
    category: "cpu",
    parentId: "cpu-branch-prediction",
    prerequisites: ["cpu-branch-prediction"],
    level: "journalist",
    summary: "Special-casing CALL/RET so returns do not pollute the BTB.",
    courseId: "arch-gpu",
    moduleId: "arch-gpu-ilp",
    curriculumOrder: 4,
    tier: 3,
  },
  {
    id: "cpu-renaming",
    name: "Register renaming",
    category: "cpu",
    parentId: "cpu-pipeline",
    prerequisites: ["cpu-pipeline"],
    level: "core",
    summary: "Mapping architectural names onto a larger physical file.",
    courseId: "arch-gpu",
    moduleId: "arch-gpu-ilp",
    curriculumOrder: 1,
    tier: 2,
  },
  {
    id: "cpu-rob",
    name: "Reorder buffers",
    category: "cpu",
    parentId: "cpu-renaming",
    prerequisites: ["cpu-renaming"],
    level: "journalist",
    summary: "Retiring out-of-order work in program order.",
    courseId: "arch-gpu",
    moduleId: "arch-gpu-ilp",
    curriculumOrder: 5,
    tier: 3,
  },
  {
    id: "cpu-coherency",
    name: "Cache coherency",
    category: "cpu",
    parentId: "cpu-pipeline",
    prerequisites: ["cpu-pipeline"],
    level: "core",
    summary: "Keeping private caches honest across cores.",
    courseId: "arch-gpu",
    moduleId: "arch-gpu-locality",
    curriculumOrder: 0,
    tier: 2,
  },

  {
    id: "gpu-why-throughput",
    name: "Why a GPU exists",
    category: "cpu",
    parentId: "arch-data-parallel",
    prerequisites: ["arch-data-parallel", "cpu-pipeline"],
    level: "core",
    summary: "Spending transistors on ALUs instead of speculation when the work is wide.",
    courseId: "arch-gpu",
    moduleId: "arch-gpu-simt",
    curriculumOrder: 0,
    tier: 2,
    objectives: [
      "Contrast a latency-optimized core with a throughput-optimized one",
      "Say what kind of program a GPU is for",
    ],
  },
  {
    id: "gpu-execution-model",
    name: "Grid, block, thread",
    category: "cpu",
    parentId: "gpu-why-throughput",
    prerequisites: ["gpu-why-throughput"],
    level: "core",
    summary: "The programmer-visible hierarchy a kernel is launched over.",
    courseId: "arch-gpu",
    moduleId: "arch-gpu-simt",
    curriculumOrder: 1,
    tier: 3,
    objectives: [
      "Map a kernel launch onto threads, blocks, and a grid",
      "Keep the programming model separate from the hardware warp",
    ],
  },
  {
    id: "gpu-simt",
    name: "SIMT versus SIMD",
    category: "cpu",
    parentId: "gpu-execution-model",
    prerequisites: ["gpu-execution-model"],
    level: "core",
    summary: "One instruction stream, many threads, with implicit lockstep and a way to mask lanes.",
    courseId: "arch-gpu",
    moduleId: "arch-gpu-simt",
    curriculumOrder: 2,
    tier: 3,
    objectives: [
      "Distinguish SIMT from packed SIMD",
      "Explain why a scalar-looking kernel still runs in lockstep",
    ],
  },
  {
    id: "gpu-warps",
    name: "Warps and wavefronts",
    category: "cpu",
    parentId: "gpu-simt",
    prerequisites: ["gpu-simt"],
    level: "core",
    summary: "The hardware scheduling quantum — 32 or 64 threads sharing an instruction.",
    courseId: "arch-gpu",
    moduleId: "arch-gpu-simt",
    curriculumOrder: 3,
    tier: 3,
    objectives: [
      "Name the warp/wavefront as the unit the scheduler sees",
      "Explain why block size that is not a multiple of the warp width wastes lanes",
    ],
  },
  {
    id: "gpu-exec-resources",
    name: "Execution resources",
    category: "cpu",
    parentId: "gpu-warps",
    prerequisites: ["gpu-warps"],
    level: "journalist",
    summary: "ALUs, special-function units, and load/store pipes a SM/CU actually has.",
    courseId: "arch-gpu",
    moduleId: "arch-gpu-resources",
    curriculumOrder: 0,
    tier: 4,
  },
  {
    id: "gpu-memory-hierarchy",
    name: "GPU memory hierarchy",
    category: "cpu",
    parentId: "gpu-warps",
    prerequisites: ["gpu-warps"],
    level: "journalist",
    summary: "Registers, shared/LDS, L1/L2, and HBM — different spaces, different costs.",
    courseId: "arch-gpu",
    moduleId: "arch-gpu-resources",
    curriculumOrder: 1,
    tier: 4,
  },
  {
    id: "gpu-coalescing",
    name: "Memory coalescing",
    category: "cpu",
    parentId: "gpu-memory-hierarchy",
    prerequisites: ["gpu-memory-hierarchy"],
    level: "journalist",
    summary: "Adjacent threads touching adjacent addresses become one transaction.",
    courseId: "arch-gpu",
    moduleId: "arch-gpu-resources",
    curriculumOrder: 2,
    tier: 4,
  },
  {
    id: "gpu-occupancy",
    name: "Occupancy",
    category: "cpu",
    parentId: "gpu-exec-resources",
    prerequisites: ["gpu-exec-resources", "gpu-memory-hierarchy"],
    level: "journalist",
    summary: "How many warps can live on a processor at once, limited by registers and shared memory.",
    courseId: "arch-gpu",
    moduleId: "arch-gpu-resources",
    curriculumOrder: 3,
    tier: 4,
  },
  {
    id: "gpu-divergence",
    name: "Control divergence",
    category: "cpu",
    parentId: "gpu-warps",
    prerequisites: ["gpu-warps", "gpu-occupancy"],
    level: "journalist",
    summary: "Threads in a warp taking different paths, so both sides run under a mask.",
    courseId: "arch-gpu",
    moduleId: "arch-gpu-schedule",
    curriculumOrder: 0,
    tier: 4,
  },
  {
    id: "gpu-latency-hiding",
    name: "Latency hiding",
    category: "cpu",
    parentId: "gpu-occupancy",
    prerequisites: ["gpu-occupancy"],
    level: "journalist",
    summary: "Switching to another ready warp instead of stalling the whole machine on a miss.",
    courseId: "arch-gpu",
    moduleId: "arch-gpu-schedule",
    curriculumOrder: 1,
    tier: 4,
  },
  {
    id: "gpu-scheduler",
    name: "Warp scheduling",
    category: "cpu",
    parentId: "gpu-latency-hiding",
    prerequisites: ["gpu-latency-hiding", "gpu-divergence"],
    level: "journalist",
    summary: "Which ready warp runs next, and why that interacts with caches and issue width.",
    courseId: "arch-gpu",
    moduleId: "arch-gpu-schedule",
    curriculumOrder: 2,
    tier: 5,
  },
  {
    id: "gpu-resource-limits",
    name: "Resource-limited launch",
    category: "cpu",
    parentId: "gpu-occupancy",
    prerequisites: ["gpu-occupancy", "gpu-scheduler"],
    level: "journalist",
    summary: "Registers, shared memory, and warp slots as coupled constraints on a kernel.",
    courseId: "arch-gpu",
    moduleId: "arch-gpu-schedule",
    curriculumOrder: 3,
    tier: 5,
  },


  {
    id: "semi-litho",
    name: "Photolithography",
    category: "semiconductors",
    prerequisites: [],
    level: "intro",
    summary: "Projecting patterns into resist to define features.",
  },
  {
    id: "semi-euv",
    name: "EUV lithography",
    category: "semiconductors",
    parentId: "semi-litho",
    prerequisites: ["semi-litho"],
    level: "core",
    summary: "13.5 nm light, mirrors, and why refractive optics die.",
  },
  {
    id: "semi-na",
    name: "Numerical aperture",
    category: "semiconductors",
    parentId: "semi-euv",
    prerequisites: ["semi-euv"],
    level: "journalist",
    summary: "How High-NA EUV buys resolution and spends depth of focus.",
  },
  {
    id: "semi-overlay",
    name: "Overlay",
    category: "semiconductors",
    parentId: "semi-euv",
    prerequisites: ["semi-euv"],
    level: "journalist",
    summary: "Layer-to-layer alignment as a yield budget, not a slogan.",
  },
  {
    id: "semi-stochastics",
    name: "Stochastic defects",
    category: "semiconductors",
    parentId: "semi-euv",
    prerequisites: ["semi-euv"],
    level: "journalist",
    summary: "Photon and photoacid shot noise at EUV doses.",
  },

  {
    id: "os-process",
    name: "Processes and threads",
    category: "os",
    prerequisites: [],
    level: "intro",
    summary: "Address spaces, threads, and what isolation actually costs.",
  },
  {
    id: "os-vm",
    name: "Virtual memory",
    category: "os",
    parentId: "os-process",
    prerequisites: ["os-process"],
    level: "core",
    summary: "Pages, page tables, and the TLB as a cache of translations.",
  },
  {
    id: "os-sched",
    name: "CPU scheduling",
    category: "os",
    parentId: "os-process",
    prerequisites: ["os-process"],
    level: "core",
    summary: "Fairness, latency, and why CFS is not a real-time scheduler.",
  },

  {
    id: "net-stack",
    name: "The network stack",
    category: "networking",
    prerequisites: [],
    level: "intro",
    summary: "Layers as contracts, not a morality play.",
  },
  {
    id: "net-congestion",
    name: "Congestion control",
    category: "networking",
    parentId: "net-stack",
    prerequisites: ["net-stack"],
    level: "core",
    summary: "How senders share a pipe they cannot see.",
  },
  {
    id: "net-bgp",
    name: "BGP",
    category: "networking",
    parentId: "net-stack",
    prerequisites: ["net-stack"],
    level: "journalist",
    summary: "Policy routing between autonomous systems.",
  },

  {
    id: "cmp-front",
    name: "Lexing and parsing",
    category: "compilers",
    prerequisites: [],
    level: "intro",
    summary: "Turning characters into a tree the rest of the compiler can hate.",
  },
  {
    id: "cmp-ssa",
    name: "SSA form",
    category: "compilers",
    parentId: "cmp-front",
    prerequisites: ["cmp-front"],
    level: "core",
    summary: "Single assignment so dataflow becomes a graph problem.",
  },
  {
    id: "cmp-alloc",
    name: "Register allocation",
    category: "compilers",
    parentId: "cmp-ssa",
    prerequisites: ["cmp-ssa"],
    level: "journalist",
    summary: "Graph coloring, spilling, and the real cost of an extra live range.",
  },

  {
    id: "ml-gd",
    name: "Gradient descent",
    category: "ml",
    prerequisites: [],
    level: "intro",
    summary: "Following the slope of a loss you can actually compute.",
  },
  {
    id: "ml-backprop",
    name: "Backpropagation",
    category: "ml",
    parentId: "ml-gd",
    prerequisites: ["ml-gd"],
    level: "core",
    summary: "Reverse-mode autodiff, not a separate algorithm from calculus.",
  },
  {
    id: "ml-attention",
    name: "Attention",
    category: "ml",
    parentId: "ml-backprop",
    prerequisites: ["ml-backprop"],
    level: "journalist",
    summary: "QKV as a content-addressable lookup, and why it scales.",
  },

  {
    id: "ast-hr",
    name: "The Hertzsprung–Russell diagram",
    category: "astronomy",
    prerequisites: [],
    level: "intro",
    summary: "Luminosity versus temperature as a map of stellar lives.",
  },
  {
    id: "ast-exo",
    name: "Exoplanet detection",
    category: "astronomy",
    parentId: "ast-hr",
    prerequisites: ["ast-hr"],
    level: "core",
    summary: "Transits, radial velocity, and what each method cannot see.",
  },

  {
    id: "bio-selection",
    name: "Natural selection",
    category: "evo-bio",
    prerequisites: [],
    level: "intro",
    summary: "Differential reproductive success, not progress.",
  },
  {
    id: "bio-evodevo",
    name: "Evo-devo",
    category: "evo-bio",
    parentId: "bio-selection",
    prerequisites: ["bio-selection"],
    level: "core",
    summary: "How developmental toolkits make large morphological jumps cheap.",
  },

  {
    id: "econ-ca",
    name: "Comparative advantage",
    category: "economics",
    prerequisites: [],
    level: "intro",
    summary: "Opportunity cost, not absolute productivity.",
  },
  {
    id: "econ-money",
    name: "Monetary policy",
    category: "economics",
    parentId: "econ-ca",
    prerequisites: ["econ-ca"],
    level: "core",
    summary: "Rates, reserves, and the transmission the press compresses.",
  },

  {
    id: "stat-bias",
    name: "Sampling bias",
    category: "statistics",
    prerequisites: [],
    level: "intro",
    summary: "Who is in the data is the result.",
  },
  {
    id: "stat-pvalue",
    name: "P-values",
    category: "statistics",
    parentId: "stat-bias",
    prerequisites: ["stat-bias"],
    level: "core",
    summary: "A tail probability under a model, not the chance you are right.",
  },
  {
    id: "stat-bayes",
    name: "Bayes in practice",
    category: "statistics",
    parentId: "stat-pvalue",
    prerequisites: ["stat-pvalue"],
    level: "journalist",
    summary: "Priors, likelihoods, and why base rates refuse to die.",
  },

  {
    id: "horo-escape",
    name: "The escapement",
    category: "horology",
    prerequisites: [],
    level: "intro",
    summary: "Turning a spring’s unwind into counted ticks.",
  },
  {
    id: "horo-tourbillon",
    name: "The tourbillon",
    category: "horology",
    parentId: "horo-escape",
    prerequisites: ["horo-escape"],
    level: "core",
    summary: "Averaging positional error, and when it is theater.",
  },

  {
    id: "aud-freq",
    name: "Frequency response",
    category: "audio",
    prerequisites: [],
    level: "intro",
    summary: "What a system does to amplitude versus frequency.",
  },
  {
    id: "aud-comp",
    name: "Compression",
    category: "audio",
    parentId: "aud-freq",
    prerequisites: ["aud-freq"],
    level: "core",
    summary: "Threshold, ratio, attack, release — gain reduction as time.",
  },

  {
    id: "mus-interval",
    name: "Intervals and consonance",
    category: "music-theory",
    prerequisites: [],
    level: "intro",
    summary: "Ratios, beating, and why a fifth sits still.",
  },
  {
    id: "mus-modes",
    name: "Modes",
    category: "music-theory",
    parentId: "mus-interval",
    prerequisites: ["mus-interval"],
    level: "core",
    summary: "Same pitch set, different tonic gravity.",
  },

  {
    id: "dm-blast",
    name: "Blast beats",
    category: "death-metal",
    prerequisites: [],
    level: "intro",
    summary: "The drum grammar that made death metal possible.",
  },
  {
    id: "dm-harmony",
    name: "Death-metal harmony",
    category: "death-metal",
    parentId: "dm-blast",
    prerequisites: ["dm-blast"],
    level: "core",
    summary: "Diminished cells, chromatic planing, and riff as form.",
  },
  {
    id: "dm-history",
    name: "Florida and Stockholm",
    category: "death-metal",
    prerequisites: [],
    level: "intro",
    summary: "Two scenes, two production doctrines, one genre name.",
  },

  {
    id: "hist-method",
    name: "How historians argue",
    category: "history",
    prerequisites: [],
    level: "intro",
    summary: "Sources, causation, and the difference between chronicle and claim.",
  },
  {
    id: "hist-nixon",
    name: "The Nixon shock",
    category: "history",
    parentId: "hist-method",
    prerequisites: ["hist-method"],
    level: "journalist",
    summary: "Ending gold convertibility and the monetary order that followed.",
  },
];

export const CONCEPT_MAP: Record<string, Concept> = Object.fromEntries(
  CONCEPTS.map((c) => [c.id, c]),
);
