import type { Lesson } from "@/lib/learning/types";
import { L, d, item } from "../lesson";

export const GPU_LESSONS: Lesson[] = [
  L({
    id: "arch-latency-throughput-5",
    conceptId: "arch-latency-throughput",
    title: "How long versus how many",
    durationMin: 5,
    effort: "light",
    level: "intro",
    prerequisites: [],
    goDeeper: "cpu-pipeline",
    explanation: [
      "Latency is how long one unit of work takes from start to finish. Throughput is how many units finish per unit time. They are related and they are not the same number. A bakery can take 40 minutes to bake one loaf and still sell 200 loaves an hour if 200 loaves share the oven.",
      "Hardware people mix the words because marketing likes a single speed. Clock frequency is a latency story about one stage. IPC and occupancy are throughput stories about how often useful work retires. You can raise the clock and lose throughput if every other cycle is a stall. You can lower the clock and gain throughput if you keep more work in flight.",
      "The rest of this course is techniques for buying one without pretending you bought the other. Pipelines attack throughput. Caches attack latency that would otherwise serialize the line. GPUs mostly refuse the latency game and bet that there is always another independent thread.",
    ],
    example:
      "A load from DRAM might take 300 cycles (latency). A core that only issues that load retires almost nothing. A GPU that has 20 other warps ready can keep ALUs busy for those 300 cycles (throughput). The load is still slow. The machine is not idle.",
    whyItMatters:
      "Every confused chip announcement — 'faster clocks', 'more CUDA cores', 'higher occupancy' — is a latency/throughput mix-up. If you cannot say which quantity moved, you cannot read the claim.",
    quiz: [
      item({
        id: "lt1",
        stem: "A change that shrinks how long one instruction takes, without changing how many finish per cycle, primarily moved:",
        correct: "Latency",
        distractors: [
          d("Throughput", "nearby", "Throughput is completion rate, not per-item time."),
          d("Instruction count", "misapplied", "How many instructions exist is not how long one takes."),
          d("Byte order", "subtle", "Endianness is a naming convention, not a speed."),
        ],
        explanation: "Latency is per-item time. Throughput is completion rate.",
        cognitiveType: "recognize",
        objectiveIds: ["Distinguish latency from throughput with a concrete pipeline or factory example"],
        difficultyTier: 0,
      }),
      item({
        id: "lt2",
        stem: "A factory with a 40-minute bake and 200 loaves in the oven at once is mainly an example of:",
        correct: "High throughput despite high latency",
        distractors: [
          d("Eliminating latency", "reversed", "Each loaf still takes 40 minutes."),
          d("That clock frequency is the only knob", "misapplied", "Overlap, not frequency, is doing the work here."),
          d("That the oven has no capacity limit", "nearby", "The oven size is exactly the capacity that creates throughput."),
        ],
        explanation: "Each loaf still takes 40 minutes; many finish each hour.",
        cognitiveType: "apply",
        objectiveIds: ["Distinguish latency from throughput with a concrete pipeline or factory example"],
        difficultyTier: 0,
      }),
      item({
        id: "lt3",
        stem: "Switching to another ready thread while a load is in flight is trying to protect:",
        correct: "Throughput while latency is paid",
        distractors: [
          d("The load’s latency", "reversed", "The miss is still slow; switching does not shorten it."),
          d("DRAM capacity", "nearby", "Capacity is not the quantity being hidden."),
          d("ISA compatibility", "subtle", "The ISA does not change because a warp is swapped."),
        ],
        explanation: "The miss is still slow. The machine keeps retiring other work.",
        cognitiveType: "identify",
        objectiveIds: ["Explain why raising clock or width can move one without the other"],
        difficultyTier: 0,
      }),
    ],
  }),
  L({
    id: "arch-data-parallel-5",
    conceptId: "arch-data-parallel",
    title: "The same math, many elements",
    durationMin: 5,
    effort: "light",
    level: "intro",
    prerequisites: ["arch-latency-throughput"],
    goDeeper: "gpu-why-throughput",
    explanation: [
      "Some programs are a long chain: each step needs the previous result. Some programs are a map: add one to every pixel, multiply every row of a matrix. The second kind is data-parallel. The operations are the same; the elements are independent.",
      "Independence is the property hardware can spend. If element 7 does not wait on element 3, you can run them in the same cycle on different ALUs, or stagger them so a cache miss on 3 does not stall 7. A loop-carried dependence (`x = f(x)`) is the opposite. No amount of GPU marketing deletes that edge.",
      "People say 'embarrassingly parallel' when the independence is obvious. Most real programs are mixed: a data-parallel map around a sequential reduction, or a grid of threads that must meet at a barrier. The skill is seeing which parts are maps.",
    ],
    example:
      "Colouring each pixel `out[i] = 2 * in[i]` is data-parallel. Computing a prefix sum where `out[i] = out[i-1] + in[i]` is not — unless you rewrite it with a tree of partials. The rewrite is the algorithm. The hardware only runs what you made independent.",
    whyItMatters:
      "GPUs are not faster CPUs. They are machines for data-parallel work. If you cannot point at the independent elements, you are about to be disappointed by a kernel.",
    quiz: [
      item({
        id: "dp1",
        stem: "A computation is data-parallel when:",
        correct: "The same operation applies to independent elements",
        distractors: [
          d("It uses a GPU", "misapplied", "The vendor logo is not the property."),
          d("It has a for-loop", "nearby", "Loops can be sequential chains."),
          d("It touches DRAM", "subtle", "Memory traffic is unrelated to independence."),
        ],
        explanation: "The hardware property is independence, not the vendor logo.",
        cognitiveType: "recognize",
        objectiveIds: ["Recognize when a computation is data-parallel"],
        difficultyTier: 0,
      }),
      item({
        id: "dp2",
        stem: "`x = f(x)` each iteration is hard to parallelize because:",
        correct: "Each step depends on the previous result",
        distractors: [
          d("Functions are slow", "misconception", "The cost is the dependence, not call overhead."),
          d("f cannot run on a SIMD unit", "misapplied", "f can run; it just cannot run independently."),
          d("The ISA forbids it", "subtle", "ISAs happily express sequential updates."),
        ],
        explanation: "A loop-carried dependence is a chain, not a map.",
        cognitiveType: "apply",
        objectiveIds: ["Contrast that with a sequential dependence a GPU cannot wish away"],
        prerequisiteConceptIds: ["arch-latency-throughput"],
        difficultyTier: 0,
      }),
      item({
        id: "dp3",
        stem: "Rewriting a reduction as a tree of partials is an example of:",
        correct: "Creating independence the original loop did not have",
        distractors: [
          d("Raising DRAM latency", "reversed", "The rewrite is about dependence, not making memory slower."),
          d("Changing the byte order", "nearby", "Endianness does not manufacture parallelism."),
          d("Deleting the need for a clock", "subtle", "The algorithm still runs on a timed machine."),
        ],
        explanation: "The algorithm manufactures parallelism. Hardware cannot invent it.",
        cognitiveType: "identify",
        objectiveIds: ["Contrast that with a sequential dependence a GPU cannot wish away"],
        difficultyTier: 0,
      }),
    ],
  }),
  L({
    id: "gpu-why-throughput-10",
    conceptId: "gpu-why-throughput",
    title: "Spend silicon on ALUs, not crystal balls",
    durationMin: 10,
    effort: "normal",
    level: "core",
    prerequisites: ["arch-data-parallel", "cpu-pipeline"],
    goDeeper: "gpu-execution-model",
    explanation: [
      "A modern CPU core spends a startling fraction of its transistors on making *one* thread look fast: predictors, reorder buffers, huge caches, fancy prefetchers. That is the right bet when the next instruction depends on this one and the user is waiting on a single program counter.",
      "A GPU makes the opposite bet. If you have thousands of independent elements, you can run them on many simple pipelines and hide memory latency by switching to another group of threads. You spend area on ALUs and memory bandwidth, not on guessing the next branch of one lonely thread.",
      "The cost is real. GPUs are weak at divergent, pointer-chasing, or lightly parallel work. They also want you to express the map (a kernel over an index space) instead of a sequential loop the hardware must discover. The win appears only when the work matches the bet.",
    ],
    example:
      "Shading a million pixels, multiplying large matrices, or running the same force calculation on many particles: the GPU’s extra ALUs stay busy. Walking a linked list of Java objects: the CPU’s caches and predictors win, and the GPU sits on a long chain of misses.",
    whyItMatters:
      "Stories that a new laptop 'has more cores so everything is faster' collapse once you know which program is a map and which is a chain. The rest of this module is how the map is actually executed.",
    quiz: [
      item({
        id: "gw1",
        stem: "A latency-optimized core spends relatively more area on:",
        correct: "Prediction, reordering, and caches for one thread",
        distractors: [
          d("Identical ALUs", "nearby", "Many ALUs is the throughput bet, not the single-thread bet."),
          d("HBM stacks", "misapplied", "Memory stacks are a package choice, not the core’s crystal ball."),
          d("Wavefront occupancy", "subtle", "Occupancy is a later GPU resource word."),
        ],
        explanation: "The CPU bet is 'make this PC fast'.",
        cognitiveType: "recognize",
        objectiveIds: ["Explain the area bet of a sequential core versus a throughput machine"],
        prerequisiteConceptIds: ["arch-data-parallel", "cpu-pipeline"],
        difficultyTier: 2,
      }),
      item({
        id: "gw2",
        stem: "A throughput GPU is a good match when:",
        correct: "Many elements can be processed independently",
        distractors: [
          d("The next instruction always depends on the last", "reversed", "That is the sequential-core case."),
          d("The working set is one cache line", "nearby", "Tiny working sets favour caches, not thousands of ALUs."),
          d("You need precise exceptions on every instruction", "subtle", "Precise exceptions are a CPU-core luxury."),
        ],
        explanation: "Independence is what extra ALUs can spend.",
        cognitiveType: "apply",
        objectiveIds: ["Match a workload to the throughput bet"],
        prerequisiteConceptIds: ["arch-data-parallel"],
        difficultyTier: 2,
      }),
      item({
        id: "gw3",
        stem: "Switching to another group of threads during a miss is buying:",
        correct: "Throughput while a long latency is in flight",
        distractors: [
          d("Shorter DRAM latency", "reversed", "The miss is still slow."),
          d("A larger ISA", "nearby", "The instruction set does not grow because a warp swapped."),
          d("Coherence", "subtle", "Coherence is about agreeing copies, not hiding a miss."),
        ],
        explanation: "The miss is still slow. Other maps keep the ALUs fed.",
        cognitiveType: "predict",
        objectiveIds: ["Predict what latency hiding actually protects"],
        prerequisiteConceptIds: ["arch-latency-throughput"],
        difficultyTier: 2,
      }),
    ],
  }),
  L({
    id: "gpu-execution-model-10",
    conceptId: "gpu-execution-model",
    title: "A kernel is a launch over an index space",
    durationMin: 10,
    effort: "normal",
    level: "core",
    prerequisites: ["gpu-why-throughput"],
    goDeeper: "gpu-simt",
    explanation: [
      "You do not hand a GPU a sequential program and hope. You write a *kernel*: a function that runs once per thread, and you *launch* it over a grid of thread blocks. Each thread knows its index (`threadIdx`, `blockIdx`) and uses that index to pick the element it owns.",
      "The hierarchy is a programming model, not yet the hardware. Threads are the finest name you write. Blocks are the unit that can share a small on-chip memory and a barrier. The grid is the whole launch. How those names map onto warps and SMs is the next concept — keep them separate for one more unit.",
      "This is why a CUDA or Metal kernel looks like a scalar function and still uses the machine. The launch geometry *is* the parallel loop. If you launch too few threads, you underfill the chip. If you launch a geometry that fights the later warp size, you waste lanes. The model came first so you could reason before counting 32s.",
    ],
    example:
      "`vectorAdd<<<blocks, threads>>>(A, B, C, N)` with each thread doing `C[i] = A[i] + B[i]` for `i = blockIdx.x * blockDim.x + threadIdx.x`. The C code is scalar. The launch is the map. A 256-thread block on a 1,000,000-element vector is a choice about occupancy and leftover threads, not about the addition itself.",
    whyItMatters:
      "Every later word — warp, occupancy, coalescing — is an implementation detail of this launch. If you skip the model, those words become vendor folklore.",
    quiz: [
      item({
        id: "ge1",
        stem: "In the CUDA-style model, the function you write that runs per thread is a:",
        correct: "Kernel",
        distractors: [
          d("Wavefront", "nearby", "A wavefront is a later hardware grouping."),
          d("Reorder buffer", "misapplied", "ROBs belong to out-of-order CPU cores."),
          d("Page table", "subtle", "Address translation is a different contract."),
        ],
        explanation: "A kernel is the per-thread body; the launch supplies the index space.",
        cognitiveType: "recognize",
        objectiveIds: ["Name the kernel as the per-thread body of a launch"],
        difficultyTier: 2,
      }),
      item({
        id: "ge2",
        stem: "A thread block is the level that can:",
        correct: "Share a small on-chip memory and a barrier",
        distractors: [
          d("Address all of DRAM privately", "misconception", "DRAM is a device resource, not block-private."),
          d("Retire x86 instructions", "misapplied", "Blocks are not CPU cores."),
          d("Replace the grid", "reversed", "The grid contains blocks; a block is not the launch."),
        ],
        explanation: "Shared memory and __syncthreads are block-scoped.",
        cognitiveType: "apply",
        objectiveIds: ["Separate thread, block, and grid responsibilities"],
        difficultyTier: 2,
      }),
      item({
        id: "ge3",
        stem: "threadIdx / blockIdx exist so that:",
        correct: "Each thread can compute which element it owns",
        distractors: [
          d("The compiler can rename registers", "nearby", "Renaming is a CPU-core name trick."),
          d("Warps can be 64 wide", "misapplied", "Warp width is hardware, not why indices exist."),
          d("Caches stay coherent", "subtle", "Indices do not implement MESI."),
        ],
        explanation: "The index is the parallel loop variable.",
        cognitiveType: "predict",
        objectiveIds: ["Use launch indices as the parallel loop variable"],
        prerequisiteConceptIds: ["gpu-why-throughput"],
        difficultyTier: 2,
      }),
    ],
  }),
  L({
    id: "gpu-simt-10",
    conceptId: "gpu-simt",
    title: "Scalar code, lockstep hardware",
    durationMin: 10,
    effort: "normal",
    level: "core",
    prerequisites: ["gpu-execution-model"],
    goDeeper: "gpu-warps",
    explanation: [
      "SIMD packs several values into one register and runs one instruction on the pack. You write vectors. SIMT (single instruction, multiple threads) lets you write *scalar* thread code. The hardware still runs one instruction across a group of threads, and it *masks* the lanes that should not participate.",
      "That is why a kernel can contain `if (threadIdx.x == 0)` and still be a vector machine. The other lanes go idle under a mask; they do not take a different instruction. When the branch ends, the group reconverges. The programming model hid the pack. The energy and occupancy cost of idle lanes did not go away.",
      "People collapse SIMT into 'it's just SIMD'. The distinction matters for compilers and for divergence. SIMD that you wrote as `_mm256_add_ps` cannot silently take two control-flow paths. SIMT can look like it did — and then you pay both paths. Next unit names the group that shares the instruction: the warp or wavefront.",
    ],
    example:
      "32 threads execute `if (x[i] > 0) y[i] = sqrt(x[i]); else y[i] = 0`. If 20 lanes are positive, the hardware issues the sqrt path with 20 lanes active, then the else path with 12 active. You wrote scalar if/else. You paid a SIMD-shaped bill.",
    whyItMatters:
      "SIMT is why GPU kernels read like C and profile like vector machines. Divergence, occupancy, and 'why is my if so slow?' are all this fact wearing different hats.",
    quiz: [
      item({
        id: "gs1",
        stem: "SIMT differs from explicit SIMD mainly because:",
        correct: "You write scalar thread code; the hardware groups and masks lanes",
        distractors: [
          d("It uses slower ALUs", "misconception", "The ALUs are not the distinction."),
          d("It cannot do floating point", "nearby", "SIMT machines do plenty of FP."),
          d("It has no registers", "subtle", "Threads still have register files."),
        ],
        explanation: "The pack is implicit. The cost of idle lanes is not.",
        cognitiveType: "recognize",
        objectiveIds: ["Distinguish SIMT from explicit SIMD"],
        difficultyTier: 2,
      }),
      item({
        id: "gs2",
        stem: "When some threads in a SIMT group take an if and others take the else:",
        correct: "Both paths run, with inactive lanes masked",
        distractors: [
          d("The GPU forks into two independent programs", "reversed", "There is still one instruction stream."),
          d("The compiler rejects the kernel", "nearby", "Divergent kernels compile; they just run both sides."),
          d("Only the first thread’s path runs", "misapplied", "Lane 0 is not a dictator."),
        ],
        explanation: "One instruction stream, two passes, a mask.",
        cognitiveType: "apply",
        objectiveIds: ["Trace what a divergent if/else actually does"],
        difficultyTier: 2,
      }),
      item({
        id: "gs3",
        stem: "A kernel that looks scalar can still waste work because:",
        correct: "Inactive lanes in the group still occupy the instruction issue",
        distractors: [
          d("C cannot run on a GPU", "misconception", "Scalar-looking C is the programming model."),
          d("DRAM ignores masks", "nearby", "The tax is issue/occupancy, not DRAM refusing masks."),
          d("Blocks cannot share memory", "subtle", "Shared memory is unrelated to idle lanes."),
        ],
        explanation: "Idle lanes are why divergence is a throughput tax.",
        cognitiveType: "predict",
        objectiveIds: ["Predict the cost of idle lanes"],
        prerequisiteConceptIds: ["gpu-execution-model"],
        difficultyTier: 2,
      }),
    ],
  }),
  L({
    id: "gpu-warps-10",
    conceptId: "gpu-warps",
    title: "The scheduler does not see your threads",
    durationMin: 10,
    effort: "normal",
    level: "core",
    prerequisites: ["gpu-simt"],
    goDeeper: "gpu-occupancy",
    explanation: [
      "Hardware groups consecutive threads into a warp (NVIDIA, typically 32) or wavefront (AMD, historically 64, now often 32). That group shares a program counter and is the unit the scheduler considers ready or stalled. You launched threads. The chip runs warps.",
      "A block whose size is not a multiple of the warp width pads out a partial warp. Those extra lanes do nothing useful and still occupy resources. A block of 1 thread and a block of 32 threads that do the same math are not the same machine: the first still occupies a warp.",
      "This is also why 'how many threads can I launch?' is the wrong first question. The occupancy question is how many *warps* can live on an SM given registers and shared memory. Divergence is a warp-local story: threads in different warps taking different branches do not mask each other.",
    ],
    example:
      "A block of 40 threads on a 32-wide warp is two warps: 32 full, 8 useful + 24 idle. A 256-thread block is exactly 8 warps. The 256 number looks nicer in a slide; the 8 is what the issue logic counts.",
    whyItMatters:
      "Occupancy, divergence, and coalescing are all warp-shaped. If you keep thinking in individual threads, those words will stay metaphorical.",
    quiz: [
      item({
        id: "ww1",
        stem: "A warp (or wavefront) is primarily:",
        correct: "The hardware group that shares an instruction and is scheduled as one",
        distractors: [
          d("A programmer-declared block", "nearby", "Blocks are the programming-model grouping."),
          d("A DRAM page", "misapplied", "Pages are an OS/memory idea."),
          d("A CUDA stream", "subtle", "Streams order launches, they do not share a PC."),
        ],
        explanation: "The scheduler’s quantum, not the kernel’s syntax.",
        cognitiveType: "recognize",
        objectiveIds: ["Name the warp as the scheduler’s quantum"],
        difficultyTier: 3,
      }),
      item({
        id: "ww2",
        stem: "A 40-thread block on a 32-wide warp wastes lanes because:",
        correct: "The second warp is only 8 threads and still occupies 32 lanes",
        distractors: [
          d("40 is prime", "misconception", "Primality is irrelevant."),
          d("Blocks cannot exceed 32", "reversed", "Blocks can be much larger than a warp."),
          d("The compiler rounds down to 32 and drops work", "nearby", "The extra 8 threads still run; they just pad a warp."),
        ],
        explanation: "Partial warps still take a full issue slot.",
        cognitiveType: "apply",
        objectiveIds: ["Compute the cost of a partial warp"],
        prerequisiteConceptIds: ["gpu-simt"],
        difficultyTier: 3,
      }),
      item({
        id: "ww3",
        stem: "Two threads in different warps taking opposite branches:",
        correct: "Do not diverge against each other; divergence is intra-warp",
        distractors: [
          d("Must mask each other", "reversed", "Different warps have different program counters."),
          d("Force a grid-wide barrier", "misapplied", "A branch is not a grid barrier."),
          d("Disable coalescing permanently", "subtle", "Coalescing is an address-pattern story."),
        ],
        explanation: "Divergence is a property of one shared program counter.",
        cognitiveType: "integrate",
        objectiveIds: ["Separate intra-warp divergence from inter-warp independence"],
        prerequisiteConceptIds: ["gpu-simt"],
        difficultyTier: 3,
      }),
    ],
  }),
];
