/**
 * Remaining subject areas: ML, horology, music theory, death metal.
 * Authoring only — runtime loads the generated JSON.
 */
export function remainingCourses(concept) {
  return [
    {
      id: "ml-foundations",
      title: "Machine Learning Foundations",
      categoryId: "ml",
      description:
        "The learning problem, linear models, generalization, and gradient descent. Neural nets wait. Transformers wait longer.",
      curriculumVersion: 1,
      orderHint: 0,
      difficultyRange: [0, 2],
      entryRequirements: [],
      sourceReferences: [
        {
          id: "stanford-cs229",
          title: "Stanford CS229 Machine Learning",
          url: "https://cs229.stanford.edu/syllabus-new.html",
          kind: "syllabus",
          notes:
            "Supervised setup and linear/logistic models before neural nets. No transformers in the core sequence. Linear algebra and probability are assumed tools, not LLM trivia.",
        },
      ],
      modules: [
        {
          id: "ml-f-problem",
          title: "The learning problem",
          blurb: "Examples, features, and a loss you can actually compute.",
          order: 0,
          prerequisites: [],
          spineIds: ["ml-learning-problem", "ml-loss"],
          learningObjectives: ["State a supervised learning problem", "Name what a loss is for"],
          sourceIds: ["stanford-cs229"],
        },
        {
          id: "ml-f-linear",
          title: "Linear models",
          blurb: "Regression, classification, and a slope.",
          order: 1,
          prerequisites: ["ml-f-problem"],
          spineIds: ["ml-linear-reg", "ml-gd"],
        },
        {
          id: "ml-f-gen",
          title: "Generalization",
          blurb: "Train, validation, test, and the ways you fool yourself.",
          order: 2,
          prerequisites: ["ml-f-linear"],
          spineIds: ["ml-overfit", "ml-train-val-test"],
        },
        {
          id: "ml-f-opt",
          title: "Optimization in practice",
          blurb: "Stochastic gradients and the assumptions underneath.",
          order: 3,
          prerequisites: ["ml-f-gen"],
          spineIds: ["ml-gd-variants", "ml-iid"],
        },
      ],
      concepts: [
        concept("ml-learning-problem", "The learning problem", "ml-f-problem", 0, [], "Inferring a rule from examples that should work on examples you have not seen."),
        concept("ml-features-targets", "Features and targets", "ml-f-problem", 0, ["ml-learning-problem"], "The inputs you chose and the thing you are trying to predict."),
        concept("ml-hypothesis", "Hypothesis class", "ml-f-problem", 1, ["ml-features-targets"], "The family of functions you are willing to consider."),
        concept("ml-loss", "Loss functions", "ml-f-problem", 1, ["ml-hypothesis"], "A number that says how wrong a prediction is."),
        concept("ml-lin-alg-lite", "Vectors as the language of models", "ml-f-problem", 1, ["ml-features-targets"], "Features live in a space. Geometry is not decoration."),
        concept("ml-prob-lite", "Probability as bookkeeping", "ml-f-problem", 1, ["ml-learning-problem"], "Uncertainty written as numbers you can multiply."),
        concept("ml-baselines", "Baselines before cleverness", "ml-f-problem", 1, ["ml-loss"], "The dumb answer you must beat."),
        concept("ml-linear-reg", "Linear regression", "ml-f-linear", 1, ["ml-loss", "ml-lin-alg-lite"], "A weighted sum plus a bias, fit by reducing squared error."),
        concept("ml-logistic", "Logistic regression", "ml-f-linear", 2, ["ml-linear-reg"], "A linear score turned into a probability."),
        concept("ml-prob-model", "Predictions as probabilities", "ml-f-linear", 2, ["ml-logistic", "ml-prob-lite"], "A number between 0 and 1 is not a promise."),
        concept("ml-gd", "Gradient descent", "ml-f-linear", 1, ["ml-loss"], "Following the slope of a loss you can actually compute."),
        concept("ml-feature-scale", "Feature scaling", "ml-f-linear", 1, ["ml-gd"], "Why unscaled inputs make the slope lie."),
        concept("ml-convex", "Convex versus non-convex loss", "ml-f-linear", 2, ["ml-gd"], "One bowl, or a landscape with many basins."),
        concept("ml-metrics-class", "Classification metrics", "ml-f-linear", 2, ["ml-logistic"], "Precision, recall, and why accuracy lies."),
        concept("ml-train-val-test", "Train, validation, test", "ml-f-gen", 1, ["ml-learning-problem"], "Three splits, three jobs. Mixing them is the original sin."),
        concept("ml-overfit", "Overfitting", "ml-f-gen", 2, ["ml-train-val-test", "ml-hypothesis"], "Fitting the sample, missing the population."),
        concept("ml-generalization", "Generalization", "ml-f-gen", 2, ["ml-overfit"], "Performance on the distribution, not the spreadsheet."),
        concept("ml-bias-variance", "Bias and variance", "ml-f-gen", 2, ["ml-generalization"], "A model that cannot see versus a model that sees noise."),
        concept("ml-regularization", "Regularization", "ml-f-gen", 2, ["ml-overfit"], "Paying a tax on complexity so the fit cannot wander."),
        concept("ml-crossval", "Cross-validation", "ml-f-gen", 2, ["ml-train-val-test"], "Rotating the held-out slice when data is scarce."),
        concept("ml-capacity", "Model capacity", "ml-f-gen", 2, ["ml-bias-variance"], "How much structure the hypothesis class can represent."),
        concept("ml-early-stop", "Early stopping", "ml-f-gen", 2, ["ml-overfit", "ml-gd"], "Quitting while the validation loss is still honest."),
        concept("ml-gd-variants", "Stochastic and mini-batch gradients", "ml-f-opt", 2, ["ml-gd"], "Estimating the slope from a handful of examples."),
        concept("ml-iid", "The i.i.d. assumption", "ml-f-opt", 2, ["ml-generalization"], "Independent, identically distributed — and how often that is a lie."),
      ],
    },

    {
      id: "ml-neural",
      title: "Neural Networks",
      categoryId: "ml",
      description:
        "From a neuron to a trained net: nonlinearities, backpropagation, representations, and why sequence models forget. Attention is the next course.",
      curriculumVersion: 1,
      orderHint: 1,
      difficultyRange: [2, 4],
      entryRequirements: ["ml-gd", "ml-loss", "ml-overfit"],
      sourceReferences: [
        {
          id: "stanford-cs229",
          title: "Stanford CS229",
          url: "https://cs229.stanford.edu/syllabus-new.html",
          kind: "syllabus",
          notes: "Neural nets after linear models and generalization. Training is a separate lecture from the architecture.",
        },
        {
          id: "stanford-cs224n",
          title: "Stanford CS224N",
          url: "https://web.stanford.edu/class/cs224n/",
          kind: "syllabus",
          notes: "Embeddings and RNNs before attention, even in years that compress the calendar. Assumes ML foundations.",
        },
      ],
      modules: [
        {
          id: "ml-n-net",
          title: "Networks",
          blurb: "Neurons, depth, and a nonlinearity.",
          order: 0,
          prerequisites: [],
          spineIds: ["ml-mlp", "ml-activation"],
        },
        {
          id: "ml-n-train",
          title: "Training nets",
          blurb: "Backprop, initialization, and the ways training dies.",
          order: 1,
          prerequisites: ["ml-n-net"],
          spineIds: ["ml-backprop"],
        },
        {
          id: "ml-n-rep",
          title: "Representations",
          blurb: "Embeddings, convolutions, and sequences before attention.",
          order: 2,
          prerequisites: ["ml-n-train"],
          spineIds: ["ml-emb-intro", "ml-seq-rnn"],
        },
      ],
      concepts: [
        concept("ml-neuron", "The artificial neuron", "ml-n-net", 2, ["ml-logistic"], "A weighted sum, a bias, and a nonlinearity."),
        concept("ml-activation", "Nonlinearities", "ml-n-net", 2, ["ml-neuron"], "Without one, a stack of layers is still a line."),
        concept("ml-mlp", "Multilayer perceptrons", "ml-n-net", 2, ["ml-activation"], "Layers of neurons, each a function of the last."),
        concept("ml-softmax", "Softmax", "ml-n-net", 2, ["ml-logistic"], "Turning scores into a distribution over classes."),
        concept("ml-ce-loss", "Cross-entropy", "ml-n-net", 2, ["ml-softmax", "ml-loss"], "The usual loss when the output is a distribution."),
        concept("ml-depth", "Why depth", "ml-n-net", 3, ["ml-mlp"], "Composition of simple functions instead of one wide shallow map."),
        concept("ml-backprop", "Backpropagation", "ml-n-train", 2, ["ml-gd", "ml-mlp"], "Reverse-mode autodiff, not a separate algorithm from calculus."),
        concept("ml-autodiff", "Reverse-mode autodiff", "ml-n-train", 3, ["ml-backprop"], "One backward pass gives every partial you need."),
        concept("ml-init", "Initialization", "ml-n-train", 3, ["ml-backprop"], "Where the weights start decides whether gradients survive."),
        concept("ml-vanishing", "Vanishing and exploding gradients", "ml-n-train", 3, ["ml-backprop", "ml-depth"], "A product of many derivatives that goes to zero or infinity."),
        concept("ml-sgd-mom", "Momentum and adaptive methods", "ml-n-train", 3, ["ml-gd-variants"], "Remembering recent slopes, scaling per-parameter."),
        concept("ml-batchnorm", "Normalization layers", "ml-n-train", 3, ["ml-mlp"], "Re-centering activations so the next layer sees a stable input."),
        concept("ml-dropout", "Dropout", "ml-n-train", 3, ["ml-overfit"], "Training as an ensemble of thinned nets."),
        concept("ml-overparam", "Overparameterization", "ml-n-train", 3, ["ml-capacity", "ml-mlp"], "More parameters than data points — and it can still generalize."),
        concept("ml-inductive", "Inductive bias", "ml-n-rep", 3, ["ml-hypothesis"], "What the architecture refuses to represent."),
        concept("ml-cnn", "Convolutions", "ml-n-rep", 3, ["ml-mlp", "ml-inductive"], "Weight sharing across space because the world repeats."),
        concept("ml-emb-intro", "Embeddings", "ml-n-rep", 3, ["ml-mlp"], "A learned lookup from a discrete symbol to a vector."),
        concept("ml-repr", "Learned representations", "ml-n-rep", 3, ["ml-emb-intro"], "Features the model invented instead of features you wrote."),
        concept("ml-word2vec", "Distributional embeddings", "ml-n-rep", 3, ["ml-emb-intro"], "You shall know a word by the company it keeps."),
        concept("ml-seq-rnn", "Recurrent sequence models", "ml-n-rep", 3, ["ml-mlp"], "A hidden state that walks the sequence."),
        concept("ml-vanish-seq", "Why RNNs forget", "ml-n-rep", 3, ["ml-seq-rnn", "ml-vanishing"], "The same vanishing product, now across time."),
        concept("ml-transfer", "Transfer learning, first look", "ml-n-rep", 3, ["ml-repr"], "Reuse a representation trained on a different job."),
      ],
    },

    {
      id: "ml-transformers",
      title: "Transformers, LLMs, and Modern AI Systems",
      categoryId: "ml",
      description:
        "Attention, the transformer, pretraining, and the systems around a large model. LLMs are a destination, not lesson one.",
      curriculumVersion: 1,
      orderHint: 2,
      difficultyRange: [3, 5],
      entryRequirements: ["ml-backprop", "ml-emb-intro", "ml-seq-rnn"],
      sourceReferences: [
        {
          id: "stanford-cs224n",
          title: "Stanford CS224N Natural Language Processing with Deep Learning",
          url: "https://web.stanford.edu/class/cs224n/",
          kind: "syllabus",
          notes:
            "Even when the calendar compresses RNNs, attention is taught as a solution to sequence-model limits. Pretraining, then adaptation, then RAG/tools/evaluation. Assumes CS229-level foundations.",
        },
      ],
      modules: [
        {
          id: "ml-t-attn",
          title: "Attention",
          blurb: "Content-addressable lookup over a sequence.",
          order: 0,
          prerequisites: [],
          spineIds: ["ml-attention", "ml-self-attn"],
        },
        {
          id: "ml-t-arch",
          title: "The transformer",
          blurb: "Blocks, positions, and decoder-only language models.",
          order: 1,
          prerequisites: ["ml-t-attn"],
          spineIds: ["ml-transformer"],
        },
        {
          id: "ml-t-pre",
          title: "Pretraining and adaptation",
          blurb: "Scale, objectives, fine-tuning, prompts.",
          order: 2,
          prerequisites: ["ml-t-arch"],
          spineIds: ["ml-pretrain", "ml-finetune"],
        },
        {
          id: "ml-t-sys",
          title: "Systems around the model",
          blurb: "Inference, context, retrieval, tools, failure.",
          order: 3,
          prerequisites: ["ml-t-pre"],
          spineIds: ["ml-inference", "ml-rag", "ml-failure"],
        },
      ],
      concepts: [
        concept("ml-seq-problem", "Sequence transduction", "ml-t-attn", 3, ["ml-seq-rnn"], "Map one sequence onto another without a fixed window."),
        concept("ml-tokenizer", "Tokenization", "ml-t-attn", 3, ["ml-emb-intro"], "The discrete units a model actually sees."),
        concept("ml-attention", "Attention", "ml-t-attn", 3, ["ml-backprop", "ml-seq-problem"], "QKV as a content-addressable lookup, and why it scales."),
        concept("ml-qkv", "Queries, keys, and values", "ml-t-attn", 3, ["ml-attention"], "Three roles for the same tokens."),
        concept("ml-self-attn", "Self-attention", "ml-t-attn", 3, ["ml-qkv"], "Every position looking at every other position in the same sequence."),
        concept("ml-multihead", "Multi-head attention", "ml-t-attn", 4, ["ml-self-attn"], "Several lookups in parallel, each free to specialize."),
        concept("ml-positional", "Positional information", "ml-t-arch", 3, ["ml-self-attn"], "Attention has no order unless you give it one."),
        concept("ml-transformer", "The transformer block", "ml-t-arch", 4, ["ml-multihead", "ml-positional"], "Attention, residual, normalization, feed-forward — stacked."),
        concept("ml-encoder-decoder", "Encoder, decoder, decoder-only", "ml-t-arch", 4, ["ml-transformer"], "Three layouts for three jobs."),
        concept("ml-lm-obj", "Language-model objectives", "ml-t-arch", 4, ["ml-encoder-decoder", "ml-ce-loss"], "Next-token prediction as the pretraining game."),
        concept("ml-pretrain", "Pretraining", "ml-t-pre", 4, ["ml-lm-obj"], "A lot of unlabeled text, one objective, a representation you will reuse."),
        concept("ml-scale", "Scale as a design choice", "ml-t-pre", 4, ["ml-pretrain"], "Parameters, data, and compute as coupled knobs."),
        concept("ml-finetune", "Fine-tuning", "ml-t-pre", 4, ["ml-pretrain", "ml-transfer"], "Continuing training on a narrower distribution."),
        concept("ml-peft", "Parameter-efficient adaptation", "ml-t-pre", 4, ["ml-finetune"], "Changing a small adapter instead of every weight."),
        concept("ml-prompt", "Prompting", "ml-t-pre", 4, ["ml-lm-obj"], "Inference-time control written in the model's own language."),
        concept("ml-align", "Preference tuning", "ml-t-pre", 5, ["ml-finetune"], "SFT, then a preference signal, then the arguments about reward."),
        concept("ml-inference", "Inference versus training", "ml-t-sys", 4, ["ml-transformer"], "The forward pass you serve, without the backward pass you trained."),
        concept("ml-context", "Context windows", "ml-t-sys", 4, ["ml-inference", "ml-positional"], "How much past the model can attend to, and what that costs."),
        concept("ml-kv-cache", "The KV cache", "ml-t-sys", 5, ["ml-context", "ml-inference"], "Remembering keys and values so you do not recompute the past."),
        concept("ml-rag", "Retrieval-augmented generation", "ml-t-sys", 4, ["ml-prompt", "ml-emb-intro"], "Looking something up instead of hoping the weights remember."),
        concept("ml-tools", "Tool use and agents", "ml-t-sys", 4, ["ml-prompt"], "A model that calls a tool, reads the result, and continues."),
        concept("ml-eval-llm", "Evaluating generative models", "ml-t-sys", 4, ["ml-inference"], "Benchmarks, contamination, and the thing a leaderboard cannot see."),
        concept("ml-failure", "Failure modes", "ml-t-sys", 4, ["ml-eval-llm"], "What breaks: reasoning, attribution, calibration, incentives."),
        concept("ml-hallucination", "Hallucination as calibration", "ml-t-sys", 4, ["ml-failure"], "A fluent continuation that is not a retrieved fact."),
        concept("ml-sparsity-attn", "Sparse and linear attention bets", "ml-t-sys", 5, ["ml-self-attn", "ml-context"], "Not every pair of tokens has to meet."),
      ],
    },

    {
      id: "horo-foundations",
      title: "Mechanical Watch Foundations",
      categoryId: "horology",
      description:
        "The whole movement first: power, train, winding, setting. Escapements and complications wait until the simple calibre is thinkable.",
      curriculumVersion: 1,
      orderHint: 0,
      difficultyRange: [0, 2],
      entryRequirements: [],
      sourceReferences: [
        {
          id: "hsny-edu",
          title: "HSNY Horology 101–103",
          url: "https://hs-ny.org/nyc-education",
          kind: "syllabus",
          notes: "101 movement mechanics before 102 gear train before 103 winding/setting. Escapement is 104. Complications are not in the beginner ladder.",
        },
        {
          id: "wostep-training",
          title: "WOSTEP training and education",
          url: "https://www.wostep.ch/index.php/en/training-and-education",
          kind: "syllabus",
          notes: "Theory and component work before chronometry and chronograph as later specializations.",
        },
      ],
      modules: [
        {
          id: "horo-f-move",
          title: "The whole movement",
          blurb: "A machine that counts the unwind of a spring.",
          order: 0,
          prerequisites: [],
          spineIds: ["horo-movement", "horo-nomenclature"],
          sourceIds: ["hsny-edu"],
        },
        {
          id: "horo-f-train",
          title: "Power and the going train",
          blurb: "Barrel, wheels, ratios.",
          order: 1,
          prerequisites: ["horo-f-move"],
          spineIds: ["horo-gear-train", "horo-mainspring"],
        },
        {
          id: "horo-f-set",
          title: "Winding and setting",
          blurb: "How energy gets in and how the hands get moved.",
          order: 2,
          prerequisites: ["horo-f-train"],
          spineIds: ["horo-winding", "horo-setting"],
        },
      ],
      concepts: [
        concept("horo-movement", "A mechanical watch as a machine", "horo-f-move", 0, [], "Stored work, a train, an escapement, a display."),
        concept("horo-nomenclature", "Naming the parts", "horo-f-move", 0, ["horo-movement"], "Plate, bridge, wheel, pinion, jewel — the words the rest of the course uses."),
        concept("horo-tools-intro", "The bench", "horo-f-move", 0, ["horo-movement"], "A movement holder and the discipline of not losing a screw."),
        concept("horo-bridges", "Plates and bridges", "horo-f-move", 1, ["horo-nomenclature"], "The frame everything else is located in."),
        concept("horo-jewels", "Jewels as bearings", "horo-f-move", 1, ["horo-nomenclature"], "Hard, polished holes that reduce friction."),
        concept("horo-disassembly", "Taking down a simple movement", "horo-f-move", 1, ["horo-tools-intro", "horo-bridges"], "Order matters. So does putting it back."),
        concept("horo-hands", "Hands as a display", "horo-f-move", 1, ["horo-movement"], "The hands are not the timebase."),
        concept("horo-mainspring", "The mainspring", "horo-f-train", 0, ["horo-movement"], "A spiral of steel that stores work."),
        concept("horo-barrel", "The barrel", "horo-f-train", 1, ["horo-mainspring"], "The drum that holds the spring and drives the first wheel."),
        concept("horo-gear-train", "The going train", "horo-f-train", 1, ["horo-barrel"], "A reduction from the barrel to the escape wheel."),
        concept("horo-wheel-pinion", "Wheels and pinions", "horo-f-train", 1, ["horo-gear-train"], "A large wheel driving a small pinion, over and over."),
        concept("horo-ratio", "Gear ratios and beat", "horo-f-train", 1, ["horo-wheel-pinion"], "Tooth counts decide how often the escapement ticks."),
        concept("horo-train-math", "Tooth counts as a calculation", "horo-f-train", 2, ["horo-ratio"], "Why 18,000 and 28,800 are not slogans."),
        concept("horo-beat-rate", "Beat rate", "horo-f-train", 1, ["horo-ratio"], "Beats per hour as the movement's clock."),
        concept("horo-power-reserve", "Power reserve", "horo-f-train", 1, ["horo-mainspring"], "How long the spring can run the train."),
        concept("horo-click", "Click and ratchet", "horo-f-train", 1, ["horo-barrel"], "The one-way that keeps the spring from unwinding through the crown."),
        concept("horo-winding", "Winding", "horo-f-set", 1, ["horo-click"], "Putting work back into the spring."),
        concept("horo-stem", "Stem and crown", "horo-f-set", 1, ["horo-winding"], "The shaft the wearer actually turns."),
        concept("horo-setting", "Setting the hands", "horo-f-set", 1, ["horo-hands", "horo-stem"], "Decoupling the display from the timebase."),
        concept("horo-keyless", "Keyless works", "horo-f-set", 2, ["horo-setting", "horo-winding"], "The clutch that chooses wind versus set."),
        concept("horo-cannon", "Cannon pinion and motion works", "horo-f-set", 1, ["horo-setting"], "Hour and minute as a 12:1 reduction."),
        concept("horo-dial-train", "Motion works versus going train", "horo-f-set", 1, ["horo-cannon", "horo-gear-train"], "Two trains, two jobs."),
        concept("horo-lubrication", "Lubrication", "horo-f-set", 2, ["horo-jewels"], "The right oil in the right place, and nowhere else."),
        concept("horo-endshake", "Endshake and freedom", "horo-f-set", 2, ["horo-jewels"], "A pivot that must move, but not rattle."),
      ],
    },

    {
      id: "horo-regulation",
      title: "Escapements, Regulation, and Timekeeping",
      categoryId: "horology",
      description:
        "How a spring's unwind becomes counted ticks, and how those ticks are made honest: lever, balance, hairspring, positions, isochronism.",
      curriculumVersion: 1,
      orderHint: 1,
      difficultyRange: [1, 4],
      entryRequirements: ["horo-gear-train", "horo-mainspring"],
      sourceReferences: [
        {
          id: "hsny-edu",
          title: "HSNY Horology 104",
          url: "https://hs-ny.org/nyc-education",
          kind: "syllabus",
          notes: "Escapement after the rest of the movement exists. Lever, models, real movements.",
        },
        {
          id: "wostep-chrono",
          title: "WOSTEP Chronometry Adjustments",
          url: "https://www.wostep.ch/index.php/en/training/chronometry-adjustments",
          kind: "syllabus",
          notes: "Swiss lever adjustments, then regulating organ: poise, hairspring, dynamic poising. Requires a finished simple movement.",
        },
      ],
      modules: [
        {
          id: "horo-r-escape",
          title: "The escapement",
          blurb: "Lock, impulse, drop.",
          order: 0,
          prerequisites: [],
          spineIds: ["horo-escape", "horo-lever"],
        },
        {
          id: "horo-r-organ",
          title: "The regulating organ",
          blurb: "Balance and hairspring.",
          order: 1,
          prerequisites: ["horo-r-escape"],
          spineIds: ["horo-balance", "horo-hairspring"],
        },
        {
          id: "horo-r-time",
          title: "Timing and positions",
          blurb: "Rate, isochronism, the timing machine.",
          order: 2,
          prerequisites: ["horo-r-organ"],
          spineIds: ["horo-isochronism", "horo-positional"],
        },
      ],
      concepts: [
        concept("horo-escape", "The escapement", "horo-r-escape", 1, ["horo-gear-train"], "Turning a spring’s unwind into counted ticks."),
        concept("horo-recoil-vs-detached", "Recoil versus detached", "horo-r-escape", 2, ["horo-escape"], "Whether the oscillator is left alone between impulses."),
        concept("horo-lever", "The Swiss lever", "horo-r-escape", 2, ["horo-escape"], "The detached lever as the modern default."),
        concept("horo-escape-wheel", "The escape wheel", "horo-r-escape", 2, ["horo-lever"], "The last wheel of the train, delivering impulse."),
        concept("horo-pallet", "Pallet stones", "horo-r-escape", 2, ["horo-lever"], "Entry and exit jewels that lock and impulse."),
        concept("horo-impulse", "Impulse and locking", "horo-r-escape", 2, ["horo-pallet", "horo-escape-wheel"], "Two jobs that must not blur."),
        concept("horo-draw", "Draw", "horo-r-escape", 3, ["horo-impulse"], "The geometry that pulls the lever onto the banking."),
        concept("horo-lock-drop", "Lock, drop, and slide", "horo-r-escape", 3, ["horo-impulse"], "The measured freedoms that keep the escapement safe."),
        concept("horo-impulse-pin", "Impulse pin and roller", "horo-r-escape", 2, ["horo-lever"], "How the lever talks to the balance."),
        concept("horo-safety", "Safety action", "horo-r-escape", 3, ["horo-impulse-pin"], "What stops a knock from unlocking the wrong pallet."),
        concept("horo-balance", "The balance wheel", "horo-r-organ", 2, ["horo-escape"], "The mass that oscillates."),
        concept("horo-hairspring", "The hairspring", "horo-r-organ", 2, ["horo-balance"], "The restoring spring that sets the period."),
        concept("horo-regulator", "Regulator versus free-sprung", "horo-r-organ", 2, ["horo-hairspring"], "Changing effective length versus changing inertia."),
        concept("horo-quartz-contrast", "What quartz is not doing", "horo-r-organ", 1, ["horo-escape"], "A crystal and a divider, not a lever."),
        concept("horo-rate", "Daily rate", "horo-r-time", 2, ["horo-beat-rate", "horo-hairspring"], "Seconds per day as the number you regulate."),
        concept("horo-isochronism", "Isochronism", "horo-r-time", 3, ["horo-hairspring", "horo-rate"], "Period that does not care about amplitude — in theory."),
        concept("horo-amplitude", "Amplitude", "horo-r-time", 3, ["horo-balance"], "How far the balance swings, and why it fades."),
        concept("horo-positional", "Positional timing", "horo-r-time", 3, ["horo-rate"], "Dial up is not pendant up."),
        concept("horo-poise", "Poising", "horo-r-time", 3, ["horo-positional", "horo-balance"], "A heavy spot on the balance that gravity can find."),
        concept("horo-beat-error", "Beat error", "horo-r-time", 3, ["horo-impulse-pin"], "Rest position that is not the middle of the roller."),
        concept("horo-timing-machine", "The timing machine", "horo-r-time", 3, ["horo-rate"], "A microphone and a diagram of rate, amplitude, beat."),
        concept("horo-temp", "Temperature and the balance", "horo-r-time", 3, ["horo-hairspring"], "Steel that changes modulus when the room does."),
        concept("horo-magnet", "Magnetism", "horo-r-time", 3, ["horo-hairspring"], "A spring that sticks to itself."),
        concept("horo-lubrication-escape", "Escapement oil", "horo-r-time", 3, ["horo-lubrication", "horo-pallet"], "A tiny film on a pallet stone, and the ways it migrates."),
      ],
    },

    {
      id: "horo-complications",
      title: "Complications and Advanced Watchmaking",
      categoryId: "horology",
      description:
        "After the simple movement is honest: calendars, chronographs, automatic winding, tourbillons, and the finishing a service actually protects.",
      curriculumVersion: 1,
      orderHint: 2,
      difficultyRange: [2, 5],
      entryRequirements: ["horo-escape", "horo-setting"],
      sourceReferences: [
        {
          id: "wostep-chrono",
          title: "WOSTEP Chronograph / Chronometry",
          url: "https://www.wostep.ch/index.php/en/training/chronograph",
          kind: "syllabus",
          notes: "Chronograph as a later specialization. Timing remains a discipline. Tourbillon is not a beginner object.",
        },
        {
          id: "hsny-edu",
          title: "HSNY education ladder",
          url: "https://hs-ny.org/nyc-education",
          kind: "syllabus",
          notes: "Complications sit after 101–104, not inside them.",
        },
      ],
      modules: [
        {
          id: "horo-c-time",
          title: "Timekeeping extras",
          blurb: "Date, GMT, automatic winding.",
          order: 0,
          prerequisites: [],
          spineIds: ["horo-date", "horo-auto-winding"],
        },
        {
          id: "horo-c-chrono",
          title: "Chronograph",
          blurb: "A stopwatch grafted onto a watch.",
          order: 1,
          prerequisites: ["horo-c-time"],
          spineIds: ["horo-chrono"],
        },
        {
          id: "horo-c-show",
          title: "High complications and finishing",
          blurb: "Tourbillon, striking, what a service is.",
          order: 2,
          prerequisites: ["horo-c-chrono"],
          spineIds: ["horo-tourbillon", "horo-service"],
        },
      ],
      concepts: [
        concept("horo-date", "Simple date", "horo-c-time", 2, ["horo-cannon"], "A 31-tooth wheel the motion works advances once a day."),
        concept("horo-calendar", "Annual and perpetual calendars", "horo-c-time", 3, ["horo-date"], "Remembering months, and sometimes leap years."),
        concept("horo-moon", "Moonphase", "horo-c-time", 3, ["horo-date"], "A 59-tooth compromise with the sky."),
        concept("horo-gmt", "GMT and world time", "horo-c-time", 3, ["horo-setting"], "A second hour hand, or a disc of cities."),
        concept("horo-alarm", "Alarm", "horo-c-time", 3, ["horo-mainspring"], "A second barrel whose job is noise."),
        concept("horo-auto-winding", "Automatic winding", "horo-c-time", 3, ["horo-winding"], "A rotor that winds so the wearer does not have to."),
        concept("horo-rotor", "The rotor", "horo-c-time", 3, ["horo-auto-winding"], "A weight that turns, and the reverser that makes both ways count."),
        concept("horo-power-reserve-ind", "Power-reserve indication", "horo-c-time", 3, ["horo-power-reserve"], "A hand that tracks the barrel, not the time."),
        concept("horo-chrono", "Chronograph", "horo-c-chrono", 3, ["horo-escape", "horo-setting"], "Start, stop, reset — a second train clutched in."),
        concept("horo-column-wheel", "Column wheel versus cam", "horo-c-chrono", 4, ["horo-chrono"], "How the pusher's logic is remembered."),
        concept("horo-chrono-reset", "Reset and hammers", "horo-c-chrono", 4, ["horo-chrono"], "Hearts on the chronograph wheels, and the hammers that find them."),
        concept("horo-flyback", "Flyback", "horo-c-chrono", 4, ["horo-chrono-reset"], "Reset that restarts without a separate stop."),
        concept("horo-rattrapante", "Rattrapante", "horo-c-chrono", 5, ["horo-chrono"], "A split seconds hand that can wait."),
        concept("horo-tourbillon", "The tourbillon", "horo-c-show", 3, ["horo-escape", "horo-positional"], "Averaging positional error, and when it is theater."),
        concept("horo-tourbillon-honest", "When a tourbillon is theater", "horo-c-show", 4, ["horo-tourbillon", "horo-isochronism"], "A wrist is not a pocket. Rotation does not cancel every error."),
        concept("horo-repeater", "Minute repeater", "horo-c-show", 5, ["horo-cannon"], "Sounding the time with racks and snails."),
        concept("horo-striking", "Striking work", "horo-c-show", 5, ["horo-repeater"], "A second gear train whose product is sound."),
        concept("horo-equation", "Equation of time", "horo-c-show", 5, ["horo-calendar"], "The difference between sundial noon and mean noon."),
        concept("horo-finishing", "Finishing", "horo-c-show", 3, ["horo-bridges"], "Anglage and perlage as function and display."),
        concept("horo-service", "What a service actually does", "horo-c-show", 3, ["horo-lubrication", "horo-disassembly"], "Clean, oil, adjust — not a battery."),
        concept("horo-accuracy-claim", "COSC and certificates", "horo-c-show", 3, ["horo-positional", "horo-rate"], "A protocol, not a personality."),
        concept("horo-silicon", "Silicon hairsprings and escapes", "horo-c-show", 4, ["horo-hairspring", "horo-magnet"], "A material that does not magnetize and does not rust."),
      ],
    },

    {
      id: "mus-foundations",
      title: "Music Theory Foundations",
      categoryId: "music-theory",
      description:
        "Sound as elements, then intervals, scales, modes, rhythm, and meter. Harmony as a craft waits until these names are honest. Built to support later heavy-music work, not a conservatory recital track.",
      curriculumVersion: 1,
      orderHint: 0,
      difficultyRange: [0, 2],
      entryRequirements: [],
      sourceReferences: [
        {
          id: "mit-21m051",
          title: "MIT 21M.051 Fundamentals of Music",
          url: "https://ocw.mit.edu/courses/21m-051-fundamentals-of-music-spring-2007/pages/syllabus/",
          kind: "ocw",
          notes: "Elements and rhythm/pitch before major/minor, then functional harmony last. Ear and notation travel with the theory.",
        },
        {
          id: "berklee-guitar",
          title: "Berklee Guitar Fundamentals",
          url: "https://online.berklee.edu/courses/guitar-fundamentals",
          kind: "syllabus",
          notes: "Technique and basic harmonic literacy that death-metal construction should assume, not duplicate.",
        },
      ],
      modules: [
        {
          id: "mus-f-elem",
          title: "Sound as elements",
          blurb: "Pitch, duration, loudness, notation.",
          order: 0,
          prerequisites: [],
          spineIds: ["mus-sound", "mus-interval"],
          sourceIds: ["mit-21m051"],
        },
        {
          id: "mus-f-pitch",
          title: "Pitch collections",
          blurb: "Scales, keys, modes.",
          order: 1,
          prerequisites: ["mus-f-elem"],
          spineIds: ["mus-scale", "mus-modes"],
        },
        {
          id: "mus-f-rhythm",
          title: "Rhythm and meter",
          blurb: "Pulse, bars, and the off-beat.",
          order: 2,
          prerequisites: ["mus-f-elem"],
          spineIds: ["mus-meter", "mus-rhythm"],
        },
      ],
      concepts: [
        concept("mus-sound", "Pitch, duration, loudness, timbre", "mus-f-elem", 0, [], "The four things a note can be before it is a theory problem."),
        concept("mus-notation", "Notation as a map", "mus-f-elem", 0, ["mus-sound"], "A staff is a diagram, not the music."),
        concept("mus-clef", "Staves and clefs", "mus-f-elem", 0, ["mus-notation"], "Where a pitch sits depends on the clef."),
        concept("mus-octave", "Octave equivalence", "mus-f-elem", 0, ["mus-sound"], "The same letter, a doubling of frequency."),
        concept("mus-semitone", "Semitones and the chromatic collection", "mus-f-elem", 1, ["mus-octave"], "Twelve named steps in the common tuning."),
        concept("mus-interval", "Intervals and consonance", "mus-f-elem", 1, ["mus-semitone"], "Ratios, beating, and why a fifth sits still."),
        concept("mus-ear-interval", "Hearing an interval", "mus-f-elem", 1, ["mus-interval"], "A name that has to survive without the page."),
        concept("mus-scale", "Scales", "mus-f-pitch", 1, ["mus-interval"], "An ordered pitch collection with a tonic."),
        concept("mus-major", "The major scale", "mus-f-pitch", 1, ["mus-scale"], "W-W-H-W-W-W-H as a pattern, not a mood."),
        concept("mus-minor", "Minor scales", "mus-f-pitch", 1, ["mus-major"], "Natural, harmonic, melodic — three answers to one tonic."),
        concept("mus-key", "Key and tonic", "mus-f-pitch", 1, ["mus-scale"], "The pitch everything else is measured from."),
        concept("mus-modes", "Modes", "mus-f-pitch", 2, ["mus-interval", "mus-scale"], "Same pitch set, different tonic gravity."),
        concept("mus-circle", "Circle of fifths", "mus-f-pitch", 2, ["mus-key"], "Near keys share almost all their pitches."),
        concept("mus-enharmonic", "Enharmonic spelling", "mus-f-pitch", 2, ["mus-semitone"], "F♯ and G♭ are the same key and a different claim."),
        concept("mus-pentatonic", "Pentatonic collections", "mus-f-pitch", 1, ["mus-scale"], "A reduced set that still implies a tonic."),
        concept("mus-rhythm", "Pulse and rhythm", "mus-f-rhythm", 0, ["mus-sound"], "When events happen, independent of which pitch."),
        concept("mus-rest", "Silence as rhythm", "mus-f-rhythm", 0, ["mus-rhythm"], "A rest is an event."),
        concept("mus-meter", "Meter", "mus-f-rhythm", 1, ["mus-rhythm"], "A repeating accent pattern you can count."),
        concept("mus-beat-div", "Beat subdivision", "mus-f-rhythm", 1, ["mus-meter"], "Twos and threes inside the beat."),
        concept("mus-tempo", "Tempo", "mus-f-rhythm", 1, ["mus-meter"], "How fast the pulse is, not how busy the surface is."),
        concept("mus-tie-dot", "Ties and dots", "mus-f-rhythm", 1, ["mus-rhythm"], "Ways of writing a duration that crosses a beat."),
        concept("mus-anacrusis", "Pickup and downbeat", "mus-f-rhythm", 1, ["mus-meter"], "Starting before the barline."),
        concept("mus-syncopation", "Syncopation", "mus-f-rhythm", 2, ["mus-meter"], "Accent where the meter did not ask for one."),
        concept("mus-polyrhythm-intro", "Polyrhythm, first look", "mus-f-rhythm", 2, ["mus-beat-div"], "Two subdivisions at once."),
      ],
    },

    {
      id: "mus-harmony",
      title: "Harmony, Voice Leading, and Rhythm",
      categoryId: "music-theory",
      description:
        "Triads to function, voice leading as a craft, then chromaticism and mixture — the bridge from common-practice grammar toward the vocabulary heavy music actually uses.",
      curriculumVersion: 1,
      orderHint: 1,
      difficultyRange: [1, 3],
      entryRequirements: ["mus-interval", "mus-scale", "mus-meter"],
      sourceReferences: [
        {
          id: "mit-21m301",
          title: "MIT 21M.301 Harmony and Counterpoint I",
          url: "https://ocw.mit.edu/courses/21m-301-harmony-and-counterpoint-i-spring-2005/pages/syllabus/",
          kind: "ocw",
          notes: "Species counterpoint and four-part writing as the way harmonic function becomes a craft. Voice leading is a prerequisite to analysis.",
        },
        {
          id: "mit-21m302",
          title: "MIT 21M.302 Harmony and Counterpoint II",
          url: "https://ocw.mit.edu/courses/21m-302-harmony-and-counterpoint-ii-spring-2005/pages/syllabus/",
          kind: "ocw",
          notes: "Chromaticism, mixture, modulation. The bridge toward the chromatic vocabulary heavy music uses.",
        },
      ],
      modules: [
        {
          id: "mus-h-func",
          title: "Harmonic function",
          blurb: "Triads, sevenths, tonic-predominant-dominant.",
          order: 0,
          prerequisites: [],
          spineIds: ["mus-triad", "mus-function"],
        },
        {
          id: "mus-h-voice",
          title: "Voice leading",
          blurb: "How parts move.",
          order: 1,
          prerequisites: ["mus-h-func"],
          spineIds: ["mus-voice-lead"],
        },
        {
          id: "mus-h-chrom",
          title: "Chromaticism",
          blurb: "Mixture, secondary dominants, modulation.",
          order: 2,
          prerequisites: ["mus-h-voice"],
          spineIds: ["mus-chromatic", "mus-modulation"],
        },
      ],
      concepts: [
        concept("mus-triad", "Triads", "mus-h-func", 1, ["mus-interval", "mus-scale"], "Three notes stacked in thirds."),
        concept("mus-seventh", "Seventh chords", "mus-h-func", 2, ["mus-triad"], "A fourth note, and a new set of tendencies."),
        concept("mus-inversion", "Inversion", "mus-h-func", 2, ["mus-triad"], "The same pitch classes, a different bass."),
        concept("mus-function", "Tonic, predominant, dominant", "mus-h-func", 2, ["mus-triad", "mus-key"], "Three jobs a chord can have in a key."),
        concept("mus-cadence", "Cadences", "mus-h-func", 2, ["mus-function"], "How a phrase decides it is over."),
        concept("mus-progress", "Common-practice progression", "mus-h-func", 2, ["mus-function"], "A grammar, not a law of nature."),
        concept("mus-phrase", "Phrase and period", "mus-h-func", 2, ["mus-cadence"], "Antecedent and consequent as a small form."),
        concept("mus-power-chord", "Fifths without a third", "mus-h-func", 2, ["mus-interval"], "A dyad that refuses to be major or minor."),
        concept("mus-voice-lead", "Voice leading", "mus-h-voice", 2, ["mus-function"], "Each part as a line, not a stack of names."),
        concept("mus-species", "Species counterpoint as a craft", "mus-h-voice", 2, ["mus-voice-lead"], "Constraints that teach you what a line can do."),
        concept("mus-parallel", "Parallel fifths and octaves", "mus-h-voice", 2, ["mus-voice-lead"], "Why they were banned, and when a riff does not care."),
        concept("mus-tension-tone", "Tendency tones", "mus-h-voice", 2, ["mus-voice-lead", "mus-major"], "Leading tones and chordal sevenths that want to resolve."),
        concept("mus-dissonance", "Dissonance as a timed event", "mus-h-voice", 2, ["mus-interval"], "A clash that is prepared, struck, and left."),
        concept("mus-nonchord", "Non-chord tones", "mus-h-voice", 2, ["mus-dissonance"], "Passing, neighbor, suspension — names for how you got there."),
        concept("mus-texture", "Texture", "mus-h-voice", 2, ["mus-voice-lead"], "How many parts, and whether they share a rhythm."),
        concept("mus-drop", "Drop voicings", "mus-h-voice", 2, ["mus-inversion"], "Spreading a close position by dropping a voice an octave."),
        concept("mus-pedal", "Pedal point", "mus-h-voice", 2, ["mus-function"], "A held bass against changing harmony."),
        concept("mus-secondary", "Secondary dominants", "mus-h-chrom", 3, ["mus-function"], "Temporarily treating another chord as a tonic."),
        concept("mus-mixture", "Modal mixture", "mus-h-chrom", 3, ["mus-function", "mus-modes"], "Borrowing a chord from the parallel mode."),
        concept("mus-modulation", "Modulation", "mus-h-chrom", 3, ["mus-secondary", "mus-key"], "Changing tonic and meaning it."),
        concept("mus-chromatic", "Chromaticism", "mus-h-chrom", 3, ["mus-mixture"], "Pitches outside the key that still have a job."),
        concept("mus-neapolitan", "Neapolitan and augmented sixths", "mus-h-chrom", 3, ["mus-chromatic"], "Predominants that approach the dominant from the side."),
        concept("mus-seq-harm", "Sequence", "mus-h-chrom", 2, ["mus-progress"], "A pattern that transposes itself."),
      ],
    },

    {
      id: "mus-heavy",
      title: "Advanced Analysis for Modern Heavy Music",
      categoryId: "music-theory",
      description:
        "Non-functional harmony, unusual meter, riff-as-harmony, and an analysis method that does not force a chorale onto a blast-beat song.",
      curriculumVersion: 1,
      orderHint: 2,
      difficultyRange: [3, 4],
      entryRequirements: ["mus-function", "mus-modes", "mus-voice-lead"],
      sourceReferences: [
        {
          id: "mit-21m350",
          title: "MIT 21M.350 Musical Analysis",
          url: "https://ocw.mit.edu/courses/21m-350-musical-analysis-spring-2008/pages/syllabus/",
          kind: "ocw",
          notes: "Form and analysis as a method. We reuse the method on riff-based music rather than copying the repertoire.",
        },
        {
          id: "mit-21m302",
          title: "MIT 21M.302",
          url: "https://ocw.mit.edu/courses/21m-302-harmony-and-counterpoint-ii-spring-2005/pages/syllabus/",
          kind: "ocw",
          notes: "Chromatic craft is the last common-practice tool this course still needs.",
        },
      ],
      modules: [
        {
          id: "mus-x-nonfunc",
          title: "Beyond function",
          blurb: "Planing, mediants, modes that refuse a dominant.",
          order: 0,
          prerequisites: [],
          spineIds: ["mus-nonfunc", "mus-planing"],
        },
        {
          id: "mus-x-meter",
          title: "Meter that lies",
          blurb: "Odd meters, polymeter, displacement.",
          order: 1,
          prerequisites: ["mus-x-nonfunc"],
          spineIds: ["mus-odd-meter", "mus-polymeter"],
        },
        {
          id: "mus-x-riff",
          title: "Riff as harmony",
          blurb: "Pedals, cells, distortion, analysis.",
          order: 2,
          prerequisites: ["mus-x-meter"],
          spineIds: ["mus-riff-harmony", "mus-analysis-method"],
        },
      ],
      concepts: [
        concept("mus-nonfunc", "Non-functional harmony", "mus-x-nonfunc", 3, ["mus-function"], "Progression that does not report to a dominant."),
        concept("mus-planing", "Planing", "mus-x-nonfunc", 3, ["mus-nonfunc", "mus-voice-lead"], "A shape that slides, keeping its intervals."),
        concept("mus-chromatic-mediant", "Chromatic mediants", "mus-x-nonfunc", 3, ["mus-nonfunc"], "Roots a third apart, few common tones, a lot of color."),
        concept("mus-tritone", "Tritone relationships", "mus-x-nonfunc", 3, ["mus-interval", "mus-nonfunc"], "The interval that bisects the octave."),
        concept("mus-locrian", "Locrian and the diminished tonic", "mus-x-nonfunc", 3, ["mus-modes"], "A mode whose tonic triad is already unstable."),
        concept("mus-phrygian", "Phrygian and the flat second", "mus-x-nonfunc", 3, ["mus-modes"], "The half-step above the tonic as a signature."),
        concept("mus-harmonic-minor", "Harmonic minor as a metal default", "mus-x-nonfunc", 3, ["mus-minor"], "The raised seventh without the rest of the classical contract."),
        concept("mus-octatonic", "Octatonic collections", "mus-x-nonfunc", 4, ["mus-semitone"], "Alternating tones and semitones, two flavors."),
        concept("mus-odd-meter", "Odd meter", "mus-x-meter", 3, ["mus-meter"], "Bars that are not 2 or 4 on the surface."),
        concept("mus-polymeter", "Polymeter", "mus-x-meter", 4, ["mus-odd-meter", "mus-polyrhythm-intro"], "Two meters at once, coinciding later."),
        concept("mus-metric-ambig", "Metric ambiguity", "mus-x-meter", 4, ["mus-odd-meter"], "A pulse you cannot yet group."),
        concept("mus-displacement", "Rhythmic displacement", "mus-x-meter", 3, ["mus-syncopation"], "The same cell, started on a different beat."),
        concept("mus-hemiola", "Hemiola and 3:2", "mus-x-meter", 3, ["mus-polyrhythm-intro"], "Three in the time of two, or the reverse."),
        concept("mus-riff-harmony", "Riff-based harmony", "mus-x-riff", 3, ["mus-nonfunc", "mus-power-chord"], "The riff is the progression."),
        concept("mus-pedal-riff", "Pedal-tone riffs", "mus-x-riff", 3, ["mus-pedal", "mus-riff-harmony"], "An open string that everything else grinds against."),
        concept("mus-chromatic-riff", "Chromatic riff cells", "mus-x-riff", 3, ["mus-chromatic", "mus-riff-harmony"], "Semitone motion as the material, not the decoration."),
        concept("mus-dissonant-voicing", "Cluster and close dissonance", "mus-x-riff", 3, ["mus-dissonance"], "Seconds stacked until the chord has no name."),
        concept("mus-form-riff", "Form built from riffs", "mus-x-riff", 3, ["mus-riff-harmony", "mus-phrase"], "Contrast and return without a verse-chorus contract."),
        concept("mus-analysis-method", "What analysis is for", "mus-x-riff", 3, ["mus-form-riff"], "A method: what repeats, what contrasts, what is the cell."),
        concept("mus-reduction", "Reduction without forcing a chorale", "mus-x-riff", 4, ["mus-analysis-method"], "Strip the surface. Do not invent a I–V that is not there."),
        concept("mus-timbre-harmony", "Distortion as a harmonic fact", "mus-x-riff", 3, ["mus-power-chord"], "Gain adds partials. A fifth becomes a crowd."),
        concept("mus-drop-tune", "Drop tunings and string physics", "mus-x-riff", 3, ["mus-power-chord"], "A lowered sixth string that makes the power chord one finger."),
      ],
    },

    {
      id: "dm-history",
      title: "Death Metal History and Vocabulary",
      categoryId: "death-metal",
      description:
        "Listening literacy: lineage, the thrash transition, Florida and Stockholm as production doctrines, then the branches. Scenes, not celebrity lists.",
      curriculumVersion: 1,
      orderHint: 0,
      difficultyRange: [0, 2],
      entryRequirements: [],
      sourceReferences: [
        {
          id: "mit-metal101",
          title: "MIT Heavy Metal 101",
          url: "https://ocw.mit.edu/courses/res-21m-001-heavy-metal-101-january-iap-2025/",
          kind: "ocw",
          notes: "History, listening, culture, songwriting tropes, harsh vocals — not celebrity lists. Extreme metal is a sound and a construction problem.",
        },
      ],
      modules: [
        {
          id: "dm-h-lineage",
          title: "Before it was named",
          blurb: "Lineage and the thrash/extreme cut.",
          order: 0,
          prerequisites: [],
          spineIds: ["dm-lineage", "dm-listening"],
        },
        {
          id: "dm-h-scenes",
          title: "Two founding scenes",
          blurb: "Florida and Stockholm as doctrines.",
          order: 1,
          prerequisites: ["dm-h-lineage"],
          spineIds: ["dm-history", "dm-production-doctrine"],
        },
        {
          id: "dm-h-branches",
          title: "Branches",
          blurb: "Brutal, technical, progressive, dissonant.",
          order: 2,
          prerequisites: ["dm-h-scenes"],
          spineIds: ["dm-brutal", "dm-tech-hist"],
        },
      ],
      concepts: [
        concept("dm-lineage", "Pre-death-metal lineage", "dm-h-lineage", 0, [], "Hardcore, thrash, and extreme metal as the soil, not a name-drop."),
        concept("dm-listening", "How to listen to a death-metal record", "dm-h-lineage", 1, ["dm-lineage"], "Riff, kit, vocal as equal parts. The mix is an argument."),
        concept("dm-thrash-bridge", "The thrash/extreme transition", "dm-h-lineage", 1, ["dm-lineage"], "When speed stopped being the point and weight took over."),
        concept("dm-vocal-hist", "Harsh vocals as a lineage", "dm-h-lineage", 1, ["dm-listening"], "A technique with a history, not a personality."),
        concept("dm-scene-not-celeb", "Scenes, not celebrity lists", "dm-h-lineage", 1, ["dm-lineage"], "A city, a studio, a tape network."),
        concept("dm-tape-trading", "How the style spread", "dm-h-lineage", 1, ["dm-scene-not-celeb"], "Tapes, zines, and the fact that scenes were postal."),
        concept("dm-history", "Florida and Stockholm", "dm-h-scenes", 1, ["dm-listening"], "Two scenes, two production doctrines, one genre name."),
        concept("dm-florida", "The Florida sound", "dm-h-scenes", 1, ["dm-history"], "Clarity, palm-mute punctuation, a particular drum sound."),
        concept("dm-stockholm", "The Stockholm sound", "dm-h-scenes", 1, ["dm-history"], "Buzzsaw guitars and a drier, dirtier midrange."),
        concept("dm-production-doctrine", "Production as a stylistic fact", "dm-h-scenes", 2, ["dm-florida", "dm-stockholm"], "The mix is part of the composition."),
        concept("dm-gore-vs-occult", "Lyrical domains", "dm-h-scenes", 1, ["dm-listening"], "Gore, occult, and social disgust as registers — not trivia."),
        concept("dm-double-kick-hist", "Double-kick as a historical marker", "dm-h-scenes", 1, ["dm-listening"], "When the right foot stopped being enough."),
        concept("dm-brutal", "Brutal death metal", "dm-h-branches", 2, ["dm-history"], "Lower, thicker, less interested in a sung interval."),
        concept("dm-tech-hist", "Technical death metal as a branch", "dm-h-branches", 2, ["dm-history"], "Density and odd grouping as a scene, not a compliment."),
        concept("dm-prog-hist", "Progressive death metal as a branch", "dm-h-branches", 2, ["dm-history"], "Longer forms and borrowed jazz/fusion grammar."),
        concept("dm-dissonant-hist", "Dissonant and avant-garde branches", "dm-h-branches", 2, ["dm-history"], "When the riff stops agreeing with itself."),
        concept("dm-melodeath", "Melodic death metal as a fork", "dm-h-branches", 2, ["dm-stockholm"], "Harmony that wants to be sung, still under distortion."),
        concept("dm-grind-border", "The grind border", "dm-h-branches", 2, ["dm-brutal"], "Duration and blast as a different contract."),
        concept("dm-ossuary", "A second wave of brutality", "dm-h-branches", 2, ["dm-brutal"], "What 'brutal' meant a decade later."),
        concept("dm-tech-90s", "1990s technicality", "dm-h-branches", 2, ["dm-tech-hist"], "The first records that treated odd grouping as normal."),
        concept("dm-modern-wave", "The later technical/dissonant wave", "dm-h-branches", 2, ["dm-dissonant-hist", "dm-tech-hist"], "2000s onward: triggers, tighter grids, colder harmony."),
        concept("dm-regional", "Regional dialects after the two capitals", "dm-h-branches", 2, ["dm-history"], "Quebec, Poland, the American south, and why the accent is the riff."),
      ],
    },

    {
      id: "dm-construction",
      title: "Riff, Rhythm, and Harmony Construction",
      categoryId: "death-metal",
      description:
        "How the music is built: riff cells, tremolo, chromatic motion, pedal tones, blast and double-kick vocabulary, song structure. Assumes music-theory foundations rather than reteaching intervals.",
      curriculumVersion: 1,
      orderHint: 1,
      difficultyRange: [2, 4],
      entryRequirements: ["mus-interval", "mus-modes", "mus-meter", "dm-listening"],
      sourceReferences: [
        {
          id: "berklee-metal",
          title: "Berklee Metal Guitar",
          url: "https://online.berklee.edu/courses/metal-guitar",
          kind: "syllabus",
          notes: "Riff vocabulary, rhythm, modes, and right-hand technique as construction skills. Depends on fundamentals rather than reteaching intervals.",
        },
        {
          id: "mit-metal101",
          title: "MIT Heavy Metal 101",
          url: "https://ocw.mit.edu/courses/res-21m-001-heavy-metal-101-january-iap-2025/",
          kind: "ocw",
          notes: "Songwriting tropes and technique as construction, not celebrity.",
        },
        {
          id: "berklee-guitar",
          title: "Berklee Guitar Fundamentals",
          url: "https://online.berklee.edu/courses/guitar-fundamentals",
          kind: "syllabus",
          notes: "This course must not duplicate interval and meter literacy.",
        },
      ],
      modules: [
        {
          id: "dm-c-riff",
          title: "Riff vocabulary",
          blurb: "Cells, tremolo, chromatic motion, pedals.",
          order: 0,
          prerequisites: [],
          spineIds: ["dm-riff-cell", "dm-harmony"],
        },
        {
          id: "dm-c-rhythm",
          title: "Rhythm-section grammar",
          blurb: "Blast, double-kick, displacement.",
          order: 1,
          prerequisites: ["dm-c-riff"],
          spineIds: ["dm-blast", "dm-double-kick"],
        },
        {
          id: "dm-c-form",
          title: "Putting a song together",
          blurb: "Structure, two guitars, vocals as rhythm.",
          order: 2,
          prerequisites: ["dm-c-rhythm"],
          spineIds: ["dm-song-form", "dm-riff-form"],
        },
      ],
      concepts: [
        concept("dm-riff-cell", "The riff cell", "dm-c-riff", 2, ["mus-interval", "dm-listening"], "A short figure that can be repeated, displaced, or mutated."),
        concept("dm-tremolo", "Tremolo writing", "dm-c-riff", 2, ["dm-riff-cell"], "Picking that turns a pitch into a surface."),
        concept("dm-chromatic-move", "Chromatic movement", "dm-c-riff", 2, ["dm-riff-cell", "mus-semitone"], "Semitone steps as the riff's spine."),
        concept("dm-pedal-tone", "Pedal tones", "dm-c-riff", 2, ["dm-riff-cell", "mus-pedal"], "An open string that the cell grinds against."),
        concept("dm-harmony", "Death-metal harmony", "dm-c-riff", 2, ["mus-interval", "mus-modes", "dm-riff-cell"], "Diminished cells, chromatic planing, and riff as form."),
        concept("dm-diminished", "Diminished cells", "dm-c-riff", 2, ["dm-harmony", "mus-tritone"], "Minor thirds stacked until the octave repeats."),
        concept("dm-tritone-riff", "Tritone and flat-2 riffs", "dm-c-riff", 2, ["dm-harmony", "mus-phrygian"], "The two intervals this style treats as home."),
        concept("dm-palm-mute", "Palm mute as orchestration", "dm-c-riff", 2, ["dm-riff-cell"], "Choked versus open as two instruments."),
        concept("dm-guitar-tune", "Tunings that change the riff", "dm-c-riff", 2, ["dm-pedal-tone", "mus-drop-tune"], "A dropped string is a compositional choice."),
        concept("dm-pick-hand", "Right-hand endurance versus accent", "dm-c-riff", 2, ["dm-tremolo"], "Speed that still has a downbeat."),
        concept("dm-blast", "Blast beats", "dm-c-rhythm", 2, ["dm-listening", "mus-meter"], "The drum grammar that made death metal possible."),
        concept("dm-blast-types", "Blast vocabulary", "dm-c-rhythm", 3, ["dm-blast"], "Traditional, bomb, hammer — different occupations of the kit."),
        concept("dm-double-kick", "Double-kick vocabulary", "dm-c-rhythm", 2, ["dm-blast"], "Two feet as a subdivision engine."),
        concept("dm-dm-displacement", "Rhythmic displacement", "dm-c-rhythm", 3, ["dm-riff-cell", "mus-displacement"], "The same cell, started on a different beat of the bar."),
        concept("dm-odd-meter", "Odd meter in death metal", "dm-c-rhythm", 3, ["dm-riff-cell", "mus-odd-meter"], "Groupings that are felt, not counted out loud."),
        concept("dm-polymeter-dm", "Polymeter in the band", "dm-c-rhythm", 4, ["dm-odd-meter", "mus-polymeter"], "Guitar in 3, kit in 4, a coincidence later."),
        concept("dm-string-skip", "String skipping and wide intervals", "dm-c-rhythm", 3, ["dm-riff-cell"], "Leaps that refuse stepwise comfort."),
        concept("dm-sweep-function", "Sweeps as function, not sport", "dm-c-rhythm", 3, ["dm-harmony"], "An arpeggio that has a harmonic job."),
        concept("dm-song-form", "Song structure", "dm-c-form", 2, ["dm-riff-cell"], "Intro, riff A, riff B, return — or a through-composed stack."),
        concept("dm-riff-form", "Riff as form", "dm-c-form", 3, ["dm-song-form", "mus-form-riff"], "The form is the order of cells and their mutations."),
        concept("dm-breakdown-dm", "Breakdowns and whether they belong", "dm-c-form", 2, ["dm-song-form"], "Half-time weight as contrast, or as a different genre arriving."),
        concept("dm-vocal-rhythm", "Vocals as a rhythmic instrument", "dm-c-form", 2, ["dm-blast", "dm-song-form"], "Phrasing against the kick, not a melody sitting on top."),
        concept("dm-harmony-two-gtr", "Two-guitar writing", "dm-c-form", 3, ["dm-harmony", "mus-voice-lead"], "Unison, harmony a third above, or a second riff."),
      ],
    },

    {
      id: "dm-advanced",
      title: "Technical, Progressive, and Stylistic Analysis",
      categoryId: "death-metal",
      description:
        "Technicality versus function, progressive and dissonant composition, and a method for analyzing tracks and scenes without collapsing into trivia.",
      curriculumVersion: 1,
      orderHint: 2,
      difficultyRange: [3, 5],
      entryRequirements: ["dm-harmony", "dm-riff-cell", "dm-blast", "mus-analysis-method"],
      sourceReferences: [
        {
          id: "mit-21m350",
          title: "MIT 21M.350 Musical Analysis",
          url: "https://ocw.mit.edu/courses/21m-350-musical-analysis-spring-2008/pages/syllabus/",
          kind: "ocw",
          notes: "Reuse the analysis method on this repertoire. The questions stay: what repeats, what contrasts, what is the cell.",
        },
        {
          id: "mit-metal101",
          title: "MIT Heavy Metal 101",
          url: "https://ocw.mit.edu/courses/res-21m-001-heavy-metal-101-january-iap-2025/",
          kind: "ocw",
          notes: "Culture and listening as analysis inputs, not a substitute for construction.",
        },
        {
          id: "berklee-metal",
          title: "Berklee Metal Guitar",
          url: "https://online.berklee.edu/courses/metal-guitar",
          kind: "syllabus",
          notes: "Technique remains a means. This course asks when technique is the piece and when it is noise.",
        },
      ],
      modules: [
        {
          id: "dm-a-tech",
          title: "Technicality",
          blurb: "When density is a choice.",
          order: 0,
          prerequisites: [],
          spineIds: ["dm-tech-vs-func"],
        },
        {
          id: "dm-a-prog",
          title: "Progressive and dissonant",
          blurb: "Long form, cold harmony.",
          order: 1,
          prerequisites: ["dm-a-tech"],
          spineIds: ["dm-prog-form", "dm-dissonant-comp"],
        },
        {
          id: "dm-a-style",
          title: "Stylistic analysis",
          blurb: "A method for a track, a scene, a mix.",
          order: 2,
          prerequisites: ["dm-a-prog"],
          spineIds: ["dm-analysis-riff", "dm-analysis-tune"],
        },
      ],
      concepts: [
        concept("dm-tech-vs-func", "Technicality versus musical function", "dm-a-tech", 3, ["dm-harmony", "dm-riff-cell"], "A hard part that does a job versus a hard part that is the point."),
        concept("dm-virtuosity", "Virtuosity as a risk", "dm-a-tech", 3, ["dm-tech-vs-func"], "Speed that erases the cell you were supposed to hear."),
        concept("dm-odd-phrasing", "Phrasing across barlines", "dm-a-tech", 4, ["dm-odd-meter", "dm-riffs-as-breath"], "A phrase that does not respect the bar the kit is in."),
        concept("dm-riffs-as-breath", "Breath and the riff", "dm-a-tech", 3, ["dm-riff-cell"], "Where a player would breathe is where the cell usually turns."),
        concept("dm-polyrhythm-dm", "Polyrhythm in the kit", "dm-a-tech", 4, ["dm-blast-types", "mus-hemiola"], "Hands and feet in different subdivisions."),
        concept("dm-contrast", "Contrast as the real technical move", "dm-a-tech", 3, ["dm-song-form"], "A slow riff after a blast is harder to write than another blast."),
        concept("dm-prog-form", "Progressive long form", "dm-a-prog", 4, ["dm-riff-form", "dm-prog-hist"], "Sections that develop instead of returning on schedule."),
        concept("dm-dissonant-comp", "Dissonant composition", "dm-a-prog", 4, ["dm-harmony", "mus-dissonant-voicing", "dm-dissonant-hist"], "Clash as the material, not the spice."),
        concept("dm-atonal-gesture", "Atonal gesture versus atonal system", "dm-a-prog", 4, ["dm-dissonant-comp"], "A lick that avoids a tonic is not twelve-tone technique."),
        concept("dm-metric-mod", "Metric modulation", "dm-a-prog", 4, ["dm-odd-meter"], "The old subdivision becomes the new pulse."),
        concept("dm-motif", "Motivic development in extreme music", "dm-a-prog", 3, ["dm-riff-cell", "mus-analysis-method"], "The cell comes back altered. That is the piece."),
        concept("dm-cliche", "Cliché versus vocabulary", "dm-a-prog", 3, ["dm-harmony"], "A diminished run that means something versus one that fills a bar."),
        concept("dm-analysis-riff", "Analyzing a riff", "dm-a-style", 3, ["mus-analysis-method", "dm-riff-cell"], "Pitch collection, cell, meter, where it sits in the form."),
        concept("dm-analysis-tune", "Analyzing a track", "dm-a-style", 4, ["dm-analysis-riff", "dm-song-form"], "The whole cut: contrast, density, production, vocal as rhythm."),
        concept("dm-compare-scenes", "Comparative scene analysis", "dm-a-style", 3, ["dm-production-doctrine", "dm-analysis-tune"], "Same year, two cities, two answers to the same problem."),
        concept("dm-production-listen", "Hearing the production doctrine", "dm-a-style", 3, ["dm-production-doctrine"], "Gate, room, guitar width, kick click — as compositional choices."),
        concept("dm-drum-comp", "Drum composition, not drum sport", "dm-a-style", 3, ["dm-blast-types"], "The kit writes form with texture changes."),
        concept("dm-bass-role", "Bass as lock, pick, or smear", "dm-a-style", 3, ["dm-harmony-two-gtr"], "Unison with the guitar, a picked counter-line, or a distorted bed."),
        concept("dm-arrangement", "Arrangement in a dense mix", "dm-a-style", 3, ["dm-analysis-tune"], "Who drops out so the next riff can be heard."),
        concept("dm-influence-map", "Influence as construction", "dm-a-style", 3, ["dm-compare-scenes"], "A borrowed cell, not a borrowed biography."),
        concept("dm-live-vs-record", "Live density versus record density", "dm-a-style", 3, ["dm-production-listen"], "What a three-piece can actually play."),
        concept("dm-modern-prod", "Modern trigger and edit production", "dm-a-style", 4, ["dm-production-listen", "dm-modern-wave"], "A grid that can erase the performance or reveal it."),
        concept("dm-notation-limit", "Why tablature lies about this music", "dm-a-style", 3, ["dm-analysis-riff", "mus-notation"], "Tab shows frets. It hides meter, cell, and function."),
      ],
    },
  ];
}
