/**
 * Operating systems, networking, compilers.
 * Authoring only — runtime loads the generated JSON.
 */
export function kernelCourses(concept) {
  return [
    {
      id: "os-foundations",
      title: "Operating Systems Foundations",
      categoryId: "os",
      description: "Kernel, syscalls, processes, and isolation — the contract between program and machine, taught the xv6 way: small enough to hold.",
      curriculumVersion: 1,
      orderHint: 0,
      difficultyRange: [0, 2],
      entryRequirements: [],
      sourceReferences: [
        { id: "mit-61810", title: "MIT 6.1810 Operating System Engineering", url: "https://ocw.mit.edu/courses/6-1810-operating-system-engineering-fall-2023/pages/syllabus/", kind: "ocw", notes: "Hardware/software contract first. xv6 as a complete small Unix." },
        { id: "mit-xv6", title: "xv6 book", url: "https://pdos.csail.mit.edu/6.1810/2025/xv6.html", kind: "notes", notes: "Organization, traps, isolation before locks and filesystems." },
      ],
      modules: [
        { id: "os-f-kernel", title: "The kernel as a program", blurb: "Privilege, traps, syscalls.", order: 0, prerequisites: [], spineIds: ["os-kernel", "os-syscall"] },
        { id: "os-f-proc", title: "Processes", blurb: "Address spaces, fork, isolation.", order: 1, prerequisites: ["os-f-kernel"], spineIds: ["os-process"] },
        { id: "os-f-switch", title: "Leaving and returning", blurb: "Interrupts, context switch, devices at a glance.", order: 2, prerequisites: ["os-f-proc"], spineIds: ["os-context-switch"] },
      ],
      concepts: [
        concept("os-kernel", "The kernel", "os-f-kernel", 0, [], "The program that owns the machine and rents it out."),
        concept("os-privilege", "Privilege rings", "os-f-kernel", 1, ["os-kernel"], "User code that cannot issue the dangerous instructions."),
        concept("os-syscall", "System calls", "os-f-kernel", 1, ["os-kernel"], "The narrow door a process uses to ask for work."),
        concept("os-trap", "Traps and exceptions", "os-f-kernel", 1, ["os-syscall"], "How control transfers into the kernel without a CALL."),
        concept("os-user-kernel", "User versus kernel memory", "os-f-kernel", 1, ["os-privilege"], "Two maps, one CPU, a lot of checking."),
        concept("os-abi", "The syscall ABI", "os-f-kernel", 2, ["os-syscall"], "Registers, numbers, and the compatibility tax."),
        concept("os-xv6-map", "A small Unix as a map", "os-f-kernel", 1, ["os-kernel"], "xv6 as a complete system you can finish reading."),
        concept("os-boot", "Booting", "os-f-kernel", 2, ["os-kernel"], "From reset vector to the first process."),
        concept("os-process", "Processes and threads", "os-f-proc", 1, ["os-kernel"], "Address spaces, threads, and what isolation actually costs."),
        concept("os-thread-vs-proc", "Threads versus processes", "os-f-proc", 1, ["os-process"], "Shared address space versus a private one."),
        concept("os-isolation", "Isolation", "os-f-proc", 1, ["os-process", "os-privilege"], "A crash next door should be someone else's problem."),
        concept("os-fork", "fork", "os-f-proc", 2, ["os-process"], "Copy the process, then diverge."),
        concept("os-exec", "exec", "os-f-proc", 2, ["os-fork"], "Replace the address space, keep the process id."),
        concept("os-wait", "wait", "os-f-proc", 2, ["os-fork"], "Reaping children so they do not stay zombies."),
        concept("os-shell", "The shell as a user of the API", "os-f-proc", 2, ["os-exec", "os-wait"], "A loop of fork, exec, wait that invents scripting."),
        concept("os-protection", "Protection domains", "os-f-proc", 2, ["os-isolation"], "Who may touch which object."),
        concept("os-monolithic-vs-micro", "Kernel structure", "os-f-proc", 2, ["os-kernel"], "Monoliths, microkernels, and the argument about where the driver lives."),
        concept("os-context-switch", "Context switches", "os-f-switch", 2, ["os-process"], "Saving one life and restoring another."),
        concept("os-interrupt", "Interrupts", "os-f-switch", 2, ["os-trap"], "The device rings; the kernel answers."),
        concept("os-device-intro", "Devices as files of a sort", "os-f-switch", 2, ["os-interrupt"], "A register file on the other side of a bus."),
        concept("os-ipc-intro", "IPC, first look", "os-f-switch", 2, ["os-process"], "Pipes and messages before shared-memory races."),
        concept("os-batch-vs-time", "Batch, multiprogramming, time-share", "os-f-switch", 1, ["os-process"], "Why we started switching at all."),
      ],
    },
    {
      id: "os-concurrency",
      title: "Memory, Concurrency, and Scheduling",
      categoryId: "os",
      description: "Page tables, the TLB, locks, races, and the scheduler that lies about how many CPUs you have.",
      curriculumVersion: 1,
      orderHint: 1,
      difficultyRange: [2, 4],
      entryRequirements: ["os-process", "os-syscall"],
      sourceReferences: [
        { id: "mit-xv6", title: "xv6 book", url: "https://pdos.csail.mit.edu/6.1810/2025/xv6.html", kind: "notes", notes: "Page tables, then locks, then scheduling." },
        { id: "mit-61810", title: "MIT 6.1810", url: "https://ocw.mit.edu/courses/6-1810-operating-system-engineering-fall-2023/pages/syllabus/", kind: "ocw", notes: "Labs extend VM and concurrency after the kernel is thinkable." },
      ],
      modules: [
        { id: "os-c-vm", title: "Virtual memory", blurb: "Pages, tables, faults.", order: 0, prerequisites: [], spineIds: ["os-vm"] },
        { id: "os-c-sched", title: "Scheduling", blurb: "Fairness, latency, and classes.", order: 1, prerequisites: ["os-c-vm"], spineIds: ["os-sched"] },
        { id: "os-c-sync", title: "Synchronization", blurb: "Locks, races, atomics.", order: 2, prerequisites: ["os-c-sched"], spineIds: ["os-lock", "os-race"] },
      ],
      concepts: [
        concept("os-vm", "Virtual memory", "os-c-vm", 2, ["os-process"], "Pages, page tables, and the TLB as a cache of translations."),
        concept("os-page-table", "Page tables", "os-c-vm", 2, ["os-vm"], "A tree of translations the hardware walks.", { parent: "os-vm" }),
        concept("os-tlb-os", "TLB shootdown", "os-c-vm", 3, ["os-vm", "cpu-tlb"], "When one core changes a mapping, the others must forget."),
        concept("os-page-fault", "Page faults", "os-c-vm", 2, ["os-vm", "os-trap"], "A missing translation as a request, not only a crash."),
        concept("os-swap", "Paging to disk", "os-c-vm", 3, ["os-page-fault"], "The illusion of more RAM than you bought."),
        concept("os-cow", "Copy-on-write", "os-c-vm", 3, ["os-fork", "os-page-fault"], "fork that does not copy until a write."),
        concept("os-mmap", "mmap", "os-c-vm", 3, ["os-vm"], "A file, or anonymous memory, appearing as a range of addresses."),
        concept("os-sched", "CPU scheduling", "os-c-sched", 2, ["os-process"], "Fairness, latency, and why CFS is not a real-time scheduler."),
        concept("os-fairness", "Fair-share scheduling", "os-c-sched", 3, ["os-sched"], "Who is owed the next slice."),
        concept("os-latency-sched", "Latency versus throughput in the scheduler", "os-c-sched", 3, ["os-sched", "arch-latency-throughput"], "Interactive tails versus batch work."),
        concept("os-realtime", "Real-time scheduling", "os-c-sched", 4, ["os-sched"], "Deadlines, not averages."),
        concept("os-scheduler-class", "Scheduling classes", "os-c-sched", 3, ["os-sched"], "More than one policy living in one kernel."),
        concept("os-load-balance", "Load balancing", "os-c-sched", 3, ["os-sched"], "Moving work across cores without wrecking caches."),
        concept("os-numa", "NUMA awareness", "os-c-sched", 4, ["os-load-balance", "os-vm"], "Memory that is closer to some cores than others."),
        concept("os-preempt", "Preemption", "os-c-sched", 2, ["os-context-switch", "os-sched"], "Taking the CPU back."),
        concept("os-priority-inv", "Priority inversion", "os-c-sched", 4, ["os-sched", "os-lock"], "A low task holding a lock a high task needs."),
        concept("os-lock", "Locks", "os-c-sync", 2, ["os-process"], "Mutual exclusion as a primitive, not a vibe."),
        concept("os-sleep-lock", "Sleeping locks", "os-c-sync", 3, ["os-lock"], "Blocking instead of spinning when the hold is long."),
        concept("os-deadlock", "Deadlock", "os-c-sync", 3, ["os-lock"], "Everyone waiting for someone who is waiting for them."),
        concept("os-race", "Races", "os-c-sync", 2, ["os-thread-vs-proc"], "A result that depends on who ran first."),
        concept("os-atomic", "Atomics", "os-c-sync", 3, ["os-race"], "Read-modify-write that does not tear."),
        concept("os-seqcst", "Memory ordering for programmers", "os-c-sync", 4, ["os-atomic", "cpu-consistency"], "Why a store on this core is not yet a load on that one."),
        concept("os-semaphore", "Semaphores", "os-c-sync", 3, ["os-lock"], "A counter you can wait on."),
        concept("os-condvar", "Condition variables", "os-c-sync", 3, ["os-sleep-lock"], "Sleep until someone says the world changed."),
      ],
    },
    {
      id: "os-storage",
      title: "Storage, Filesystems, and Kernel Internals",
      categoryId: "os",
      description: "Persistence after virtualization: blocks, inodes, journals, drivers, and the namespaces containers actually use.",
      curriculumVersion: 1,
      orderHint: 2,
      difficultyRange: [2, 5],
      entryRequirements: ["os-vm", "os-lock"],
      sourceReferences: [
        { id: "mit-xv6", title: "xv6 book", url: "https://pdos.csail.mit.edu/6.1810/2025/xv6.html", kind: "notes", notes: "File system after locks. Crash consistency is the hard part." },
        { id: "mit-61810", title: "MIT 6.1810", url: "https://ocw.mit.edu/courses/6-1810-operating-system-engineering-fall-2023/pages/syllabus/", kind: "ocw", notes: "Labs add sophisticated VM and networking onto a known kernel." },
      ],
      modules: [
        { id: "os-s-fs", title: "Filesystems", blurb: "Inodes, directories, journals.", order: 0, prerequisites: [], spineIds: ["os-inode", "os-journal"] },
        { id: "os-s-io", title: "I/O path", blurb: "Caches, DMA, drivers.", order: 1, prerequisites: ["os-s-fs"], spineIds: ["os-buffer-cache", "os-driver"] },
        { id: "os-s-isol", title: "Modern isolation extras", blurb: "Namespaces, cgroups, virtualization.", order: 2, prerequisites: ["os-s-io"], spineIds: ["os-namespace", "os-container"] },
      ],
      concepts: [
        concept("os-block-dev", "Block devices", "os-s-fs", 2, ["os-device-intro"], "Fixed-size sectors and the fiction of a linear disk."),
        concept("os-inode", "Inodes", "os-s-fs", 2, ["os-block-dev"], "The on-disk object a filename eventually names."),
        concept("os-dir", "Directories", "os-s-fs", 2, ["os-inode"], "A list of names to inode numbers."),
        concept("os-fs-layout", "Filesystem layout", "os-s-fs", 3, ["os-inode"], "Superblock, bitmaps, and where the data lives."),
        concept("os-journal", "Journaling", "os-s-fs", 3, ["os-fs-layout"], "Write the intent before the damage."),
        concept("os-crash-consist", "Crash consistency", "os-s-fs", 4, ["os-journal"], "A power cut in the middle of rename."),
        concept("os-vfs", "The VFS", "os-s-fs", 3, ["os-inode"], "One API over many filesystem types."),
        concept("os-mount", "Mounts", "os-s-fs", 3, ["os-vfs"], "Grafting a tree onto a directory."),
        concept("os-buffer-cache", "Buffer cache", "os-s-io", 3, ["os-block-dev"], "Recently used blocks kept in RAM."),
        concept("os-page-cache", "Page cache", "os-s-io", 3, ["os-mmap", "os-buffer-cache"], "File contents as pages, not just blocks."),
        concept("os-dma", "DMA", "os-s-io", 3, ["os-device-intro"], "The device writes memory while the CPU does something else."),
        concept("os-driver", "Device drivers", "os-s-io", 3, ["os-interrupt", "os-dma"], "The kernel code that speaks a particular device's dialect."),
        concept("os-virtio", "Virtio", "os-s-io", 4, ["os-driver"], "A device model designed to be virtualized."),
        concept("os-init", "init and userspace bring-up", "os-s-io", 2, ["os-exec"], "The first process and everything it starts."),
        concept("os-namespace", "Namespaces", "os-s-isol", 3, ["os-isolation"], "A process that cannot see the whole machine."),
        concept("os-namespace-linux", "Linux namespace types", "os-s-isol", 4, ["os-namespace"], "PID, mount, net, user — different lies."),
        concept("os-cgroup", "cgroups", "os-s-isol", 4, ["os-sched"], "Accounting and limits on CPU, memory, I/O."),
        concept("os-capability", "Capabilities", "os-s-isol", 4, ["os-privilege"], "Splitting root into bits you can drop."),
        concept("os-seccomp", "seccomp", "os-s-isol", 4, ["os-syscall"], "A filter on which syscalls remain legal."),
        concept("os-syscall-filter", "Reducing the syscall surface", "os-s-isol", 4, ["os-seccomp"], "Why a sandboxed process still needs open(2)."),
        concept("os-kvm-intro", "KVM at a glance", "os-s-isol", 4, ["os-privilege", "cpu-virtual-addr"], "The kernel as a hypervisor for other kernels."),
        concept("os-container", "Containers", "os-s-isol", 4, ["os-namespace", "os-cgroup"], "Namespaces plus cgroups plus a filesystem view — not a VM."),
      ],
    },
    {
      id: "net-foundations",
      title: "Networking Foundations",
      categoryId: "networking",
      description: "Packets, layers as contracts, Ethernet, IP, and the socket a program actually sees. Routing politics wait.",
      curriculumVersion: 1,
      orderHint: 0,
      difficultyRange: [0, 2],
      entryRequirements: [],
      sourceReferences: [
        { id: "stanford-cs144", title: "Stanford CS144", url: "https://web.stanford.edu/class/cs144/", kind: "syllabus", notes: "Packets and a reliable byte stream before BGP. Layers as implementation contracts." },
      ],
      modules: [
        { id: "net-f-pack", title: "Packets and layers", blurb: "Why we slice the problem.", order: 0, prerequisites: [], spineIds: ["net-stack", "net-packet"] },
        { id: "net-f-link", title: "Link and local delivery", blurb: "MAC, switching, ARP.", order: 1, prerequisites: ["net-f-pack"], spineIds: ["net-ethernet"] },
        { id: "net-f-ip", title: "Internet Protocol", blurb: "Addresses, CIDR, ICMP.", order: 2, prerequisites: ["net-f-link"], spineIds: ["net-ip"] },
        { id: "net-f-host", title: "The host interface", blurb: "Sockets, UDP, names.", order: 3, prerequisites: ["net-f-ip"], spineIds: ["net-socket-api"] },
      ],
      concepts: [
        concept("net-stack", "The network stack", "net-f-pack", 0, [], "Layers as contracts, not a morality play."),
        concept("net-packet", "Packets", "net-f-pack", 0, ["net-stack"], "A header plus a payload, lost independently of its neighbors."),
        concept("net-layering", "Why layering", "net-f-pack", 1, ["net-stack"], "Each layer offers a service and hides a mechanism."),
        concept("net-end-to-end", "The end-to-end argument", "net-f-pack", 2, ["net-layering"], "Functions that only the endpoints can implement correctly."),
        concept("net-bandwidth-delay", "Bandwidth-delay product", "net-f-pack", 2, ["net-packet", "arch-latency-throughput"], "How much data fits in the pipe."),
        concept("net-ethernet", "Ethernet frames", "net-f-link", 1, ["net-packet"], "A local delivery envelope with a MAC address."),
        concept("net-mac", "MAC addresses", "net-f-link", 1, ["net-ethernet"], "A burned-in name that is not an Internet name."),
        concept("net-switching", "Switching", "net-f-link", 2, ["net-ethernet"], "Learning which port a MAC last spoke from."),
        concept("net-arp", "ARP", "net-f-link", 2, ["net-mac"], "Who has this IP? Tell this MAC."),
        concept("net-wifi-vs-wired", "Shared versus switched media", "net-f-link", 2, ["net-ethernet"], "Collision domains did not vanish; they moved."),
        concept("net-ip", "IPv4 addressing", "net-f-ip", 1, ["net-packet"], "A hierarchical name the routers understand."),
        concept("net-cidr", "CIDR and prefixes", "net-f-ip", 2, ["net-ip"], "A length, not a class."),
        concept("net-icmp", "ICMP", "net-f-ip", 2, ["net-ip"], "Control messages: unreachable, too big, echo."),
        concept("net-mtu", "MTU", "net-f-ip", 2, ["net-ip"], "The largest packet this hop will accept."),
        concept("net-fragment", "Fragmentation", "net-f-ip", 3, ["net-mtu"], "Splitting a packet the next link will not take — and why we try not to."),
        concept("net-nat-intro", "NAT, first look", "net-f-ip", 2, ["net-ip"], "Many private addresses sharing one public one."),
        concept("net-endian-wire", "Network byte order", "net-f-ip", 1, ["net-packet", "cpu-endian"], "Big-endian on the wire, whatever you are at home."),
        concept("net-checksum", "Checksums", "net-f-ip", 2, ["net-packet"], "A cheap detector, not a cryptographic proof."),
        concept("net-udp", "UDP", "net-f-host", 1, ["net-ip"], "A port number and a hope."),
        concept("net-socket-api", "The socket API", "net-f-host", 1, ["net-udp"], "How a process binds a port and exchanges bytes."),
        concept("net-dns-intro", "DNS, first look", "net-f-host", 2, ["net-udp"], "Names that resolve to addresses."),
        concept("net-dhcp", "DHCP", "net-f-host", 2, ["net-ip"], "Borrowing an address for a while."),
      ],
    },
    {
      id: "net-transport",
      title: "Transport and Congestion",
      categoryId: "networking",
      description: "Reliability, windows, and how senders share a pipe they cannot see. TCP first; QUIC as a later design that learned the same lessons.",
      curriculumVersion: 1,
      orderHint: 1,
      difficultyRange: [2, 4],
      entryRequirements: ["net-ip", "net-socket-api"],
      sourceReferences: [
        { id: "stanford-cs144", title: "Stanford CS144", url: "https://web.stanford.edu/class/cs144/", kind: "syllabus", notes: "Labs build a reliable transport. Congestion is a mechanism, not a slogan." },
      ],
      modules: [
        { id: "net-t-rel", title: "Reliability", blurb: "Acks, windows, state.", order: 0, prerequisites: [], spineIds: ["net-reliable", "net-tcp-state"] },
        { id: "net-t-cc", title: "Congestion control", blurb: "AIMD, RTT, the unseen pipe.", order: 1, prerequisites: ["net-t-rel"], spineIds: ["net-congestion"] },
        { id: "net-t-mod", title: "Modern transports", blurb: "Bufferbloat, BBR, QUIC.", order: 2, prerequisites: ["net-t-cc"], spineIds: ["net-bbr", "net-quic"] },
      ],
      concepts: [
        concept("net-reliable", "Reliable delivery", "net-t-rel", 2, ["net-udp"], "Retransmit what was lost, in order, exactly once — approximately."),
        concept("net-tcp-state", "TCP state machine", "net-t-rel", 2, ["net-reliable"], "LISTEN to TIME_WAIT as a protocol, not a diagram to memorize."),
        concept("net-handshake", "The handshake", "net-t-rel", 2, ["net-tcp-state"], "Three packets to agree a starting sequence."),
        concept("net-sliding-window", "Sliding windows", "net-t-rel", 3, ["net-reliable", "net-bandwidth-delay"], "Many packets in flight, one window to bound them."),
        concept("net-flow-control", "Flow control", "net-t-rel", 3, ["net-sliding-window"], "The receiver advertising how much it can still take."),
        concept("net-timeout", "Retransmit timers", "net-t-rel", 3, ["net-reliable"], "When silence means loss."),
        concept("net-fast-retransmit", "Fast retransmit", "net-t-rel", 3, ["net-timeout"], "Triple-duplicate ACK as an earlier hint than a timeout."),
        concept("net-nagle", "Nagle and delayed ACK", "net-t-rel", 3, ["net-tcp-state"], "Two optimizations that deadlock each other."),
        concept("net-keepalive", "Keepalives", "net-t-rel", 2, ["net-tcp-state"], "Probing a quiet connection so middleboxes do not forget it."),
        concept("net-congestion", "Congestion control", "net-t-cc", 2, ["net-stack"], "How senders share a pipe they cannot see."),
        concept("net-aimd", "AIMD", "net-t-cc", 3, ["net-congestion"], "Additive increase, multiplicative decrease — fairness from a rule."),
        concept("net-slow-start", "Slow start", "net-t-cc", 3, ["net-aimd"], "Exponential probing until you hit something."),
        concept("net-rtt", "RTT estimation", "net-t-cc", 3, ["net-timeout"], "Jacobson/Karels: the mean is not enough; you need the variance."),
        concept("net-fairness-tcp", "TCP fairness", "net-t-cc", 3, ["net-aimd"], "Equal shares among equal RTTs — and the bias when they are not."),
        concept("net-head-of-line", "Head-of-line blocking", "net-t-cc", 3, ["net-reliable"], "One lost packet stalling the streams behind it."),
        concept("net-bufferbloat", "Bufferbloat", "net-t-mod", 3, ["net-congestion"], "Huge buffers turning loss into delay."),
        concept("net-ecn", "Explicit congestion notification", "net-t-mod", 4, ["net-congestion"], "Marking instead of dropping."),
        concept("net-bbr", "Delay-based control (BBR)", "net-t-mod", 4, ["net-congestion", "net-bandwidth-delay"], "Model the pipe instead of waiting for a drop."),
        concept("net-quic", "QUIC", "net-t-mod", 4, ["net-udp", "net-head-of-line"], "Transport over UDP so we can change it without the kernel."),
        concept("net-tls-place", "Where TLS sits", "net-t-mod", 3, ["net-tcp-state"], "Encryption as a layer, and why QUIC ate it."),
        concept("net-udp-use", "When UDP is the right tool", "net-t-mod", 3, ["net-udp", "net-congestion"], "Media, games, and anything that would rather drop than stall."),
        concept("net-middlebox", "Middleboxes", "net-t-mod", 4, ["net-nat-intro", "net-tcp-state"], "The path is not just routers. It rewrites you."),
      ],
    },
    {
      id: "net-internet",
      title: "Routing and Internet Architecture",
      categoryId: "networking",
      description: "How packets find a path across independently owned networks: prefixes, IGPs, BGP, peering, and the failures that are political.",
      curriculumVersion: 1,
      orderHint: 2,
      difficultyRange: [3, 5],
      entryRequirements: ["net-cidr", "net-ip"],
      sourceReferences: [
        { id: "stanford-cs144", title: "Stanford CS144", url: "https://web.stanford.edu/class/cs144/", kind: "syllabus", notes: "Internet architecture after a working transport. BGP is policy, not a shortest-path toy." },
      ],
      modules: [
        { id: "net-i-fwd", title: "Forwarding", blurb: "Longest prefix, tables.", order: 0, prerequisites: [], spineIds: ["net-forwarding-vs-routing"] },
        { id: "net-i-igp", title: "Inside an AS", blurb: "IGPs, OSPF.", order: 1, prerequisites: ["net-i-fwd"], spineIds: ["net-igp"] },
        { id: "net-i-bgp", title: "Between ASes", blurb: "BGP, peering, hijacks.", order: 2, prerequisites: ["net-i-igp"], spineIds: ["net-bgp"] },
        { id: "net-i-sys", title: "The system around it", blurb: "DNS, anycast, CDN, IPv6.", order: 3, prerequisites: ["net-i-bgp"], spineIds: ["net-dns-system", "net-anycast"] },
      ],
      concepts: [
        concept("net-forwarding-vs-routing", "Forwarding versus routing", "net-i-fwd", 3, ["net-cidr"], "The lookup in the datapath versus the process that filled the table."),
        concept("net-longest-prefix", "Longest-prefix match", "net-i-fwd", 3, ["net-forwarding-vs-routing"], "More specific wins."),
        concept("net-as", "Autonomous systems", "net-i-igp", 3, ["net-ip"], "A network with one routing policy."),
        concept("net-igp", "Interior gateway protocols", "net-i-igp", 3, ["net-as"], "How an AS talks to itself."),
        concept("net-ospf", "Link-state routing (OSPF)", "net-i-igp", 4, ["net-igp"], "Everyone floods the map, then runs shortest path."),
        concept("net-bgp", "BGP", "net-i-bgp", 3, ["net-stack"], "Policy routing between autonomous systems."),
        concept("net-peering", "Peering", "net-i-bgp", 4, ["net-bgp"], "Settlement-free exchange, until it is not."),
        concept("net-transit", "Transit", "net-i-bgp", 4, ["net-bgp"], "Paying someone to reach the rest of the Internet."),
        concept("net-ixp", "Internet exchange points", "net-i-bgp", 4, ["net-peering"], "A room where many ASes meet."),
        concept("net-policy-route", "Policy in the path", "net-i-bgp", 4, ["net-bgp"], "Local preference and AS-path as politics encoded in attributes."),
        concept("net-hijack", "Route hijacks", "net-i-bgp", 4, ["net-bgp"], "Announcing a prefix you do not own."),
        concept("net-rpki", "RPKI", "net-i-bgp", 5, ["net-hijack"], "Cryptographic permission to announce a prefix."),
        concept("net-dns-system", "The DNS as a system", "net-i-sys", 3, ["net-dns-intro"], "Hierarchy, caches, and the resolvers in the middle."),
        concept("net-anycast", "Anycast", "net-i-sys", 4, ["net-bgp"], "One address, many locations, routing decides which."),
        concept("net-anycast-dns", "Anycast DNS", "net-i-sys", 4, ["net-anycast", "net-dns-system"], "Why 8.8.8.8 is near everyone."),
        concept("net-cdn", "CDNs", "net-i-sys", 4, ["net-anycast", "net-dns-system"], "Putting the bytes next to the viewer."),
        concept("net-ipv6", "IPv6", "net-i-sys", 3, ["net-ip"], "Larger addresses and a different neighbor-discovery story."),
        concept("net-mpls", "MPLS", "net-i-sys", 4, ["net-forwarding-vs-routing"], "Labels instead of IP lookups in the core."),
        concept("net-sdn", "Software-defined control", "net-i-sys", 4, ["net-forwarding-vs-routing"], "A logically centralized controller filling the tables."),
        concept("net-measurement", "Measuring the Internet", "net-i-sys", 4, ["net-icmp", "net-bgp"], "Traceroute lies, and we use it anyway."),
        concept("net-anycast-http", "Anycast at L7", "net-i-sys", 4, ["net-cdn"], "When the TCP connection and the HTTP cache disagree about where you are."),
        concept("net-anycast-bgp", "BGP and anycast interaction", "net-i-sys", 5, ["net-anycast", "net-policy-route"], "A more-specific prefix pulling traffic across an ocean."),
      ],
    },
    {
      id: "cmp-frontend",
      title: "Compiler Front-End",
      categoryId: "compilers",
      description: "From characters to a typed tree: lexing, parsing, names, and the errors a compiler owes the human.",
      curriculumVersion: 1,
      orderHint: 0,
      difficultyRange: [0, 3],
      entryRequirements: [],
      sourceReferences: [
        { id: "stanford-cs143", title: "Stanford CS143 Compilers", url: "https://web.stanford.edu/class/cs143/", kind: "syllabus", notes: "Lex, parse, semantic analysis as the first project phases. Optimization waits." },
      ],
      modules: [
        { id: "cmp-fe-lex", title: "Lexical analysis", blurb: "Characters into tokens.", order: 0, prerequisites: [], spineIds: ["cmp-front"] },
        { id: "cmp-fe-parse", title: "Parsing", blurb: "Tokens into a tree.", order: 1, prerequisites: ["cmp-fe-lex"], spineIds: ["cmp-cfg", "cmp-ast"] },
        { id: "cmp-fe-sem", title: "Names and types", blurb: "The tree becomes honest.", order: 2, prerequisites: ["cmp-fe-parse"], spineIds: ["cmp-typecheck"] },
      ],
      concepts: [
        concept("cmp-front", "Lexing and parsing", "cmp-fe-lex", 0, [], "Turning characters into a tree the rest of the compiler can hate."),
        concept("cmp-token", "Tokens", "cmp-fe-lex", 1, ["cmp-front"], "The words of a programming language."),
        concept("cmp-regex-lex", "Regular lexers", "cmp-fe-lex", 1, ["cmp-token"], "Why identifiers are regular and expressions are not."),
        concept("cmp-source-loc", "Source locations", "cmp-fe-lex", 1, ["cmp-token"], "Every diagnostic needs a span."),
        concept("cmp-preproc", "Preprocessing", "cmp-fe-lex", 2, ["cmp-token"], "A language before the language."),
        concept("cmp-macro", "Macros", "cmp-fe-lex", 2, ["cmp-preproc"], "Expansion that later phases must still explain."),
        concept("cmp-cfg", "Context-free grammars", "cmp-fe-parse", 1, ["cmp-front"], "Recursive structure you can write down."),
        concept("cmp-parse-tree", "Parse trees", "cmp-fe-parse", 1, ["cmp-cfg"], "The derivation, including the punctuation."),
        concept("cmp-ast", "Abstract syntax trees", "cmp-fe-parse", 1, ["cmp-parse-tree"], "The tree you actually want to typecheck."),
        concept("cmp-recursive-descent", "Recursive descent", "cmp-fe-parse", 2, ["cmp-cfg"], "One function per nonterminal."),
        concept("cmp-lr", "Bottom-up parsing", "cmp-fe-parse", 2, ["cmp-cfg"], "Shift and reduce, and the tables that drive them."),
        concept("cmp-ambiguity", "Ambiguity", "cmp-fe-parse", 2, ["cmp-cfg"], "Two trees for one string."),
        concept("cmp-grammar-class", "LL versus LR", "cmp-fe-parse", 3, ["cmp-recursive-descent", "cmp-lr"], "What each algorithm will not swallow."),
        concept("cmp-semantic-action", "Semantic actions", "cmp-fe-parse", 2, ["cmp-ast"], "Building values while you parse."),
        concept("cmp-error-recovery", "Parse error recovery", "cmp-fe-parse", 3, ["cmp-recursive-descent"], "Reporting more than the first mistake."),
        concept("cmp-symbol-table", "Symbol tables", "cmp-fe-sem", 2, ["cmp-ast"], "A map from names to meanings, stacked by scope."),
        concept("cmp-scope", "Scope", "cmp-fe-sem", 2, ["cmp-symbol-table"], "Where a name is visible."),
        concept("cmp-name-resolve", "Name resolution", "cmp-fe-sem", 2, ["cmp-scope"], "Which declaration this use refers to."),
        concept("cmp-typecheck", "Type checking", "cmp-fe-sem", 2, ["cmp-name-resolve"], "Rejecting trees that cannot mean anything."),
        concept("cmp-overload", "Overload resolution", "cmp-fe-sem", 3, ["cmp-typecheck"], "Picking which f this f is."),
        concept("cmp-visitor", "Walking the tree", "cmp-fe-sem", 2, ["cmp-ast"], "Visitors and the passes that share them."),
        concept("cmp-ir-lower-intro", "Lowering, first look", "cmp-fe-sem", 3, ["cmp-typecheck"], "The typed tree is not yet something you can allocate registers for."),
      ],
    },
    {
      id: "cmp-ir",
      title: "Intermediate Representations and Optimisation",
      categoryId: "compilers",
      description: "SSA, dataflow, and the passes that change the program without changing what it means.",
      curriculumVersion: 1,
      orderHint: 1,
      difficultyRange: [2, 4],
      entryRequirements: ["cmp-typecheck", "cmp-ast"],
      sourceReferences: [
        { id: "stanford-cs143", title: "Stanford CS143", url: "https://web.stanford.edu/class/cs143/", kind: "syllabus", notes: "IR and local/global optimization after the front-end exists." },
        { id: "cmu-15411", title: "CMU 15-411/611 Compiler Design", url: "https://csd.cs.cmu.edu/15411611-compiler-design", kind: "syllabus", notes: "IR and dataflow as the intellectual center." },
      ],
      modules: [
        { id: "cmp-ir-form", title: "IR shapes", blurb: "Three-address, CFG, SSA.", order: 0, prerequisites: [], spineIds: ["cmp-ssa"] },
        { id: "cmp-ir-flow", title: "Dataflow", blurb: "Liveness and friends.", order: 1, prerequisites: ["cmp-ir-form"], spineIds: ["cmp-dataflow"] },
        { id: "cmp-ir-opt", title: "Transformations", blurb: "The useful rewrites.", order: 2, prerequisites: ["cmp-ir-flow"], spineIds: ["cmp-dce", "cmp-inlining"] },
      ],
      concepts: [
        concept("cmp-three-addr", "Three-address code", "cmp-ir-form", 2, ["cmp-ir-lower-intro"], "One operator, a few operands, easy to move."),
        concept("cmp-cfg-ir", "Control-flow graphs", "cmp-ir-form", 2, ["cmp-three-addr"], "Basic blocks and the edges between them."),
        concept("cmp-ssa", "SSA form", "cmp-ir-form", 2, ["cmp-front"], "Single assignment so dataflow becomes a graph problem."),
        concept("cmp-phi", "φ-nodes", "cmp-ir-form", 3, ["cmp-ssa", "cmp-cfg-ir"], "A merge of names at a join point."),
        concept("cmp-mem2reg", "Memory to registers", "cmp-ir-form", 3, ["cmp-ssa"], "Promoting allocas so SSA can see them."),
        concept("cmp-ir-verify", "IR verification", "cmp-ir-form", 3, ["cmp-ssa"], "Types and dominance as a checker, not a hope."),
        concept("cmp-dataflow", "Dataflow analysis", "cmp-ir-flow", 3, ["cmp-cfg-ir"], "Facts that flow forward or backward until they settle."),
        concept("cmp-liveness", "Liveness", "cmp-ir-flow", 3, ["cmp-dataflow"], "Which values are still needed."),
        concept("cmp-alias", "Alias analysis", "cmp-ir-flow", 4, ["cmp-dataflow"], "May these two pointers be the same."),
        concept("cmp-call-graph", "Call graphs", "cmp-ir-flow", 3, ["cmp-cfg-ir"], "Who might call whom."),
        concept("cmp-pass-manager", "Pass managers", "cmp-ir-flow", 3, ["cmp-ir-verify"], "Order, invalidation, and why passes fight."),
        concept("cmp-const-fold", "Constant folding", "cmp-ir-opt", 3, ["cmp-ssa"], "Doing arithmetic the compiler can already see."),
        concept("cmp-dce", "Dead code elimination", "cmp-ir-opt", 3, ["cmp-liveness"], "Deleting what nothing uses."),
        concept("cmp-cse", "Common-subexpression elimination", "cmp-ir-opt", 3, ["cmp-ssa"], "Computing a thing once."),
        concept("cmp-inlining", "Inlining", "cmp-ir-opt", 3, ["cmp-call-graph"], "Replacing a call with the body, for a price."),
        concept("cmp-loop-inv", "Loop-invariant code motion", "cmp-ir-opt", 4, ["cmp-cfg-ir"], "Hoisting work the loop does not change."),
        concept("cmp-licm", "LICM carefully", "cmp-ir-opt", 4, ["cmp-loop-inv", "cmp-alias"], "When a load is not actually invariant."),
        concept("cmp-strength-red", "Strength reduction", "cmp-ir-opt", 3, ["cmp-loop-inv"], "A multiply becoming an add."),
        concept("cmp-sroa", "Scalar replacement of aggregates", "cmp-ir-opt", 4, ["cmp-mem2reg"], "Exploding a struct into pieces SSA can eat."),
        concept("cmp-tailcall", "Tail calls", "cmp-ir-opt", 3, ["cmp-cfg-ir"], "A call that can be a jump."),
        concept("cmp-vectorize", "Vectorization", "cmp-ir-opt", 4, ["cmp-loop-inv", "cpu-vector-simd"], "One instruction, many loop iterations."),
        concept("cmp-ipo", "Interprocedural optimization", "cmp-ir-opt", 4, ["cmp-inlining", "cmp-call-graph"], "Facts that cross function boundaries."),
      ],
    },
    {
      id: "cmp-backend",
      title: "Code Generation and Runtime Systems",
      categoryId: "compilers",
      description: "Instruction selection, register allocation, ABIs, and the runtime that still exists after the compiler is done — including JIT.",
      curriculumVersion: 1,
      orderHint: 2,
      difficultyRange: [3, 5],
      entryRequirements: ["cmp-ssa", "cmp-liveness"],
      sourceReferences: [
        { id: "stanford-cs143", title: "Stanford CS143", url: "https://web.stanford.edu/class/cs143/", kind: "syllabus", notes: "Codegen, register allocation, GC, JIT as later phases." },
        { id: "cmu-15411", title: "CMU 15-411/611", url: "https://csd.cs.cmu.edu/15411611-compiler-design", kind: "syllabus", notes: "Instruction selection and the backend as first-class work." },
      ],
      modules: [
        { id: "cmp-be-sel", title: "Selection and allocation", blurb: "ISel, coloring, spilling.", order: 0, prerequisites: [], spineIds: ["cmp-alloc", "cmp-isel"] },
        { id: "cmp-be-abi", title: "Talking to the platform", blurb: "Calls, frames, objects.", order: 1, prerequisites: ["cmp-be-sel"], spineIds: ["cmp-abi-call"] },
        { id: "cmp-be-rt", title: "Runtimes and JITs", blurb: "GC, exceptions, dynamic compilation.", order: 2, prerequisites: ["cmp-be-abi"], spineIds: ["cmp-gc", "cmp-jit"] },
      ],
      concepts: [
        concept("cmp-isel", "Instruction selection", "cmp-be-sel", 3, ["cmp-three-addr"], "IR operators become real opcodes."),
        concept("cmp-alloc", "Register allocation", "cmp-be-sel", 3, ["cmp-ssa"], "Graph coloring, spilling, and the real cost of an extra live range."),
        concept("cmp-spill", "Spilling", "cmp-be-sel", 4, ["cmp-alloc", "cmp-liveness"], "A value that did not fit, living on the stack."),
        concept("cmp-scheduling", "Instruction scheduling", "cmp-be-sel", 4, ["cmp-isel", "cpu-pipeline"], "Reordering to hide latency without breaking dependences."),
        concept("cmp-peephole", "Peephole opts", "cmp-be-sel", 3, ["cmp-isel"], "Tiny local rewrites on the real ISA."),
        concept("cmp-abi-call", "Calling conventions", "cmp-be-abi", 3, ["cmp-isel", "cpu-isa"], "Which arguments live in which registers."),
        concept("cmp-frame", "Stack frames", "cmp-be-abi", 3, ["cmp-abi-call"], "The record a call leaves behind."),
        concept("cmp-object", "Object files", "cmp-be-abi", 3, ["cmp-isel"], "Sections, symbols, and what the linker will see."),
        concept("cmp-reloc", "Relocations", "cmp-be-abi", 3, ["cmp-object"], "Addresses the linker still has to fill in."),
        concept("cmp-linker", "Linking", "cmp-be-abi", 3, ["cmp-reloc"], "Many objects, one address space."),
        concept("cmp-pic", "Position-independent code", "cmp-be-abi", 4, ["cmp-reloc"], "Code that does not assume where it was loaded."),
        concept("cmp-tls", "Thread-local storage", "cmp-be-abi", 4, ["cmp-abi-call", "os-thread-vs-proc"], "A global that is not shared."),
        concept("cmp-debug-info", "Debug info", "cmp-be-abi", 3, ["cmp-source-loc"], "DWARF as a map back to the source the optimizer scrambled."),
        concept("cmp-runtime", "The language runtime", "cmp-be-rt", 3, ["cmp-abi-call"], "The support code every compiled program still links."),
        concept("cmp-gc", "Automatic memory management", "cmp-be-rt", 4, ["cmp-runtime"], "Finding the live objects without a free()."),
        concept("cmp-exception", "Exceptions", "cmp-be-rt", 4, ["cmp-frame"], "Unwinding until someone catches."),
        concept("cmp-unwinding", "Stack unwinding", "cmp-be-rt", 4, ["cmp-exception"], "Tables instead of a setjmp in every frame."),
        concept("cmp-stackmap", "Stack maps", "cmp-be-rt", 5, ["cmp-gc", "cmp-jit"], "Where the GC roots are at this safepoint."),
        concept("cmp-jit", "JIT compilation", "cmp-be-rt", 4, ["cmp-isel"], "Compiling while the program runs."),
        concept("cmp-deopt", "Deoptimization", "cmp-be-rt", 5, ["cmp-jit"], "Falling back when a speculative type was a lie."),
        concept("cmp-lto", "Link-time optimization", "cmp-be-rt", 4, ["cmp-ipo", "cmp-linker"], "Seeing the whole program after the .o files exist."),
        concept("cmp-pgo", "Profile-guided optimization", "cmp-be-rt", 4, ["cmp-inlining"], "Letting yesterday's run tell today's inliner the truth."),
      ],
    },
  ];
}
