/**
 * CPU, semiconductors, OS, networking, compilers.
 * Authoring only — runtime loads the generated JSON.
 */
export function technicalCourses(concept) {
  return [
    {
      id: "cpu-microarch",
      title: "Modern CPU Microarchitecture",
      categoryId: "cpu",
      description: "How a core finds independent work: prediction, renaming, out-of-order issue, and the memory system that has to stay honest across cores.",
      curriculumVersion: 1,
      orderHint: 1,
      difficultyRange: [2, 5],
      entryRequirements: ["cpu-pipeline", "cpu-hazards"],
      sourceReferences: [
        { id: "mit-6823", title: "MIT 6.823 Computer System Architecture", url: "https://ocw.mit.edu/courses/6-823-computer-system-architecture-fall-2005/pages/syllabus/", kind: "ocw", notes: "Superscalar/VLIW/vector/threads after ISA and caches. Multiprocessors and memory models last." },
        { id: "stanford-cs149", title: "Stanford CS149", url: "https://gfxcourses.stanford.edu/cs149/fall25/", kind: "syllabus", notes: "Coherence and consistency after the core is thinkable, not as GPU week-one." },
      ],
      modules: [
        { id: "cpu-m-pred", title: "Speculating control", blurb: "Prediction so the pipeline stays full.", order: 0, prerequisites: [], spineIds: ["cpu-branch-prediction"], learningObjectives: ["Separate direction from target", "Say what a mispredict costs"] },
        { id: "cpu-m-ooo", title: "Renaming and out-of-order", blurb: "Names, the ROB, and retiring in program order.", order: 1, prerequisites: ["cpu-m-pred"], spineIds: ["cpu-renaming", "cpu-rob"], learningObjectives: ["Explain why architectural names are too few", "Retire in order after executing out of order"] },
        { id: "cpu-m-memsys", title: "The core's memory system", blurb: "Stores, loads, and the buffers between them.", order: 2, prerequisites: ["cpu-m-ooo"], spineIds: ["cpu-load-store-queue"], learningObjectives: ["Say why a store buffer exists", "Name what memory disambiguation is for"] },
        { id: "cpu-m-mp", title: "Sharing and ordering", blurb: "Coherence, consistency, and speculation's dark side.", order: 3, prerequisites: ["cpu-m-memsys"], spineIds: ["cpu-coherency", "cpu-consistency"], learningObjectives: ["Separate coherence from consistency", "See why speculation creates security surface"] },
      ],
      concepts: [
        concept("cpu-branch-prediction", "Branch prediction", "cpu-m-pred", 2, ["cpu-pipeline"], "Guessing control flow so the pipeline stays full.", { parent: "cpu-pipeline", obj: ["Separate direction prediction from target prediction"] }),
        concept("cpu-btb", "Branch target buffers", "cpu-m-pred", 3, ["cpu-branch-prediction"], "Caching where a branch went last time, not just taken/not-taken.", { parent: "cpu-branch-prediction" }),
        concept("cpu-predictors", "Predictor types", "cpu-m-pred", 3, ["cpu-branch-prediction"], "Local, global, and TAGE-style predictors and why they exist.", { parent: "cpu-branch-prediction" }),
        concept("cpu-ras", "Return address stacks", "cpu-m-pred", 3, ["cpu-branch-prediction"], "Special-casing CALL/RET so returns do not pollute the BTB.", { parent: "cpu-branch-prediction" }),
        concept("cpu-issue-width", "Issue width", "cpu-m-pred", 3, ["cpu-pipeline", "cpu-ilp-idea"], "How many operations a cycle can start if they are ready."),
        concept("cpu-renaming", "Register renaming", "cpu-m-ooo", 2, ["cpu-pipeline"], "Mapping architectural names onto a larger physical file.", { parent: "cpu-pipeline" }),
        concept("cpu-rob", "Reorder buffers", "cpu-m-ooo", 3, ["cpu-renaming"], "Retiring out-of-order work in program order.", { parent: "cpu-renaming" }),
        concept("cpu-ooo-schedule", "Out-of-order scheduling", "cpu-m-ooo", 3, ["cpu-renaming", "cpu-ilp-idea"], "Issuing ready work, not the next instruction in program order.", { parent: "cpu-renaming" }),
        concept("cpu-wakeup-select", "Wakeup and select", "cpu-m-ooo", 4, ["cpu-ooo-schedule"], "Broadcasting completions and picking the next ready ops.", { parent: "cpu-ooo-schedule" }),
        concept("cpu-precise-exceptions", "Precise exceptions", "cpu-m-ooo", 4, ["cpu-rob"], "The illusion that nothing after the faulting instruction happened."),
        concept("cpu-smt", "Simultaneous multithreading", "cpu-m-ooo", 4, ["cpu-ooo-schedule"], "Filling issue slots from another thread when this one cannot."),
        concept("cpu-load-store-queue", "Load/store queues", "cpu-m-memsys", 3, ["cpu-ooo-schedule"], "Tracking memory ops so they can complete without lying about order."),
        concept("cpu-memory-disambig", "Memory disambiguation", "cpu-m-memsys", 4, ["cpu-load-store-queue"], "Guessing that a load does not overlap an earlier store."),
        concept("cpu-speculative-load", "Speculative loads", "cpu-m-memsys", 4, ["cpu-memory-disambig", "cpu-branch-prediction"], "Starting a load before you know you should."),
        concept("cpu-store-buffer", "Store buffers", "cpu-m-memsys", 3, ["cpu-write-policy"], "Letting the core retire a store before memory has it."),
        concept("cpu-mshr", "Miss-status holding registers", "cpu-m-memsys", 4, ["cpu-cache-miss"], "Outstanding misses as first-class state."),
        concept("cpu-prefetch", "Hardware prefetch", "cpu-m-memsys", 3, ["cpu-cache-miss"], "Starting the next line because the past looked sequential."),
        concept("cpu-inclusive-cache", "Inclusion and exclusivity", "cpu-m-memsys", 4, ["cpu-cache-levels"], "Whether a line in L1 must also live in L2."),
        concept("cpu-coherency", "Cache coherency", "cpu-m-mp", 2, ["cpu-pipeline"], "Keeping private caches honest across cores.", { parent: "cpu-pipeline" }),
        concept("cpu-mesi", "MESI-style protocols", "cpu-m-mp", 3, ["cpu-coherency"], "Invalidation as the way two writers do not invent two truths.", { parent: "cpu-coherency" }),
        concept("cpu-snoop-vs-dir", "Snooping versus directories", "cpu-m-mp", 4, ["cpu-mesi"], "Broadcast versus asking a known owner."),
        concept("cpu-consistency", "Memory consistency", "cpu-m-mp", 3, ["cpu-coherency"], "What stores another core is allowed to see, and when."),
        concept("cpu-tso-vs-relaxed", "TSO and relaxed models", "cpu-m-mp", 4, ["cpu-consistency"], "Why x86 feels stronger than a phone core."),
        concept("cpu-vector-simd", "SIMD and vectors", "cpu-m-mp", 3, ["arch-data-parallel"], "One instruction, many packed elements, no implicit divergence."),
        concept("cpu-vliw", "VLIW as compile-time ILP", "cpu-m-mp", 4, ["cpu-ilp-idea"], "The compiler packs the issue group so the hardware does not have to."),
        concept("cpu-power-wall", "The power wall", "cpu-m-mp", 3, ["cpu-perf-metrics"], "Why frequency stopped being the scaling story."),
        concept("cpu-security-spec", "Speculation and side channels", "cpu-m-mp", 5, ["cpu-speculative-load", "cpu-predictors"], "Transient state that microarchitecture can observe even when architecture cannot."),
        concept("cpu-microcode", "Microcode assists", "cpu-m-mp", 4, ["cpu-isa"], "Complex ops that become little programs inside the core."),
      ],
    },
    {
      id: "arch-gpu",
      title: "GPU Architecture and Parallel Execution",
      categoryId: "cpu",
      description: "Throughput hardware: grids, SIMT, warps, occupancy, and the schedulers that hide latency. Surprise Me may drop you in this subject; it will not start you on occupancy.",
      curriculumVersion: 1,
      orderHint: 2,
      difficultyRange: [2, 5],
      entryRequirements: ["cpu-pipeline", "arch-data-parallel"],
      sourceReferences: [
        { id: "stanford-cs149", title: "Stanford CS149 Parallel Computing", url: "https://gfxcourses.stanford.edu/cs149/fall25/", kind: "syllabus", notes: "GPU after multi-core and data-parallel thinking." },
        { id: "nvidia-educators", title: "NVIDIA CUDA C++ Programming Guide", url: "https://developer.nvidia.com/educators/existing-courses", kind: "vendor", notes: "Thread hierarchy → SIMT/warps → memory → occupancy/divergence as performance." },
        { id: "mit-6823", title: "MIT 6.823", url: "https://ocw.mit.edu/courses/6-823-computer-system-architecture-fall-2005/pages/syllabus/", kind: "ocw", notes: "Vectors/GPUs after pipelining and OOO, not as a first encounter with hardware." },
      ],
      modules: [
        { id: "arch-gpu-simt", title: "GPU execution model", blurb: "Why a GPU exists, then grids, SIMT, warps.", order: 0, prerequisites: [], spineIds: ["gpu-why-throughput", "gpu-execution-model", "gpu-simt", "gpu-warps"] },
        { id: "arch-gpu-resources", title: "Resources and the memory hierarchy", blurb: "What a warp is competing for, and where data lives.", order: 1, prerequisites: ["arch-gpu-simt"], spineIds: ["gpu-memory-hierarchy", "gpu-occupancy"] },
        { id: "arch-gpu-schedule", title: "Hiding latency, paying for divergence", blurb: "Scheduling interactions — the advanced end of this course.", order: 2, prerequisites: ["arch-gpu-resources"], spineIds: ["gpu-divergence", "gpu-latency-hiding"] },
        { id: "arch-gpu-systems", title: "Beyond one SM", blurb: "Atomics, multi-GPU, and specialized units.", order: 3, prerequisites: ["arch-gpu-schedule"], spineIds: ["gpu-atomics"] },
      ],
      concepts: [
        concept("gpu-why-throughput", "Why a GPU exists", "arch-gpu-simt", 2, ["arch-data-parallel", "cpu-pipeline"], "Spending transistors on ALUs instead of speculation when the work is wide.", { parent: "arch-data-parallel", obj: ["Contrast a latency-optimized core with a throughput-optimized one", "Say what kind of program a GPU is for"] }),
        concept("gpu-execution-model", "Grid, block, thread", "arch-gpu-simt", 3, ["gpu-why-throughput"], "The programmer-visible hierarchy a kernel is launched over.", { parent: "gpu-why-throughput", obj: ["Map a kernel launch onto threads, blocks, and a grid", "Keep the programming model separate from the hardware warp"] }),
        concept("gpu-kernel-launch", "Kernel launch", "arch-gpu-simt", 3, ["gpu-execution-model"], "A host-side decision that creates millions of threads the hardware will schedule.", { parent: "gpu-execution-model" }),
        concept("gpu-simt", "SIMT versus SIMD", "arch-gpu-simt", 3, ["gpu-execution-model"], "One instruction stream, many threads, with implicit lockstep and a way to mask lanes.", { parent: "gpu-execution-model", obj: ["Distinguish SIMT from packed SIMD", "Explain why a scalar-looking kernel still runs in lockstep"] }),
        concept("gpu-simd-lane", "Lanes and masks", "arch-gpu-simt", 3, ["gpu-simt", "cpu-vector-simd"], "A disabled lane still occupies the cycle."),
        concept("gpu-warps", "Warps and wavefronts", "arch-gpu-simt", 3, ["gpu-simt"], "The hardware scheduling quantum — 32 or 64 threads sharing an instruction.", { parent: "gpu-simt", obj: ["Name the warp/wavefront as the unit the scheduler sees", "Explain why block size that is not a multiple of the warp width wastes lanes"] }),
        concept("gpu-exec-resources", "Execution resources", "arch-gpu-resources", 4, ["gpu-warps"], "ALUs, special-function units, and load/store pipes a SM/CU actually has.", { parent: "gpu-warps" }),
        concept("gpu-memory-hierarchy", "GPU memory hierarchy", "arch-gpu-resources", 4, ["gpu-warps"], "Registers, shared/LDS, L1/L2, and HBM — different spaces, different costs.", { parent: "gpu-warps" }),
        concept("gpu-shared-mem", "Shared memory / LDS", "arch-gpu-resources", 4, ["gpu-memory-hierarchy"], "A software-managed scratchpad visible to a block.", { parent: "gpu-memory-hierarchy" }),
        concept("gpu-bank-conflict", "Bank conflicts", "arch-gpu-resources", 4, ["gpu-shared-mem"], "When several threads hit the same shared-memory bank and serialize."),
        concept("gpu-coalescing", "Memory coalescing", "arch-gpu-resources", 4, ["gpu-memory-hierarchy"], "Adjacent threads touching adjacent addresses become one transaction.", { parent: "gpu-memory-hierarchy" }),
        concept("gpu-occupancy", "Occupancy", "arch-gpu-resources", 4, ["gpu-exec-resources", "gpu-memory-hierarchy"], "How many warps can live on a processor at once, limited by registers and shared memory.", { parent: "gpu-exec-resources" }),
        concept("gpu-occupancy-math", "Occupancy as a budget", "arch-gpu-resources", 4, ["gpu-occupancy"], "Registers × warps × blocks against a finite file.", { parent: "gpu-occupancy" }),
        concept("gpu-divergence", "Control divergence", "arch-gpu-schedule", 4, ["gpu-warps", "gpu-occupancy"], "Threads in a warp taking different paths, so both sides run under a mask.", { parent: "gpu-warps" }),
        concept("gpu-latency-hiding", "Latency hiding", "arch-gpu-schedule", 4, ["gpu-occupancy"], "Switching to another ready warp instead of stalling the whole machine on a miss.", { parent: "gpu-occupancy" }),
        concept("gpu-ilp-vs-tlp", "ILP versus TLP on a GPU", "arch-gpu-schedule", 4, ["gpu-latency-hiding", "cpu-ilp-idea"], "Instruction slack inside a thread versus more warps."),
        concept("gpu-scheduler", "Warp scheduling", "arch-gpu-schedule", 5, ["gpu-latency-hiding", "gpu-divergence"], "Which ready warp runs next, and why that interacts with caches and issue width.", { parent: "gpu-latency-hiding" }),
        concept("gpu-resource-limits", "Resource-limited launch", "arch-gpu-schedule", 5, ["gpu-occupancy", "gpu-scheduler"], "Registers, shared memory, and warp slots as coupled constraints on a kernel.", { parent: "gpu-occupancy" }),
        concept("gpu-persistent-threads", "Persistent threads", "arch-gpu-schedule", 5, ["gpu-scheduler"], "A kernel that lives and pulls work, instead of one launch per tile."),
        concept("gpu-atomics", "Atomics and contention", "arch-gpu-systems", 4, ["gpu-memory-hierarchy"], "Read-modify-write that stays correct when many threads hit one address."),
        concept("gpu-unified-mem", "Unified virtual memory", "arch-gpu-systems", 4, ["gpu-memory-hierarchy", "cpu-virtual-addr"], "A single address space whose pages migrate, with a cost."),
        concept("gpu-tensor-core", "Tensor / matrix units", "arch-gpu-systems", 5, ["gpu-exec-resources", "cpu-vector-simd"], "Specialized pipes for dense matrix fragments."),
        concept("gpu-multi-gpu", "Multi-GPU communication", "arch-gpu-systems", 5, ["gpu-memory-hierarchy"], "NVLink, PCIe, and the fact that 'the GPU' is often several."),
        concept("gpu-graph-capture", "Work graphs and capture", "arch-gpu-systems", 5, ["gpu-kernel-launch"], "Recording a launch sequence so the host is not in the inner loop."),
      ],
    },
  ];
}
