/**
 * Semiconductors, operating systems, networking, compilers.
 * Authoring only — runtime loads the generated JSON.
 */
export function systemsCourses(concept) {
  return [
    {
      id: "semi-process",
      title: "Semiconductor Process Foundations",
      categoryId: "semiconductors",
      description: "From crystal to patterned films: wafer, oxidation, implant, deposition, etch, and why integration is later than any single step.",
      curriculumVersion: 1,
      orderHint: 0,
      difficultyRange: [0, 3],
      entryRequirements: [],
      sourceReferences: [
        { id: "mit-6152j", title: "MIT 6.152J Micro/Nano Processing Technology", url: "https://ocw.mit.edu/courses/6-152j-micro-nano-processing-technology-fall-2005/pages/syllabus/", kind: "ocw", notes: "Unit processes before a finished device. Lithography is one peer among oxidation, deposition, etch." },
        { id: "mit-6774", title: "MIT 6.774 Physics of Microfabrication", url: "https://ocw.mit.edu/courses/6-774-physics-of-microfabrication-front-end-processing-fall-2004/", kind: "ocw", notes: "Front-end physics as mechanisms, not tool brochures." },
      ],
      modules: [
        { id: "semi-p-wafer", title: "The wafer", blurb: "Crystal, cleanliness, and the starting surface.", order: 0, prerequisites: [], spineIds: ["semi-wafer"] },
        { id: "semi-p-front", title: "Front-end films and dopants", blurb: "Oxidation, diffusion, implant, anneal.", order: 1, prerequisites: ["semi-p-wafer"], spineIds: ["semi-oxide", "semi-implant"] },
        { id: "semi-p-shape", title: "Adding and removing material", blurb: "Deposition, etch, planarization.", order: 2, prerequisites: ["semi-p-front"], spineIds: ["semi-cvd", "semi-etch-plasma"] },
        { id: "semi-p-integrate", title: "Making a device of it", blurb: "Isolation, gates, yield as a property of the flow.", order: 3, prerequisites: ["semi-p-shape"], spineIds: ["semi-integration", "semi-yield-intro"] },
      ],
      concepts: [
        concept("semi-crystal", "Single-crystal silicon", "semi-p-wafer", 0, [], "Why a chip starts as an ordered lattice, not a metal lump."),
        concept("semi-wafer", "Wafer preparation", "semi-p-wafer", 0, ["semi-crystal"], "Slicing, polishing, and the surface everything else will inherit."),
        concept("semi-clean", "Contamination and cleans", "semi-p-wafer", 1, ["semi-wafer"], "Particles and metals as yield before any pattern exists."),
        concept("semi-oxide", "Thermal oxidation", "semi-p-front", 1, ["semi-wafer"], "Growing SiO2 from the wafer itself."),
        concept("semi-diffusion", "Diffusion of dopants", "semi-p-front", 1, ["semi-wafer"], "Concentration profiles as a function of time and temperature."),
        concept("semi-implant", "Ion implantation", "semi-p-front", 2, ["semi-diffusion"], "Placing dopants with an accelerator, then repairing the damage."),
        concept("semi-anneal", "Anneal and activation", "semi-p-front", 2, ["semi-implant"], "Healing the lattice so the dopant actually dopes."),
        concept("semi-cvd", "Chemical vapor deposition", "semi-p-shape", 2, ["semi-oxide"], "Growing a film from a gas that reacts on the surface."),
        concept("semi-pvd", "Physical vapor deposition", "semi-p-shape", 2, ["semi-cvd"], "Throwing atoms at the wafer — sputtering and evaporation."),
        concept("semi-epitaxy", "Epitaxy", "semi-p-shape", 3, ["semi-cvd", "semi-crystal"], "A film that continues the crystal underneath."),
        concept("semi-etch-wet", "Wet etching", "semi-p-shape", 1, ["semi-oxide"], "Isotropic chemistry that undercuts."),
        concept("semi-etch-plasma", "Plasma etching", "semi-p-shape", 2, ["semi-etch-wet"], "Anisotropic removal so sidewalls can be vertical."),
        concept("semi-cmp", "Chemical-mechanical planarization", "semi-p-shape", 2, ["semi-cvd"], "Making the wafer flat enough for the next lithography."),
        concept("semi-metals", "Metallization", "semi-p-shape", 2, ["semi-pvd"], "Wires on the chip, and the barriers that keep them from wandering."),
        concept("semi-dielectric", "Interlevel dielectrics", "semi-p-shape", 2, ["semi-cvd"], "The insulators between metal layers."),
        concept("semi-isolation", "Device isolation", "semi-p-integrate", 2, ["semi-oxide", "semi-etch-plasma"], "Keeping neighboring transistors from sharing a channel."),
        concept("semi-well", "Wells and channel engineering", "semi-p-integrate", 3, ["semi-implant"], "The doped tubs a MOSFET lives in."),
        concept("semi-gate-stack", "The gate stack", "semi-p-integrate", 3, ["semi-oxide", "semi-cvd"], "Dielectric plus electrode as the MOSFET's control surface."),
        concept("semi-silicide", "Silicides and contacts", "semi-p-integrate", 3, ["semi-metals"], "Low-resistance meetings of silicon and metal."),
        concept("semi-integration", "Process integration", "semi-p-integrate", 3, ["semi-gate-stack", "semi-isolation"], "The sequence is the device. Order is not decorative."),
        concept("semi-yield-intro", "Yield as a process property", "semi-p-integrate", 2, ["semi-clean", "semi-integration"], "Good die per wafer, owned by defectivity and process window."),
        concept("semi-defect-class", "Defect classes", "semi-p-integrate", 3, ["semi-yield-intro"], "Particles, pattern defects, and parametric misses."),
        concept("semi-metrology", "In-line metrology", "semi-p-integrate", 3, ["semi-integration"], "Measuring thickness, CD, and overlay before the lot is lost."),
        concept("semi-moscap", "The MOS capacitor", "semi-p-integrate", 2, ["semi-oxide"], "The simplest device that still teaches the stack."),
        concept("semi-planarity", "Why flatness is a lithography input", "semi-p-integrate", 2, ["semi-cmp"], "Depth of focus does not forgive topography."),
        concept("semi-contamination", "Cross-contamination between tools", "semi-p-integrate", 3, ["semi-clean"], "A metal that is fine in one module poisons another."),
      ],
    },
    {
      id: "semi-litho",
      title: "Lithography and Patterning",
      categoryId: "semiconductors",
      description: "How a pattern becomes a feature: resists, exposure, Rayleigh, DUV, multiple patterning, then EUV as a later light source — not the first word.",
      curriculumVersion: 1,
      orderHint: 1,
      difficultyRange: [1, 5],
      entryRequirements: ["semi-wafer", "semi-planarity"],
      sourceReferences: [
        { id: "mit-6152j", title: "MIT 6.152J", url: "https://ocw.mit.edu/courses/6-152j-micro-nano-processing-technology-fall-2005/pages/syllabus/", kind: "ocw", notes: "Photolithography as a unit process after the wafer exists." },
        { id: "asml-optics", title: "ASML lenses and mirrors", url: "https://www.asml.com/en/technology/lithography-principles/lenses-and-mirrors", kind: "vendor", notes: "Rayleigh, NA, refractive DUV vs reflective EUV." },
        { id: "asml-euv", title: "ASML EUV systems", url: "https://www.asml.com/en/products/euv-lithography-systems", kind: "vendor", notes: "Source, mirrors, vacuum. High-NA is a later platform." },
      ],
      modules: [
        { id: "semi-l-basics", title: "Printing a layer", blurb: "Mask, resist, exposure, develop.", order: 0, prerequisites: [], spineIds: ["semi-litho", "semi-resist"] },
        { id: "semi-l-limits", title: "What sets resolution", blurb: "Rayleigh, k1, process window.", order: 1, prerequisites: ["semi-l-basics"], spineIds: ["semi-rayleigh"] },
        { id: "semi-l-duv", title: "DUV and tricks that extend it", blurb: "Immersion, OPC, multiple patterning.", order: 2, prerequisites: ["semi-l-limits"], spineIds: ["semi-duv", "semi-multi-pattern"] },
        { id: "semi-l-euv", title: "EUV as a light source", blurb: "13.5 nm, mirrors, stochastics.", order: 3, prerequisites: ["semi-l-duv"], spineIds: ["semi-euv", "semi-stochastics"] },
      ],
      concepts: [
        concept("semi-litho", "Photolithography", "semi-l-basics", 1, ["semi-wafer"], "Projecting patterns into resist to define features."),
        concept("semi-resist", "Photoresists", "semi-l-basics", 1, ["semi-litho"], "A film that changes solubility where the light hit.", { parent: "semi-litho" }),
        concept("semi-mask", "Masks and reticles", "semi-l-basics", 1, ["semi-litho"], "The chrome (or multilayer) original the stepper reduces."),
        concept("semi-exposure", "Exposure and develop", "semi-l-basics", 1, ["semi-resist"], "Dose as the thing you can miss in either direction."),
        concept("semi-alignment", "Alignment marks", "semi-l-basics", 2, ["semi-litho"], "How this layer finds the last one."),
        concept("semi-rayleigh", "The Rayleigh criterion", "semi-l-limits", 2, ["semi-litho"], "Resolution as k1 · λ / NA — three knobs, not one slogan.", { parent: "semi-litho" }),
        concept("semi-k1", "The k1 factor", "semi-l-limits", 3, ["semi-rayleigh"], "Process and illumination cleverness packed into a dimensionless number."),
        concept("semi-process-window", "The process window", "semi-l-limits", 3, ["semi-exposure", "semi-rayleigh"], "Focus and dose ranges that still print a legal CD."),
        concept("semi-focus-expose", "Focus-exposure matrices", "semi-l-limits", 3, ["semi-process-window"], "The bossung plot as a lab object."),
        concept("semi-ler", "Line-edge roughness", "semi-l-limits", 3, ["semi-resist"], "The wall is not a straight line."),
        concept("semi-duv", "Deep ultraviolet lithography", "semi-l-duv", 2, ["semi-rayleigh"], "248 and 193 nm as the workhorses that still print most layers."),
        concept("semi-immersion", "Immersion lithography", "semi-l-duv", 3, ["semi-duv"], "Water between lens and wafer to raise NA."),
        concept("semi-opc", "Optical proximity correction", "semi-l-duv", 3, ["semi-duv"], "Distorting the mask so the wafer looks like the drawing."),
        concept("semi-pec", "Proximity and flare", "semi-l-duv", 3, ["semi-opc"], "Neighbors and stray light changing the dose you thought you set."),
        concept("semi-multi-pattern", "Multiple patterning", "semi-l-duv", 3, ["semi-duv", "semi-etch-plasma"], "Splitting one drawn layer across several litho-etch passes."),
        concept("semi-pitch-split", "Pitch splitting", "semi-l-duv", 4, ["semi-multi-pattern"], "Why a 20 nm pitch is not a 20 nm exposure."),
        concept("semi-overlay-basics", "Overlay as a lithography budget", "semi-l-duv", 3, ["semi-alignment", "semi-litho"], "Layer-to-layer error before anyone says EUV."),
        concept("semi-euv", "EUV lithography", "semi-l-euv", 3, ["semi-litho"], "13.5 nm light, mirrors, and why refractive optics die.", { parent: "semi-litho" }),
        concept("semi-euv-source", "The EUV source", "semi-l-euv", 4, ["semi-euv"], "A CO2 laser on tin droplets, tens of thousands of times a second.", { parent: "semi-euv" }),
        concept("semi-euv-mirrors", "Multilayer mirrors", "semi-l-euv", 4, ["semi-euv"], "Bragg reflectors because nothing is a lens at 13.5 nm.", { parent: "semi-euv" }),
        concept("semi-euv-vacuum", "Vacuum beam path", "semi-l-euv", 4, ["semi-euv"], "Air eats EUV. The whole column is a chamber."),
        concept("semi-pellicle", "EUV pellicles", "semi-l-euv", 4, ["semi-euv"], "A membrane that must protect the mask without eating the photons."),
        concept("semi-stochastics", "Stochastic defects", "semi-l-euv", 4, ["semi-euv"], "Photon and photoacid shot noise at EUV doses.", { parent: "semi-euv" }),
        concept("semi-na", "Numerical aperture", "semi-l-euv", 4, ["semi-euv"], "How High-NA EUV buys resolution and spends depth of focus.", { parent: "semi-euv" }),
        concept("semi-overlay", "Overlay", "semi-l-euv", 4, ["semi-euv"], "Layer-to-layer alignment as a yield budget, not a slogan.", { parent: "semi-euv" }),
      ],
    },
    {
      id: "semi-leading",
      title: "Modern Leading-Edge Manufacturing",
      categoryId: "semiconductors",
      description: "After the unit processes and EUV exist: High-NA, stochastics as a limiter, advanced devices, packaging, and the scaling constraints a reporter actually meets.",
      curriculumVersion: 1,
      orderHint: 2,
      difficultyRange: [3, 5],
      entryRequirements: ["semi-euv", "semi-integration", "semi-na"],
      sourceReferences: [
        { id: "asml-euv", title: "ASML EUV lithography systems", url: "https://www.asml.com/en/products/euv-lithography-systems", kind: "vendor", notes: "NXE 0.33 vs EXE 0.55. High-NA after EUV is already thinkable." },
        { id: "asml-optics", title: "ASML lithography principles", url: "https://www.asml.com/en/technology/lithography-principles/lenses-and-mirrors", kind: "vendor", notes: "NA is not a score. Wavelength travels with it." },
      ],
      modules: [
        { id: "semi-a-highna", title: "High-NA as a platform", blurb: "0.55, anamorphic optics, new masks.", order: 0, prerequisites: [], spineIds: ["semi-high-na"] },
        { id: "semi-a-limit", title: "What still kills yield", blurb: "Stochastics, overlay budgets, defectivity.", order: 1, prerequisites: ["semi-a-highna"], spineIds: ["semi-stochastic-limit", "semi-defectivity"] },
        { id: "semi-a-device", title: "Devices after planar", blurb: "Fins, gates-all-around, backside power.", order: 2, prerequisites: ["semi-a-limit"], spineIds: ["semi-finfet"] },
        { id: "semi-a-pack", title: "When the die is not the product", blurb: "Chiplets, HBM, advanced packaging.", order: 3, prerequisites: ["semi-a-device"], spineIds: ["semi-chiplets", "semi-scaling-wall"] },
      ],
      concepts: [
        concept("semi-high-na", "High-NA EUV", "semi-a-highna", 5, ["semi-na"], "0.55 NA as a new scanner family, not a bigger number on the same tool.", { parent: "semi-na" }),
        concept("semi-high-na-optics", "Anamorphic High-NA optics", "semi-a-highna", 5, ["semi-high-na", "semi-euv-mirrors"], "Different demagnification in X and Y so the mask stays printable."),
        concept("semi-high-na-mask", "High-NA mask 3D effects", "semi-a-highna", 5, ["semi-high-na", "semi-mask"], "The absorber has thickness. At these angles that matters."),
        concept("semi-high-na-process", "High-NA process implications", "semi-a-highna", 5, ["semi-high-na", "semi-process-window"], "Smaller depth of focus, new resists, new inspection."),
        concept("semi-mask-3d", "Mask 3D effects", "semi-a-highna", 4, ["semi-euv-mirrors", "semi-mask"], "A '2D' pattern sitting on a multilayer is not 2D to the light."),
        concept("semi-anamorphic", "Anamorphic imaging", "semi-a-highna", 5, ["semi-high-na-optics"], "Why the reticle field is no longer a simple 4× shrink in both axes."),
        concept("semi-stochastic-limit", "Stochastics as a scaling wall", "semi-a-limit", 5, ["semi-stochastics", "semi-na"], "More NA does not buy you photons."),
        concept("semi-defectivity", "Leading-edge defectivity", "semi-a-limit", 4, ["semi-defect-class", "semi-euv"], "What a killer defect looks like when the CD is a handful of nanometers."),
        concept("semi-overlay-budget", "Overlay at the leading edge", "semi-a-limit", 4, ["semi-overlay", "semi-multi-pattern"], "Error budgets measured in fractions of a nanometer."),
        concept("semi-euv-throughput", "EUV throughput and dose", "semi-a-limit", 4, ["semi-euv-source", "semi-stochastics"], "Source power versus the dose stochastics demand."),
        concept("semi-yield-model", "Yield models", "semi-a-limit", 4, ["semi-yield-intro"], "Poisson and beyond: why die size and defect density fight."),
        concept("semi-finfet", "FinFETs", "semi-a-device", 4, ["semi-gate-stack", "semi-integration"], "A channel you wrap, not a plane you sit on."),
        concept("semi-gag", "Gate-all-around", "semi-a-device", 5, ["semi-finfet"], "Nanosheets as the fin's successor."),
        concept("semi-cfet", "CFETs", "semi-a-device", 5, ["semi-gag"], "Stacking n and p to keep scaling the inverter."),
        concept("semi-backside-power", "Backside power delivery", "semi-a-device", 5, ["semi-metals", "semi-integration"], "Power vias from the other face so signal wiring can breathe."),
        concept("semi-dtco", "Design-technology co-optimization", "semi-a-device", 4, ["semi-integration"], "The standard cell and the process invent each other."),
        concept("semi-chiplets", "Chiplets", "semi-a-pack", 4, ["semi-yield-model"], "Yielding small die and assembling the product."),
        concept("semi-hbm-stack", "HBM stacking", "semi-a-pack", 4, ["semi-chiplets"], "Memory cubes next to compute, with a thermal bill."),
        concept("semi-advanced-packaging", "Advanced packaging", "semi-a-pack", 4, ["semi-chiplets"], "Interposers, bridges, and the factory after the fab."),
        concept("semi-multi-beam", "Multi-beam inspection and write", "semi-a-pack", 5, ["semi-metrology"], "When a single beam cannot visit every feature in time."),
        concept("semi-cost-per-wafer", "Cost per wafer", "semi-a-pack", 4, ["semi-euv-throughput", "semi-yield-model"], "A scanner is a factory. Depreciation shows up in the die."),
        concept("semi-scaling-wall", "Scaling constraints", "semi-a-pack", 5, ["semi-stochastic-limit", "semi-cost-per-wafer"], "Cost, heat, stochastics, and the fact that λ already jumped."),
      ],
    },
  ];
}
