/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as GraphRouteImport } from './routes/graph'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as LibraryRouteImport } from './routes/library'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ReviewsRouteImport } from './routes/reviews'
import { Route as SessionRouteImport } from './routes/session'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as TopicsRouteImport } from './routes/topics'
import { Route as CourseCourseIdRouteImport } from './routes/course.$courseId'
import { Route as LearnLessonIdRouteImport } from './routes/learn.$lessonId'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as LearnLessonIdQuizRouteImport } from './routes/learn_.$lessonId.quiz'
import { Route as LearnLessonIdRateRouteImport } from './routes/learn_.$lessonId.rate'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const GraphRoute = GraphRouteImport.update({
  id: '/graph',
  path: '/graph',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryRoute = LibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewsRoute = ReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionRoute = SessionRouteImport.update({
  id: '/session',
  path: '/session',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const TopicsRoute = TopicsRouteImport.update({
  id: '/topics',
  path: '/topics',
  getParentRoute: () => rootRouteImport,
} as any)
const CourseCourseIdRoute = CourseCourseIdRouteImport.update({
  id: '/course/$courseId',
  path: '/course/$courseId',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnLessonIdRoute = LearnLessonIdRouteImport.update({
  id: '/learn/$lessonId',
  path: '/learn/$lessonId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnLessonIdQuizRoute = LearnLessonIdQuizRouteImport.update({
  id: '/learn_/$lessonId/quiz',
  path: '/learn/$lessonId/quiz',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnLessonIdRateRoute = LearnLessonIdRateRouteImport.update({
  id: '/learn_/$lessonId/rate',
  path: '/learn/$lessonId/rate',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/graph': typeof GraphRoute
  '/history': typeof HistoryRoute
  '/library': typeof LibraryRoute
  '/login': typeof LoginRoute
  '/reviews': typeof ReviewsRoute
  '/session': typeof SessionRoute
  '/settings': typeof SettingsRoute
  '/topics': typeof TopicsRoute
  '/course/$courseId': typeof CourseCourseIdRoute
  '/learn/$lessonId': typeof LearnLessonIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/learn/$lessonId/quiz': typeof LearnLessonIdQuizRoute
  '/learn/$lessonId/rate': typeof LearnLessonIdRateRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/graph': typeof GraphRoute
  '/history': typeof HistoryRoute
  '/library': typeof LibraryRoute
  '/login': typeof LoginRoute
  '/reviews': typeof ReviewsRoute
  '/session': typeof SessionRoute
  '/settings': typeof SettingsRoute
  '/topics': typeof TopicsRoute
  '/course/$courseId': typeof CourseCourseIdRoute
  '/learn/$lessonId': typeof LearnLessonIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/learn/$lessonId/quiz': typeof LearnLessonIdQuizRoute
  '/learn/$lessonId/rate': typeof LearnLessonIdRateRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/graph': typeof GraphRoute
  '/history': typeof HistoryRoute
  '/library': typeof LibraryRoute
  '/login': typeof LoginRoute
  '/reviews': typeof ReviewsRoute
  '/session': typeof SessionRoute
  '/settings': typeof SettingsRoute
  '/topics': typeof TopicsRoute
  '/course/$courseId': typeof CourseCourseIdRoute
  '/learn/$lessonId': typeof LearnLessonIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/learn_/$lessonId/quiz': typeof LearnLessonIdQuizRoute
  '/learn_/$lessonId/rate': typeof LearnLessonIdRateRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/graph'
    | '/history'
    | '/library'
    | '/login'
    | '/reviews'
    | '/session'
    | '/settings'
    | '/topics'
    | '/course/$courseId'
    | '/learn/$lessonId'
    | '/api/auth/$'
    | '/learn/$lessonId/quiz'
    | '/learn/$lessonId/rate'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/graph'
    | '/history'
    | '/library'
    | '/login'
    | '/reviews'
    | '/session'
    | '/settings'
    | '/topics'
    | '/course/$courseId'
    | '/learn/$lessonId'
    | '/api/auth/$'
    | '/learn/$lessonId/quiz'
    | '/learn/$lessonId/rate'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/graph'
    | '/history'
    | '/library'
    | '/login'
    | '/reviews'
    | '/session'
    | '/settings'
    | '/topics'
    | '/course/$courseId'
    | '/learn/$lessonId'
    | '/api/auth/$'
    | '/learn_/$lessonId/quiz'
    | '/learn_/$lessonId/rate'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  GraphRoute: typeof GraphRoute
  HistoryRoute: typeof HistoryRoute
  LibraryRoute: typeof LibraryRoute
  LoginRoute: typeof LoginRoute
  ReviewsRoute: typeof ReviewsRoute
  SessionRoute: typeof SessionRoute
  SettingsRoute: typeof SettingsRoute
  TopicsRoute: typeof TopicsRoute
  CourseCourseIdRoute: typeof CourseCourseIdRoute
  LearnLessonIdRoute: typeof LearnLessonIdRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  LearnLessonIdQuizRoute: typeof LearnLessonIdQuizRoute
  LearnLessonIdRateRoute: typeof LearnLessonIdRateRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/graph': {
      id: '/graph'
      path: '/graph'
      fullPath: '/graph'
      preLoaderRoute: typeof GraphRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library': {
      id: '/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof LibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reviews': {
      id: '/reviews'
      path: '/reviews'
      fullPath: '/reviews'
      preLoaderRoute: typeof ReviewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/session': {
      id: '/session'
      path: '/session'
      fullPath: '/session'
      preLoaderRoute: typeof SessionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/topics': {
      id: '/topics'
      path: '/topics'
      fullPath: '/topics'
      preLoaderRoute: typeof TopicsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/course/$courseId': {
      id: '/course/$courseId'
      path: '/course/$courseId'
      fullPath: '/course/$courseId'
      preLoaderRoute: typeof CourseCourseIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn/$lessonId': {
      id: '/learn/$lessonId'
      path: '/learn/$lessonId'
      fullPath: '/learn/$lessonId'
      preLoaderRoute: typeof LearnLessonIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn_/$lessonId/quiz': {
      id: '/learn_/$lessonId/quiz'
      path: '/learn/$lessonId/quiz'
      fullPath: '/learn/$lessonId/quiz'
      preLoaderRoute: typeof LearnLessonIdQuizRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn_/$lessonId/rate': {
      id: '/learn_/$lessonId/rate'
      path: '/learn/$lessonId/rate'
      fullPath: '/learn/$lessonId/rate'
      preLoaderRoute: typeof LearnLessonIdRateRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  GraphRoute: GraphRoute,
  HistoryRoute: HistoryRoute,
  LibraryRoute: LibraryRoute,
  LoginRoute: LoginRoute,
  ReviewsRoute: ReviewsRoute,
  SessionRoute: SessionRoute,
  SettingsRoute: SettingsRoute,
  TopicsRoute: TopicsRoute,
  CourseCourseIdRoute: CourseCourseIdRoute,
  LearnLessonIdRoute: LearnLessonIdRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  LearnLessonIdQuizRoute: LearnLessonIdQuizRoute,
  LearnLessonIdRateRoute: LearnLessonIdRateRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
